### ISSUE TITLE
Output Cache 1.9 and Authenticated Requests

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5157]
I was just testing out authenticated output caching, and noticed something that effectively breaks this feature for us.

We have unique content on the website based on two things:
  1. User Account (Welcome [username] message)
  2. User Role 
      *  Widgets that display different content depending on role
      *  Navigation that displays different menu items depending on role

I've noticed that with caching authenticated requests enabled (testing on my local dev environment), the unique content will be cached and served up to a different user. 

i.e. If I'm logged in as User2 and the page I'm visiting was cached by User1, the welcome message would say Welcome User1.  The same applies to all other content.

I'm not sure how many people this would affect, and caching authenticated content would be great (if we could implement it or split it up by module and role).  Don't cache this, do cache this for all role members of role [x]...etc.  Not sure the best way to go about this or if this is even feasible, but perhaps a cache key which include role may be sufficient.

Thoughts?

**Comment by Jetski5822** [comment]
Yeah, I have seen this happen too. I think the behavior is wrong, i think the cache key needs the user Id in it.

**Comment by dcinzona** [comment]
If that's the case, an ideal scenario would also include longer cache TTL for authenticated requests (or at least a different TTL).  I would love to be able to cache some layouts or shapes specifically though - for example: the welcome message.  No need to hit the DB every time to get the User first and last names (that is what we are displaying in our case, not the username).  

On a side note, we could just store that in a cookie instead...with the Claims token, including what roles the user has (this is updated on login and pulled from the database every page load).  If roles are updated in the middle of a session, we would want to expire the cache for that user.

**Comment by Jetski5822** [comment]
@DanielStolt whats your take on this? you are the caching man :)

**Comment by dcinzona** [comment]
Per user cache may also increase memory requirements severely.  Maybe requiring something like Redis Cache would be the way to go in this case...not sure.  

Looking forward to hearing from @DanielStolt - also hope he's feeling better.

**Comment by sebastienros** [comment]
I think having the userid as cache might at best be optional. Otherwise this is an intended behavior, your are not supposed to use it if the content varies by user. You are instead supposed to use client based calls (ajax) to render these elements.

But as explained, we could easily allow a userid or role key dependency. We must have talked about it already, so Daniel will be able to answer quite easily.

**Comment by DanielStolt** [comment]
Hey guys, sorry I'm late to the discussion here - for some reason I didn't think about enabling notifications for the Github repo...

Anyway, my take on this: I added this feature to accommodate scenarios/sites where the rendered markup does **not** change based on the user's identity or role memberships. If your site is such that you render role/user specific content, then this feature should not be disabled. It was not intended for such scenarios.

I always saw this as just a first step - it is on my TODO list to also add an option to vary by **role membership**, essentially by adding the IDs of all the user's roles to the cache key in a deterministic order. I think this would solve a large number of scenarios.

Varying the cache key by **user ID** I think would consume too much memory for many sites. But I don't see a problem with adding this as an option also. If you have a lot of RAM or externalized caching or a small number of users, you can enable it.

Additionally on my TODO list is making the cache key generation provider based, so that custom code can contribute cache keys for the current request. This would enable you to do pretty much anything that makes sense for your site, or even for different parts of your site as it would be per-request.

Finally, I think the configuration structure for output cache settings needs to be a lot more flexible. Currently most settings are only configurable for the whole tenant, while a select few of them can also be configured per route. But think we need more flexibility here, such as being able to configure all output cache settings by route, layer rules, content type, etc.

**Comment by kumards** [comment]
What about donut caching? We can cache part of the views.

**Comment by DanielStolt** [comment]
Regarding donut caching, IDeliverable.Widgets can be used to enable ajax loading of any widget, effectively enabling donut caching. https://github.com/IDeliverable/IDeliverable.Widgets

**Comment by kumards** [comment]
Nice solution @DanielStolt!, thanks for sharing.
