### ISSUE TITLE
ReadUncommitted isolation level results in invalid content items being published

### ISSUE THREAD

**Issue by John-Williams** [OrchardCMS/Orchard#5238]
In orchard 1.8.1 + 1.x, (tested using SQL Server 2008) if you set the isolation level as READUNCOMMITTED, by:

1. Uncommenting the configuration in Orchard.Web/Config/Sites.config
2. Click to create a new Page, then click Publish without filling in a Title
3. The Page validates correctly with a big red error about a missing Title, however a content Item is still created.

This is because the content creation validation logic creates a content item and then validates the model against the content item. It then applies a database rollback if the model isn't valid. 
Unfortunately if you set READUNCOMMITTED isolation level, the rollback isn't actually applied, so you're left with invalid content items being created.

A really good fix would be to make the rollback work properly. I'm not sure how to do that.
However a more simple option would be to just move the content creation step to after the validation. I've done that in a fork here:

https://github.com/John-Williams/Orchard/commit/0861eea659a8e4300c899e670cd03b81ce18a275

I could add a pull request with the above change in, but I was hoping for a little feedback first. 
Does anyone know if the validation ever needs the content item persisted to the database first?

**Comment by pszmyd** [comment]
`ReadUncommitted` is dangerous. 

If you're concerned about performance better leave the `ReadCommitted` isolation level as-is and set up your database to use snapshots instead of row-locking:

    ALTER DATABASE MyDatabase
    SET ALLOW_SNAPSHOT_ISOLATION ON

    ALTER DATABASE MyDatabase
    SET READ_COMMITTED_SNAPSHOT ON

**Comment by stevehine** [comment]
Whilst I agree with the senttiment of not using ReadUncommitted; I think John's point is paricularly valid. Why should a model that fails to be validated ever be written to the database - that validation check needs to be done at some point regardless; so writing it out and then rolling back the transaction feels like an unnecessary overhead - unless there is some absolute requirement for it to be done that way round ?

**Comment by jersiovic** [comment]
@pszmyd with READ_COMMITTED_SNAPSHOT ON DDL queries fail, how do you deal with DDL queries in migrations? 
By the moment what I've done is setting variables to this values:
SET ALLOW_SNAPSHOT_ISOLATION ON
SET READ_COMMITTED_SNAPSHOT OFF 
Next I have changed in TransactionManager contructor the default ISolationLevel IsolationLevel.Snapshot;
Problem is it fails when a migrations executes a DDL SQL. So I have changed DefaultMigrationManager to use _transactionManager.RequireNew(System.Data.IsolationLevel.ReadCommitted) to avoid problems.

How do you handle this limitation of the READ_COMMITTED_SNAPSHOT ON mode?

**Comment by MpDzik** [comment]
@jersiovic I have never encountered any problems with using snapshot isolation with Orchard. The query posted by @pszmyd should be all that you need to set it up. What version of SQL Server are you using?

**Comment by jersiovic** [comment]
Microsoft SQL Server 2012 (SP1) Express Edition

**Comment by jersiovic** [comment]
What about TaskLeaseService? It doesn't work well with READ_COMMITTED_SNAPSHOT to ON. It can cause two tasks run at the same time, isnt'it?

**Comment by MpDzik** [comment]
I used only Standard and Enterprise editions of SQL Server, so I can't say much about Express edition, maybe it has some limitations. As for TaskLeaseService, I didn't have any problems with simultaneous tasks, however, I only used the standard Lucene search index builder task which is scheduled every minute. I haven't looked into the implementation of TaskLeaseService. @pszmyd do you have any experience with using custom tasks under snapshot isolation?

**Comment by jersiovic** [comment]
This is the exception I get sometimes with READ_COMMITTED_SNAPSHOT 
`2016-02-24 00:51:56,711 [9] Orchard.Exceptions.DefaultExceptionPolicy - (null) - An unexpected exception was caught [(null)]
System.Data.SqlClient.SqlException (0x80131904): Transaction failed because this DDL statement is not allowed inside a snapshot isolation transaction. Since metadata is not versioned, a metadata change can lead to inconsistency if mixed within snapshot isolation.
   en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   en System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   en System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   en System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   en Orchard.Data.Migration.Interpreters.DefaultDataMigrationInterpreter.RunPendingStatements() en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Data\Migration\Interpreters\DefaultDataMigrationInterpreter.cs:línea 380
   en Orchard.Data.Migration.Interpreters.DefaultDataMigrationInterpreter.Visit(AlterTableCommand command) en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Data\Migration\Interpreters\DefaultDataMigrationInterpreter.cs:línea 153
   en Orchard.Data.Migration.Interpreters.AbstractDataMigrationInterpreter.Visit(ISchemaBuilderCommand command) en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Data\Migration\Interpreters\AbstractDataMigrationInterpreter.cs:línea 17
   en Orchard.Data.Migration.Schema.SchemaBuilder.Run(ISchemaBuilderCommand command) en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Data\Migration\Schema\SchemaBuilder.cs:línea 84
   en Orchard.Data.Migration.Schema.SchemaBuilder.AlterTable(String name, Action`1 table) en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Data\Migration\Schema\SchemaBuilder.cs:línea 57
   en Orchard.Tasks.Locking.Services.DistributedLockSchemaBuilder.CreateSchema() en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Tasks\Locking\Services\DistributedLockSchemaBuilder.cs:línea 32
   en Orchard.Tasks.Locking.Services.DistributedLockSchemaBuilder.EnsureSchema() en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Tasks\Locking\Services\DistributedLockSchemaBuilder.cs:línea 20
   en Orchard.Data.Migration.AutomaticDataMigrations.EnsureDistributedLockSchemaExists() en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Data\Migration\AutomaticDataMigrations.cs:línea 87
   en Orchard.Data.Migration.AutomaticDataMigrations.Activated() en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Data\Migration\AutomaticDataMigrations.cs:línea 45
   en Orchard.Events.DelegateHelper.<>c__DisplayClass13_0`1.<BuildAction>b__0(Object target, Object[] p) en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Events\DelegateHelper.cs:línea 110
   en Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Events\DefaultOrchardEventBus.cs:línea 84
   en Orchard.Events.DefaultOrchardEventBus.TryInvoke(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Events\DefaultOrchardEventBus.cs:línea 70
   en Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) en D:\PROYECTOS\B2BB2C\Orchard Multitenant\src\Orchard\Events\DefaultOrchardEventBus.cs:línea 53
ClientConnectionId:ffa48308-102a-4137-a976-835f135fde37
Error Number:3964,State:1,Class:16
`

**Comment by carlwoodhouse** [comment]
IN regards to task lease and if it works with snapshot isolation or not its worth noting sql azure has READ_COMMITTED_SNAPSHOT set to ON as default (and you can't turn it off ..)

**Comment by jersiovic** [comment]
Then has someone using Azure suffered this exception on migrations or múltiple background services running same task concurrently?

**Comment by carlwoodhouse** [comment]
we haven't that i'm aware of and have been using sql azure with orchard for 3 years ish

**Comment by jersiovic** [comment]
It is courious. The exception I shared happened executing Orchard 1.9 to 1.10 migrations, so not suspicious custom code made by me.  The only modification I did to those migrations is the loop I describe in the following post for removing duplicated records in some tables https://github.com/OrchardCMS/Orchard/issues/6464
The solution to that was:
First to change READ_COMMITTED_SNAPSHOT to OFF. Second to modify Orchard Transaction Manager for using SNAPSHOT isolation level by default (for performance reasons). And finally to use READ COMMITTED isolation level in the session used for migrations. Then it worked like a charm.
On following weeks I will move to Azure so I will check the same there.
