### ISSUE TITLE
NullReferenceException being thrown by IndexingBackgroundTask, when using DynamicForms

### ISSUE THREAD

**Issue by jvr84** [OrchardCMS/Orchard#5306]
NullReferenceException is being thrown because HttpContext.Current is null in background index task.

Enabled modules:

Dynamic forms
Lucene
Indexing
Search

In the content item that is being indexed. the dynamic layout contains a Form element and a input element like hidden field or input field.

A first chance exception of type 'System.NullReferenceException' occurred in Orchard.Layouts.dll

Additional information: Object reference not set to an instance of an object.

In CurrentControllerAccessor.cs in Orchard Layouts, which is being called by FormElementDriver.cs in the ondisplaying method

The exception is being catched by the indexing task, but when you have set up throw exceptions the exception will be thrown.

**Comment by Piedone** [comment]
This is in contrast with #4607.

**Comment by sfmskywalker** [comment]
I recently added a change that injects HttpContextBase directly which fixes the issue, but I agree with Piedone that we should somehow make IHttpContextAccessor return the fake HttpContext in background tasks because it seems inconsistent that it would return null in background tasks while at the same time injecting HttpContextBase directly returns the fake instance. Unless there is a special reason for this I think we should make sure IHttpContextAccessor should return an HttpContextBase derivative.

**Comment by sfmskywalker** [comment]
After digging in some more, it seems that code using ```IHttpContextAccessor.Current()``` actually expects to get the ```HttpContext.Current``` object, and ```null``` if that object is null. So I am reluctant to change that behavior / expectation.

In hindsight, why do we think it's bad practice to inject ```HttpContextBase``` instead of an interface? It seems to me that the very reason for the existence of ```HttpContextBase``` I to be able to substitute different implementations of it, like interfaces. The only difference is that it is an abstract class instead of an interface, but in principle it's the same pattern.

Thoughts?

**Comment by sfmskywalker** [comment]
Please review my changes here: https://github.com/OrchardCMS/Orchard/commit/ef2abe14cbb35b3f42c8a1b6f9c606b1c299071d

Note that I did not change any behavior of the ```IHttpContextAccessor``` - all I did in principle is initializing ```HttpContext.Current``` with an actual instance during background sweeps so that Html Helpers won't fail when Razor views are being rendered in the background.

**Comment by sfmskywalker** [comment]
Fixed in #53e58f60fe2f588e76fcad3e26442eded8cc60f3
