### ISSUE TITLE
Logging during Setup

### ISSUE THREAD

**Issue by gcsuk** [OrchardCMS/Orchard#5340]
I need to have a log of any error that occurs during recipe setup. At present, the Logger property is set (by default) to an instance of NullLogger.

When running a recipe from the Recipes tab of a tenant already set up, Logger is an instance of CastleLogger. The same applies to the Import/Export area. It is only when setting up a tenant for the first time that it uses the default.

I have tried adding this to the SetupMode class in Orchard.Setup module, but although the line is hit the Logger is still null.

builder.RegisterType&lt;CastleLoggerFactory&gt;().As&lt;ILoggerFactory&gt;().InstancePerLifetimeScope()

Is it intentional that CastleLogger is not instantiated during initial setup?

**Comment by PaulDevenney** [comment]
+1

**Comment by sebastienros** [comment]
It might be the case if the logger is not resolved in the class you see it to be null, or this class is not resolved itself.

**Comment by gcsuk** [comment]
When setting up Orchard from scratch, Logger in RecipeParser (Orchard.Recipes) is an instance of NullLogger. It should be CastleLogger, otherwise if an errors occur nothing will be logged.

Adding a DI registration as shown above to SetupMode in Orchard.Setup, although executed, does not work.

I am unsure where I need to resolve Logger

**Comment by sfmskywalker** [comment]
Is the Logger property in question publicly settable?

**Comment by gcsuk** [comment]
Yes

**Comment by sebastienros** [comment]
@Piedone will do it tomorrow

**Comment by Piedone** [comment]
Hit for @gcsuk : the Logger (just as the Localizer) needs some special ceremony because it is property-injected. This is set up by `LoggingModule`, so my guess is that it doesn't run during setup, but you have to register it as an Autofac module in `SetupModule`.

**Comment by DanielStolt** [comment]
Did some digging into this today - here are my findings so far.

Firstly, this only happens in setup mode.

Secondly, the only components affected by this are `IRecipeHarvester` and `IRecipeParser`, because these two are the ones instantiated and used when the setup page is loaded (GET) i.e. before `SetupService` does its thing. The sequence is:

1. `OrchardStarter.CreateHostContainer()` executes and `LoggingModule` property-injects `ILogger` on any dependencies. At this point `Orchard.Recipes.dll` isn't even in the AppDomain yet, it doesn't get registered for property injection of `ILogger`.
2. `DefaultOrchardHost.Initialize()` executes - this is when `Orchard.Recipes.dll` gets loaded into the AppDomain.
3. `RecipeParser` is instantiated and `RecipeParser.ParseRecipe()` gets called, but since `RecipeParser` wasn't even loaded at step 1 above, it won't have a property-injected `ILogger`.

The rest of the recipe-related components are unaffected, because when setup executes (POST of the setup page) `ShellContainerFactory.CreateContainer()` is executed and it triggers another execution of `LoggingModule`, and at this point all recipe-related components get registered for property injection of `ILogger`.

From that point on, all the recipe-related components such as `IRecipeManager`, `IRecipeScheduler`, `IRecipeStepExecutor`, `IRecipeStepQueue` and `IRecipeHandler` are eventually resolved and used, and they all get `ILogger` instances property-injected.

So, I would argue that this is not a big deal, because the two affected components `IRecipeHarvester` and `IRecipeParser` don't really do much. Any problems you are having with recipes are about the **execution** of the recipes, not the harvesting or parsing (btw parsing in this context sounds like more than it is - it really only extracts the recipe metadata).

**Comment by gcsuk** [comment]
I agree, let's leave it and focus on improving ILogger.
