### ISSUE TITLE
Add Heading element

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5362]
In addition to the *Paragraph* element, it would be good to also have a *Heading* element.
The user can then change the "weight" using a quicktool button (H1, H2, H3, H4, H5, H6).
The toolbar would show the varios heading styles, but when dropping any of them, a Heading element is created (with its "weight" property preconfigured). This works exactly the same way as the various Row toolbar elements.

**Comment by thekaveman** [comment]
:+1:

**Comment by bleroy** [comment]
Fixed by c1359f7. I did not do the quicktools buttons: a single heading button takes less real estate in the toolbox, and isn't making things significantly harder for the user. Rows and columns was different as lots of parameters would have to be changed to obtain the same effect. Here, it would just rule the heading level.
