### ISSUE TITLE
INavigationFilters are not run through INavigationProvider-provided menus

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#5377]
`NavigationManager.BuildMenu(string menuName)` doesn't run the menu items through filters as `NavigationManager.BuildMenu(IContent menu)` does. Is this intentional?

**Comment by pszmyd** [comment]
Also the former does not use the `Arrange` method to build hierarchy.

I guess the reason is the `NavigationManager.BuildMenu(string menuName)` is used solely for the purpose of building an admin menu and it differs quite a lot from a "normal" menu.
Ideally we should have one logic for building any kind of menu, imho.

**Comment by Piedone** [comment]
Yes, I think that too. E.g. content-backed menu would be just another INavigationProvider.

**Comment by pszmyd** [comment]
Exactly.

**Comment by barthamark** [comment]
I also had this issue when I was trying to filter admin menus. Unfortunately, I couldn't do it because the BuildMenu(string menuName) doesn't call the Filter() method. Here is a solution for this and for Zoltán's and Piotr's idea as well.

We could make IMenuProvider and its default implementation to Obsolete and bring the IContent parameter from the GetMenu() method to the INavigationProvider.GetNavigation() method but it could be optional (with default null).
Create the DefaultMenuNavigationProvider (or sg named like that) based on the DefaultMenuProvider and we can keep the algorithm (maybe the menuName parameter can expected to be an empty string or "content" or "menu" I don't know).

In the NavigationManager we can merge the two methods and make the IContent menu parameter optional too. And of course don't forget to Filter() the menu items.

What's your opinion? @sebastienros ?

**Comment by sebastienros** [comment]
Let's try to add Arrange and Filter to BuildMenu.
