### ISSUE TITLE
Add Glimpse support to Orchard out of the box

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/Orchard#5419]
Following on from the Tuesday night demonstration of the Glimpse plugin that I wrote for Orchard, it was suggested that the functionality should be pulled into the out of the box download of Orchard.

Glimpse out of the box can give us information about filter and controller execution, and I have extended this to provide information about layers, widgets, the Content Manager and other Orchard specific features.

As this would be a major new feature, I'd like to suggest we kick off a conversation about the intended feature set, as well as talk about some potential design decisions.

For example:
- Do we build this functionality into the default implementation of services? Or do we decorate existing services?
- Do we create a generic interface for timing and performance monitoring? Or do we tie into Glimpse?
- Do we allow third party module developers to plug into Glimpse by consuming the Glimpse interfaces? Or do we provide an abstraction?
- What would be the required feature set for the first iteration?
- Do we move shape tracing into Glimpse?
- Is the Glimpse license compatible with Orchard's?

**Comment by DanielStolt** [comment]
This would be an awesome addition, so glad you're getting the conversation started.

I think this should definitely be implemented using decorators wherever possible, as we need to be able to enable and disable this feature - it should not be baked into any existing services.

I personally do not believe in creating an abstraction over Glimpse. I think it would be very difficult to design an abstraction that would both allow us to harness all the power of Glimpse **and** be generic enough to substitute Glimpse for something else. Difficult to achieve and for very little benefit IMHO. I would rather just clearly define this feature as a "Glimpse" feature, rather than some generic abstract timing and performance monitoring feature.

As for feature set... what have you got? :)

Sounds interesting to move shape tracing into it - do you think that would be feasible? Don't know much about Glimpse, but during your demo it seemed to be that it was more geared towards timing and performance, than DOM inspection and visualization of the rendered result?

Glimpse is Apache 2.0 licensed it seems - I don't know enough to tell whether it's permissive enough for Orchard's license to mirror it.

**Comment by sebastienros** [comment]
License is fine.
Yes, deprecate Shape Tracing in favor of a Glimpse plugin.
Don't hide Glimpse.

Very useful plugin is the SQL one, as in Mini Profiler.

I would say that the minimum level of feature to ship is to have the times taken by the methods and shapes render.

**Comment by paynecrl97** [comment]
I mainly have timings. There is also a log4net plugin that we have successfully installed.

A SQL tab would be awesome too; there is already an nHibernate plugin available. I wonder if we could use that?

Shape tracing should in theory be possible (there is an API to allow you to inject JS into the Glimpse panel), but I'd imagine it'd be a big undertaking; maybe we can bake this into the next iteration?

I'd also favour an approach of not abstracting too far away from Glimpse as I know from experience that it's close to impossible to get a good abstraction without sacrificing features.

I should be able to make a start at some point this week, so I'll keep this issue up to date with my progress.

**Comment by paynecrl97** [comment]
I've created a prototype to make creating decorators simpler.

I've created an attribute (`OrchardDecoratorAttribute`) that denotes that a class is a decorator. I then updated the `ShellContainerFactory` to:
* Register all implementations without the `OrchardDecoratorAttribute` as normal, with the addition of assigning each registered implementation a unique name. A dictionary is maintained that contains the interface name along with the unique name given to the implementation.
* Each implementation that is a decorator is then registered, and the `WithParameter` method is called on the registration. This tells autofac to use the implementation with the name assigned to it as read from the dictionary.
* The decorator then replaces the implementation that it itself decorated in the dictionary. This allows decorators to stack on top of each other.

Sample Usage:

    [OrchardDecorator]
    public class DecoratorDefault : IDecoratorTest
    {
        private readonly INotifier _notifier;
        private readonly IDecoratorTest _decoratedService;

        public DecoratorDefault(INotifier notifier, IDecoratorTest decoratedService)
        {
            _notifier = notifier;
            _decoratedService = decoratedService;
        }
    }

Notice that this class implements `IDecoratorTest` yet Orchard is still able to resolve the dependency it has on `IDecoratorTest` because this class is annotated with the `OrchardDependencyAttibute`.

You can see the diff here: https://github.com/OrchardCMS/Orchard/compare/dev...paynecrl97:feature/glimpse_decorators?diff=unified&expand=1&name=feature%2Fglimpse_decorators. This diff also includes a sample module that allows the user to toggle several features that register decorators at various priorities:

![image](https://cloud.githubusercontent.com/assets/2872984/8396327/1e3b2af2-1d99-11e5-812e-b424985dd992.png)

![image](https://cloud.githubusercontent.com/assets/2872984/8396336/503acbb6-1d99-11e5-89b3-f2ab201c9956.png)

**Comment by sebastienros** [comment]
Why are you using an attribute, we just need standard orchard features. And a custom interface to extend glimpse.

**Comment by paynecrl97** [comment]
The attribute is a method of allowing developers to create decorators without having to create an autofac module, much like `IDependency` allows a developer to write an implementation without having to create an autofac module to register it.

Because the Glimpse module should not care about the underlying implementation that it is instrumenting, I needed an easy way to register decorators without knowing the type of the service to be decorated.

For example:

    [OrchardDecorator]
    [OrchardFeature(FeatureNames.Authorizer)]
    public class GlimpseAuthorizerDecorator : IAuthorizer
    {
        private readonly IAuthorizer _decoratedService;
        private readonly IGlimpseService _glimpseService;

        public GlimpseAuthorizerDecorator(IAuthorizer decoratedService, IGlimpseService glimpseService) {
            _decoratedService = decoratedService;
            _glimpseService = glimpseService;
        }

        public bool Authorize(Permission permission) {
            return _glimpseService.PublishTimedAction(() => _decoratedService.Authorize(permission),
                (r, t) => new AuthorizerMessage {
                    Permission = permission,
                    Result = r,
                    Duration = t.Duration
                }, TimelineCategories.Authorizer, "Authorize", permission.Name).ActionResult;
        }

        // Other methods required by IAuthorizer omitted for clarity...
    }

**Comment by paynecrl97** [comment]
FYI for anyone interested- You can find the branch I am working on at https://github.com/paynecrl97/Orchard/tree/feature/glimpse.

Feel free to pull down and have a play about.

Tabs so far:

- [ ] Layers
- [x] Cache Service
- [ ] Cache Manager
- [x] Widgets
- [x] Shapes
- [x] Content Manager
- [x] Authorizer
- [ ] Routs / Alias
- [ ] Tokens
- [ ] Parts, Fields & Elements
- [x] SQL

I'm happy to take suggestions for any other tabs.

Known issues:

* Configuration is done in web.config. Would like to move to Admin Panel
* Shapes tab requires entire implementation of `IDisplayManager` (ie it is not a decorator) and the tab itself is a bit messy
* Localization - all data is currently in English. This may be a hard one to overcome.
* Data for the layers tab cannot come from a decorator
* Orchard.Web requires a reference to Orchard.Glimpse (not sure how much of a big deal this is)
* Some OOTB Glimpse tabs may not be that useful to us (eg Views)

Instructions:

1. Pull down my fork as linked above
1. Build and run
1. Enable Glimpse (via `~/Glimpse.axd`)
1. Enable the Glimpse features in the Admin Panel to see data appearing in your tabs

Looking forward to feedback on my progress so far.

**Comment by sebastienros** [comment]
Well, for the interface and the autofac module, yes we don't want users to create them, but YOU can do one that will harvest this interface automatically, in this orchard module.

**Comment by paynecrl97** [comment]
Although what you're saying is correct in the sense that I can create an Autofac module in this module to discover all my decorators and register accordingly, I think we'd be missing a trick by not making this functionality more readily available (ie outside of the Glimpse module).

I've now reverted the changes I made to Orchard.Framework and do all my decorator registrations in the Glimpse module itself (currently using the implementation from the helper class that @LombiqTechnologies provide in their Helpful Libraries toolkit, I hope this is OK). That said, I'd strongly urge a re-think  on the stance that this functionality shouldn't be made available globally in Orchard.Framework.

Registering decorators at the same point as all other registrations means that:
* This functionality can be used in any module (3rd party or not) without the need to reference the Glimpse module. This will be a powerful addition to the Orchard developer's toolbelt.
* You don't need to prevent the `ShellContainerFactory` from registering the decorators as the main implementation (I've had to do this by making the decorators `internal` so that they can't be discovered by `ShellContainerFactory`, which isn't ideal).
* Decorators can be registered using standard patterns and practises for Autofac, without having to hook into events to switch out the implementations at activation time.

One of the best features of Orchard for developers is the simplicity of DI framework- `IDependency`, `OrchardSuppressDependency` etc... and I truly believe that this attribute would fit well into this framework and be a great addition.

**Comment by Piedone** [comment]
I agree with @paynecrl97 : although implementing decorators is of course possible with an Autofac module this is something that hardcore developers would be able to leverage more if it would be baked into the Framework (this is why there is also that helper class in Helpful Libraries: it was a recurring task). I'm an advocate of being able to use and actually using Orchard as a generic application framework (http://orchardapphost.codeplex.com/) and things like this make Orchard a great framework.

I've taken a look at the implementation under https://github.com/OrchardCMS/Orchard/compare/dev...paynecrl97:feature/glimpse_decorators?diff=unified&expand=1&name=feature%2Fglimpse_decorators#diff-601e824491fb4dfa61a4ef0ce3d8cd04R115. Mostly it seems fine to me, just some remarks (can't comment on such code diffs apparently):

1. Running format is needed on the affected classes (noticed misplaced braces and some other styling issues).
2. I don't think using localized strings in `ShellContainerFactory` is a good idea: even if it seemingly works I doubt it would actually use translated strings (since this is so early that the culture settings of the shell are not yet loaded). But I haven't tried.
3. I'd add some documentation to the decorator attribute explaining what it does and how to use it.
4. I'm hesitant about having a priority value: the order of dependencies IMO should be decided by the declared feature dependency order (i.e. how injected dependencies are registered).

I'd suggest bringing up the decorator question on Thursday's meeting.

And BTW feel free to add functionality from Helpful Libraries - it's open source and we should probably also take some of its proven features into the Framework.

**Comment by paynecrl97** [comment]
1 & 3- That diff is just a prototype of how I envisage it working. Once we agree on a design then I'd format and document accordingly.

2 - I think the only reason for the Localized string is use of `OrchardFatalException`. I could easily remove this in favour of an exception that doesn't require localization.

4 - I myself am not sure of the answer to this question. On one hand, I feel like it should behave the same as injected dependencies for the sake of simplicity. But on the other hand, I can see benefit and some use cases for allowing developers to alter the order that their decorators are registered.

**Comment by paynecrl97** [comment]
As an aside @Piedone- I'm having issues using `DecoratorsModuleBase` to register multiple decorators of the same interface (ie wrapping `IContentManager` with multiple decorators). I'm seeing circular dependency chains.

Is this a known issue, or would this be expected to work?

**Comment by Piedone** [comment]
I didn't think about multiple decorators (didn't need them myself) so that looks like a missing feature.

**Comment by DanielStolt** [comment]
After looking at this implementation and taking the time to understand it, I also agree with @paynecrl97 and @Piedone that this approach would fit very nicely into the core framework. I suggest we continue the work to design it to be a natural fit.

A few thoughts:

1. I wonder if maybe the code in `ShellContainerFactory` could benefit from using Autofac's built-in support for decorators? http://autofac.readthedocs.org/en/latest/advanced/adapters-decorators.html
2. For services with big API surfaces (i.e. interfaces with many members) it would be nice to have abstract decorator base classes that the decorators can subclass, so that you can override only the members whose behavior you wish to alter in your decorator, rather than implement every member on the interface only to have to delegate to the decorated service in most of them. But I of course also realize the cunundrum - who should define such base classes? If we define them along with the decorated services, the question becomes for which services do we define them? And conversely, if it is instead left up to modules providing the decorators to define these base classes, then a lot of the benefit goes away because every module needs to define one...
3. Perhaps the explicit ordering and feature dependency ordering can complement each other, such that feature dependencies take precedence, while the explicit ordering applies among decorators without feature dependencies between them and decorators within the same feature. I too can see a value in being able to explicitly order decorators, in cases where the same module provides a number of them - having to declare a bunch of features just to order them would seem cumbersome in such a scenario.

**Comment by Piedone** [comment]
2. Good idea about base classes. I don't think we should think here too much: let's create base classes for those services that Glimpse would use first (I'd think about the services of IOrchardServices, maybe IRepository<T>). After that time will tell what else we need.

**Comment by Hazzamanic** [comment]
Is Glimpse integration in the core still on the cards?

**Comment by urbanit** [comment]
Is Glimpse integration in the core still on the cards?

**Comment by dcinzona** [comment]
Is Glimpse integration in the core still on the cards? :)

**Comment by sfmskywalker** [comment]
Most certainly, but it depends on the decorator support, which is still under investigation.

**Comment by DanielStolt** [comment]
Remind me, why is the decorator support still under investigation? It's always seemed like a solid addition to me..

**Comment by sebastienros** [comment]
Still under investigation, but the plan is for it to be part of 1.11. I just need to review the decorator to be sure nothing can be broken.
And it's so awesome that it will be part of O2 OOB.
