### ISSUE TITLE
Add Properties To Layout Element In Orchard

### ISSUE THREAD

**Issue by Skelet0r67** [OrchardCMS/Orchard#5456]
I am using the new Orchard.Layouts feature and am currently trying to add a property to the Html Element in Orchard (in the same area where you set the Html Id, Css Classes and styles. I saw that there is a class called LayoutEditorPropertiesItem in which you can pass into the Editor Template for that specific element, but doing that did not save the data, so I'm assuming there are other steps involved.

It is a property I would like to use to add alternates to the element when it is being displayed. What I would like to know is, is it easy to add a property to each individual element OR is there an easy way to add a custom shape to any of the elements?

**Comment by sfmskywalker** [comment]
Adding your own properties to the Html element would require changing core code, since elements themselves aren't extensible like content typed. However you can add shapes to any of the elements because since ultimately they are created and rendered as shapes of type Element. Depending on your requirements you could implement a shape table provider, describe the Element shape, and check for it's Element property and its type during the Displaying event. If its the Html element, add your shapes and properties to the element shape. Unfortunately this wouldn't solve the scenario where you want the user to be able to provide values to your custom properties. Perhaps you should consider writing a custom element if that's part of the requirement.

**Comment by jonvee** [comment]
Thanks, that's exactly what I did (custom elements) ;) There's a lot to play with in 1.9! 
You guys are awesome!

**Comment by Skelet0r67** [comment]
Okay, that makes sense.. When you say to make a custom element are you talking about through the blueprints or doing it all through code? I was going to look at the way the dynamic form elements are set up and use those as an example, is that a good place to start?

**Comment by sfmskywalker** [comment]
Yes, by custom elements I mean doing it through code. Absolutely, Dynamic Forms elements are a great way to start writing your own.
