### ISSUE TITLE
Import exception: "No records were found in the database for recipe execution ID"

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5532]
This happens when the imported recipe contained no steps. We should either display a message on the import screen that no actions will be performed, or display a message on the import result screen that no action was performed. But in any case, we should not show an exception to the user.

**Comment by DanielStolt** [comment]
If it's possible to know already at schedule time that the recipe contains no step, the most elegant solution I think would be for the `IRecipeService.Execute()` method to return something to indicate that nothing was scheduled (perhaps return `null` instead of an execution ID) and then to surface this information as a notification and return to the Import view.

**Comment by DanielStolt** [comment]
And looking at `RecipeManager.cs` that's definitely possible.

**Comment by sfmskywalker** [comment]
My idea exactly.

**Comment by DanielStolt** [comment]
Great minds think alike, and fools never differ. :)

**Comment by sfmskywalker** [comment]
Fixed in 42901c8ea59fbb03f085afb53101ceddd475f678
