### ISSUE TITLE
Bug: Making new transaltion of a content does not copy values from master to translated version

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#5535]
By clicking on translation link, I expected all values present in master content will be copied into new translation content, as in 1.8.1 feature.
this does not happen in 1.9.x version. Seems to be a bug...

**Comment by Skrypt** [comment]
Can you give us the steps to reproduce this. I am currently fixing the problem with Widgets, is it doing this somewhere else ?

**Comment by HermesSbicego-Laser** [comment]
Yes, here the steps:
1. Enable Content Localization
2. Add another culture to site (it-IT in my case)
3. Edit a Content ( a page for example )
4. Set a culture to it (en-US)
5. Publish content
6. click + New translation
7. No fields will be filled up with master content values (Title is empty, Body is empty, etc...)

**Comment by Skrypt** [comment]
I'm not sure we want to copy those values in that specific scenario since they will be replaced with translated content. This makes more sense with Widgets for instance; where you need to copy the Layer and Zone to the Widget you are translating. Though let's see other people opinions about this. I think other CMS's like Wordpress gives a checkbox option to copy those values or not when you are translating a content item, this could be how we could implement this.

**Comment by HermesSbicego-Laser** [comment]
In the case of a content with fields and parts that need translations, you are right.
But imagine to have a content with many fields (Numeric Fields, Enum fields, Media Library picker fields image and so on) and/or parts that don't need for a translation. You have to re-enter all values and contents. 
In Orchard 1.8.1 (and previous versions) all data were copied from master to translation. 
So, i agree for a checkbox, but the default behavior should be "copy contents from master to translation". let's see other people opinions. Thanks.

**Comment by Skrypt** [comment]
@Jetski5822

**Comment by Skrypt** [comment]
@sfmskywalker Can we copy Layouts from one content item to another easily ? @Jetski5822 has it been dropped in 1.9.1 because of the changes made in the Localization features ? Would it be a proper way to use the handler to do this then ?

**Comment by Piedone** [comment]
This feature never existed.

**Comment by Skrypt** [comment]
That's what I thought too. I don't remember that in 1.8.x it was copying the content. Though that's a good feature idea to consider implementing. I'm asking myself now if this is a specific case scenario or if it would be needed everytime we have a LocalizationPart on a content item. If it's the second then, we should maybe consider doing something more proper than what I did with the Widgets.

**Comment by HermesSbicego-Laser** [comment]
I am quite sure this feature was present:
at this history point, logic within Translate Action was changed: 
https://github.com/OrchardCMS/Orchard/commit/fa1de09a4f5688f2fb4fe9abd270e1a0106d1dde

before:
MasterContent was used as Model for buildeditor of AdminController/Translate. The effect was that the MasterContent worked as initial value for the translation... may be this could help...

**Comment by sfmskywalker** [comment]
@Skrypt Yes very easily, simply copy the LayoutData and TemplateId properties over (`string` and `int?`).

**Comment by sebastienros** [comment]
So here it's not about copying the properties, but using the master content item to modelbind the UI, which I think is he best solution. We should fix the regression.

**Comment by Skrypt** [comment]
Yes thanks @sebastienros  for the precision

**Comment by sebastienros** [comment]
I need to revert the fix as this is preventing from selecting the translation. The real solution needs more work. I think we need to leverage the Clone function then to initialize the cloned culture. But then we need to change Clone in two ways:
- not save the content item as it is done by default during a cloning
- extend the clone action with some events so that parts like Autoroute can reinitialize the value, like when the cloned content is the homepage.

**Comment by TFleury** [comment]
@sebastienros I worked on a PR to add clone handling, and also solving this translation issue. #6540
