### ISSUE TITLE
Why do we need Cache.Dat?

### ISSUE THREAD

**Issue by PaulDevenney** [OrchardCMS/Orchard#5550]
The cache.dat, as far as I am aware stores the list of features that were enabled on the local machine. I'm wondering what the point of placing this data into a cache file is. The time to regenerate the file seems very small, and only seems to occur on changing a feature or other configuration change, so performance does not appear to be an issue. Also, there are other mechanisms within orchard to cache a value that does not require this text file to exist. 

Two reasons you might not want the cache.dat file are
1. If you run the orchard command line before IIS does it is the user context of the command line tool that creates the file. Often this means that IIS no longer has permissions to cache.dat
2. When doing "pseudo remote" debugging (same code base on local machine as some other environment and point at it's databases) you have to be careful to clear your local cache.dat or you actually do NOT have the same features enabled, which seems counter-intuitive

**Comment by sebastienros** [comment]
THE reason is to make the startup of the website faster, so that we don't need to load the state from the database to know which features need to be enabled.

If you show that a site with a 100 features starts as fast with or without the file, then we can think about removing it.

Also, could you state what the issue with this file is? There is a documented option to ignore it.

**Comment by PaulDevenney** [comment]
We disabled the option. That option did not exist in the past, so it was a pleasant surprise! The additional start-up time seems negligible though and we do indeed have 100s of features (216 on one site).

**Comment by bleroy** [comment]
What about large multi-tenancy setups? Does it make a difference?
