### ISSUE TITLE
Be able to select whether Templates are rendered on the frontend, admin or both

### ISSUE THREAD

**Issue by mehranrezaei** [OrchardCMS/Orchard#5579]
Currently when i publish a template, it will be rendered in both of Admin and Front theme.
I think it's better Templates in Orchard.Templates will only be rendered on front-end.
For example i created "Menu" template to change menu of front theme. But it destroyed Admin menu. (Also about Layout template, ....)
One better option can be a check box that user can limit target of rendering!
Currently i cannot use this great feature (Orchard.Templates) because it will destroy Admin UI.

**Comment by urbanit** [comment]
cc:/ @bleroy

**Comment by Piedone** [comment]
I disagree with generally disabling it for the admin (this would remove a big, actually useful feature) but being able to select (per template) whether you want to have it active for the admin is a good idea IMO.

**Comment by armanforghani** [comment]
@Piedone, Yes, You are correct. As Mehran mentioned above, the best option is ability to select per template. 
Also one very important lack in Orchard.Templates is permission management. I think it needs at least two extracted permissions for writing front and admin templates.

**Comment by bleroy** [comment]
I've been summoned, but unfortunately, I don't even understand the issue. Sorry.

**Comment by armanforghani** [comment]
This is the list of important issues:
1. All users of Back-end can access Orchard.Templates. Why the author should have access?
2. There is no control on target of rendering for a template. For example if you create a template with the name Menu or Layout, ..., It will be rendered in both Admin and Front theme.

**Comment by armanforghani** [comment]
/cc @Piedone
I sent a PR for issue #4951. As you know this issue is related to that. 
I want to send a new commit to the current PR to fix this issue.
I am looking for the correct point to check context using ```AdminFilter.IsApplied``` and search for available templates in front or back ends based on new ```RenderingMode``` property.
Do you have any recommendations?

Please be aware that i defined an enum and added new property to ShapePart as bellow:
```
    public enum RenderingMode {
        FrontEnd,
        Admin,
        Unspecified
    }
```

```
    public RenderingMode RenderingMode {
        get { return _renderingMode.Value; }
        set { _renderingMode.Value = value; }
    }
```
I found ```TemplateShapeBindingResolver``` and its private ```BuildShapeProcessors``` method.
I think i can inject ```WorkContextAccessor``` and check ```RenderingMode``` for any templates. Do you agree?

But there is another important issue. Template name must be unique. But suppose we want to create one template for overriding ```Menu``` shape in front end and another one to override ```Menu``` shape in admin.
Both templates should have the same name to match shape type.

**Comment by Piedone** [comment]
@armanforghani somehow I missed these messages of yours here... Do you have any code you want to be reviewed for this issue?

**Comment by armanforghani** [comment]
@Piedone Unfortunately, I didn't find enough time to work on this issue. Sorry. I hope you find.
But if you have time to spend on this issue please notice to the naming issue as i mentioned above.

> Template name must be unique. But suppose we want to create one template for overriding Menu shape in front end and another one to override Menu shape in admin.
Both templates should have the same name to match shape type.

**Comment by Piedone** [comment]
Yes, thank you.
