### ISSUE TITLE
Assets.json should be created by codegen module

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#5606]
With a skeleton and examples of what can be used: bundles and star matching

**Comment by dcinzona** [comment]
If Assets.json is created every time the codegen module is used, there may end up being a lot of empty assets.json files there that are being watched for no reason.
I added some helper comments to the gulpfile.js and can optionally write that help out to the console when the developer starts the "watch" task.  That way it can be documented somewhere more obvious and visible.
Thoughts?
Here is the PR referenced above: https://github.com/OrchardCMS/Orchard/pull/5613

**Comment by DanielStolt** [comment]
@dcinzona That's not how it works - if an `Assets.json` file does not contain an asset group, or if an asset group doesn't actually declare any input assets, nothing will get watched.

Furthermore I don't think comments in `Gulpfile.js` is the best place. Would prefer to describe it in documentation, add a tersely commented sample to codegen, and *maybe* also add a `GulpReadme.txt` file or similar to the `Gulp` solution folder.

**Comment by DanielStolt** [comment]
Had to settle for a minimal version of this because you can't put comments in a .json file, which makes it practically impossible to provide any illustrative examples without actually implementing them fully and put all the corresponding assets and outputs in the generated module, which obviously we don't want to do. We'll have to refer to documentation (which really should be the go-to place anyway).
