### ISSUE TITLE
Taxonomy term malfuntioning autoroute pattern and bad term ordering

### ISSUE THREAD

**Issue by Xeevis** [OrchardCMS/Orchard#5631]
**_Tested on dev branch.**_
## Default autoroute pattern not followed by terms
1. Create new Taxonomy `Tax`
2. Add new term to it `Test 1` 
   - You can notice that this term will generate with incorrect permalink `test-1` it should be according to default autoroute pattern `tax/test-1`
3. This can be fixed by going to `Tax Term` content definition and just hit save without changing anything
4. Now any new terms will follow pattern correctly.
## Terms don't order properly
1. Create another term `Test 2`
2. Create another term that is child of `Test 1` and name it `Test 3`
   - `Test 3` will appear on the bottom as a child of `Test 2`, but it's child of `Test 1`. All new terms are ordered to the end of the list instead of being placed under their parents.

**Comment by thekaveman** [comment]
I've can confirm there is an issue with taxonomy and autoroute. 

My specific use case is trying to generate an autoroute from the value of a taxonomy field:

 - I have a part `MyPart` with a taxonomy field `TaxField`, this part is attached to the page type
 - Autoroute pattern is defined as `{Content.Fields.MyPart.TaxField.Terms:0}/{Content.Slug}` 
 - Assume a page titled *Test Page* with a term named *term-1* selected


I would expect the autoroute to be `term-1/test-page` but it is in fact just `test-page`. Debugging, it seems that at the time the autoroute is generated, `TaxField.Terms` is null. 

This could be related to #3762 and/or #4043

**Comment by bleroy** [comment]
I'm not sure that this scenario should work at all. It seems to be fraught with problems: what if you change the terms associated with an item after it's been created for example? I know we have the same kind of problem with other sources of Autoroute tokens, but to a much lesser extent. In general, the URL of a resource should be built on invariants or quasi-invariants of this item, such as its creation date or container. Taxonomies are not invariants, and I would steer clear of them for URL generation.

**Comment by thekaveman** [comment]
I agree that it may not be the best or most stable approach. The concerns you raise are in the domain of the *content managers* (e.g. don't setup your autoroutes using taxonomy then go changing your terms), not the *content management system*, right?

This issue is about OOTB functionality. This and the 3 related issues that I linked show, whether or not it's the right thing to do, users are trying because the pieces are there.

**Comment by bleroy** [comment]
Not exactly. How do you propose this could work at all? Should we special-case taxonomies, detect that there is a token in the autoroute pattern that uses a taxonomy's first term, then check that the field has been marked mandatory, and error if it wasn't? What if it's the first and second term that are used in the pattern? Should we then error if there is only one term entered? I'm sure you can see how that doesn't scale and is nearly impossible to implement in a foolproof way. The fact that we tried and failed to fix it several times before doesn't exactly plead in favor of trying again.
The only way out of this that I can see is to raise an error if any token in the pattern gets evaluated to null or empty string, but that would be a seriously breaking change.
Am I missing something?

**Comment by thekaveman** [comment]
I fear that I am missing something (more likely). I'll forge ahead anyway...

This issue (as originally reported by @Xeevis) is about standard Taxonomy autoroute generation. Using the default autoroute pattern that comes OOTB, the expectation is that a term's permalink includes its taxonomy hierarchy. This actually requires a secondary save on the term definition - something is not working as expected here, right?

I mention my scenario because I've been looking at taxonomy+autoroute all day and came across this issue, which *seems* related. I think using a token like `{Content.Fields.MyPart.TaxField.Terms:0}` (autogenerated by Orchard and shown to me in the token selector) should already be supported based on the code in ` Orchard.Taxonomies.Tokens.TaxonomyTokens.Evaluate`.

I can debug more to confirm or deny this, but what *I think* I saw was that at the time the token is being evaluated (for autoroute generation, in my case) the field that contains the data for the token is not "ready" yet. This is the reason why I think my issue is related to @Xeevis's issue - autoroute generation using taxonomy-related data doesn't have the taxonomy-related data that it needs.

**Comment by bleroy** [comment]
No, you're probably right on that. But even if we fix that one problem (again), the whole scenario is flawed in a hundred other little ways, and we may be in need of a more generically better way to fail when we can't find any right way to succeed. If that makes sense.
