### ISSUE TITLE
The Orchard.DesignerTools does'n work

### ISSUE THREAD

**Issue by neTp9c** [OrchardCMS/Orchard#5647]
WorkContext is always null, because one getting in constructor.

https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.DesignerTools/Services/ShapeTracingFactory.cs

if change class variable from WorkContext to IWorkContextAccessor all works fine.

**Comment by Piedone** [comment]
Yes, the WC should be resolves from the WCA as late as possible. Just wondering, when exactly does this cause an error for you?

**Comment by neTp9c** [comment]
I don't know. But it occurs for a standard orchard installation.

Clone repository (then use dev branch).
Enable Shape Tracing.
You get this error: "Object reference not set to an instance of an object.".

**Comment by jtkech** [comment]
@Piedone, @sebastienros, @neTp9c,

For infos, just found that this occurs after this commit: https://github.com/OrchardCMS/Orchard/commit/83cae5f0a0d6a3000be2e52e2fcf8e80966005b4 (just before it works) where `FormsAuthenticationService` uses an `IMembershipService` in place of an `IContentManager`.

Maybe because the work context scope is created later with this new dependency injection. This because the `FormsAuthenticationService.GetAuthenticatedUser()` method is used in one of the `IWorkContextStateProvider` that are resolved in the `WorkContextImplementation` constructor...

Not sure but if I use a `Lazy<IMembershipService>` it works, in this case the `ShapeTracingFactory _workContext` is correctly initialized in the constructor, a work context object has already been set in the `httpContext.Items[_workContextKey]`, as done in `CreateWorkContextScope()`...

All of this to say from when this happens and try to understand why. But maybe we need at least to do what @neTp9c is suggesting. Using `_workContextAccessor.GetContext()` later in `ShapeTracingFactory` also solves the issue. Using a `Lazy<WorkContext>` or `Work<WorkContext>` also works...

Notice that there are many other places where a work context is intialized in a class constructor. Some times by injecting directly a `WorkContext` but without using `Lazy<> or Work<>`, other times by using a `wca.GetContext()` but in the constructor...

Best

**Comment by sebastienros** [comment]
Works fine on 1.9.x so I will assume that's a dev branch issue as it is mentioned. Right now I can't make the dev branch to work for me but that's another problem.
