### ISSUE TITLE
Ability to add widget to Layout

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#5662]
How we can insert a widget in layout editor?

**Comment by Piedone** [comment]
This is not supported right now. As a workaround you can set the specific widget content type Listable, then you can add those widget items to a Layout with the Content Item Element. Proper support for this would need a similar Element but just for widgets I presume. @sfmskywalker ?

**Comment by sfmskywalker** [comment]
We had support for this at some point during the development phase but decided it should not be part of the core feature, as it would mix up the two worlds. When doing custom development, implement your things as an Element first so you can use it both on a layout as well as a widget.
If you do want to display widgets on a layout, either use the Content Item Element as @Piedone suggests, implement a custom Widget Element that allows you to select which existing widget to render, or even implement a custom element harvester that allows you to drag & drop new widgets onto a layout.

**Comment by Piedone** [comment]
@sfmskywalker even if building Elements first is the advised approach now this helps little if you have already developed hundreds of widgets and don't want to re-write all of them. The Content Item Element is really just a workaround. Why wouldn't we want to include an Element for widget support? This would allow you to utilize Layouts even if you have a bunch of widgets.

Not to mention even in the future it's a valid use-case to re-use pieces of content or already configured functionality across Layouts (and maybe on further pages with Layers), i.e. to re-use the same widget content item.

**Comment by sfmskywalker** [comment]
The reason we wouldn't want to support adding widgets to layouts from a core module is because the Widgets world is a much different one from the Layouts world. Mixing Widgets into Layouts would be more of a work around rather than a well-designed solution, making it a scenario we should not endorse I think. The very fact that a `WidgetPart`, the thing that defines a widget, has a `Layer` and `Zone` property, punctuates that opinion, since both properties are useless in a layout. Not to mention that a widget with a NULL layer will cause an exception (somewhere, can't recall the exact scenario).

That being said, I do see the usefulness of reusing existing widgets, so maybe it should be done as a gallery module. But I don't think it should be part of the core distribution because it seems to be more of a hack than a proper fit.

Here's a thought: given a sample widget type called `MyBannerWidget` which consists of:
- MyBannerPart
- WidgetPart

What if we created a new type called `MyBannerElement` which consists of:
- MyBannerPart

and maybe change its `Stereotype` to *Element*. Now we could have a harvester that yields available elements based on the *Element* stereotype. If necessary, we would invent an `ElementPart` as well to store additional data, but perhaps we could do without.

This way we could have an optimized solution and still use existing customized code.
What do you think?

**Comment by bleroy** [comment]
I disagree: I think it's natural that people would want to put widgets in layouts, because the semantics are virtually indistinguishable from the user's standpoint. I think your solution has value, but we could also do something simpler that addresses the problem better from the user's perspective.
First, the lack of layer is easily solved by adding the default layer to those widgets dynamically, when rendering the layout. The zone can be the parent container element that the widget is in (zones are just shapes, after all). This way, as far as the widget knows, it is in a legit layer and zone. All we have to do is add an optional feature that does those things, and dynamically creates elements out of the available widgets in the system.
FWIW, I think we have a concept overload in Orchard, and this is one more example: shape, widget, element, the difference is subtle at best, and often unnecessary.

**Comment by Piedone** [comment]
It is true that if you have a widget just for the sake of adding it to a Layout it will be kind of hackish: you need to put the widget into a Layer that will never be active and the zone won't matter. The glue between these two features could be more explicit (e.g. a built-in Layer and zone, both just to put Layout-only widgets into), though indeed it would remain an adapter, a bridge. Regardless of any legacy code, however, I still see the valid use-case of using the same widget item traditionally and in Layouts at the same time.

We have a lot of existing code corresponding to widget-attached content parts that we need to be able to re-use in Layouts. Now if those are not coupled with the widget ecosystem (e.g. relying on WidgetPart), which should be the case most of the time, we could use the solution of creating a separate content type with the Element stereotype - though this is elegant I fail to see the advantage compared to just having a standard content type and its items and using Content Item Element. The important semantic difference between Creatable content types and widgets types is that the latter represent self-contained pieces of content or functionality that can be put anywhere on the website. I'd keep this difference.

**Comment by bleroy** [comment]
Also take into account the developer scenario: let's say that I want to build a simple goeloc/mapping module. It just has a longitude and latitude, and shows that on a map. It's hard to get simpler than that in concept. Let's see what I have to build (I'm not even mentioning the mess of drivers that I'll have to build for each of those):

* Part
* Field
* Element
* Widget

There is so much overlap between those, it's not even funny. I know I'm drifting off-topic here, but we should probably think about how we can be a lot DRYer here, and build all of those things from as much common code as possible. Enabling widgets as elements may be part of this.

**Comment by sfmskywalker** [comment]
@bleroy I didn't mean to say that the `WidgetPart` properties aren't solvable (because I had already done it and it worked perfectly fine), but it was more to make my point that widgets simply belong to a different world. But looking at it the way you do, where a Layer could just as well represent the container (being a widget layer or a layout) and the Zone could just as well be a widget zone name or a container element, plus that both features are meant to help the user to place things, plus @Piedone 's scenario where you do have a number of widgets that would make sense on a layout, I am kind of leaning towards making widgets work with layouts again.

However I'd like to hear @sebastienros 's take on this as well.
If I'm being completely honest, I do get excited just thinking about implementing this.

**Comment by sfmskywalker** [comment]
@bleroy regarding the overlap, we already solved for that. If you want to create a new thing, all you need to implement is a GeoLoc element and its driver. You don't need to write anything to turn that into a widget.

**Comment by bleroy** [comment]
Yes, you're right. There is other overlap, too, in parts vs. fields vs. element that we should probably discuss face to face in October, from an Orchard 2.0 perspective. Cheers.

**Comment by sfmskywalker** [comment]
To elaborate on my latest comment, you would do the following:

1. Create a `GeoLoc` class that derives from `Element`.
2. Create a `GeoLocDriver` class that dervives from `ElementDriver<T>`

To reuse this element as a widget, define a new content type called `GeolocWidget` and attach the `ElementWrapperPart` and configure it with the element name.

**Comment by sfmskywalker** [comment]
Looking forward to discussing that for 2.0 very much. :)

**Comment by bleroy** [comment]
So if I understand you correctly, parts and fields are dead? In 2.0 that may well be the case, but it may be a little early for this. In particular, how will that work with projections? This is definitely off-topic though ;) Let's keep some points to discuss in October.

**Comment by sfmskywalker** [comment]
Good god no, such widgets still require the widget part and other parts. I would not touch the design of parts and fields at all. Maybe unify them as you did with DecentCMS in Orchard 2.0. But yes, let's leave this open for Alicante. :)

**Comment by sebastienros** [comment]
I think that's ok to support Widgets in the layout editor, that would help some users. 
Questions:
1. Should we be able to add an existing widget to a layout? This would be the sane behavior as the Content Item element, but would also show the widgets.
2. We need to be able to create new Widgets, so the element editor needs to allow that, with full postback support, and hide the layer selection. Or the user would use the Hidden layer, and any Zone.

This seems to be pretty simple to support.

**Comment by bleroy** [comment]
I was more thinking about scenario no. 2: creating a completely new element that happens to be a widget. For no.1, one thing I suggested before is to make it possible for a container to be "promoted" to become a zone. Essentially, give a container a zone name, and widgets can target it. This has the advantage that layouts can replace almost everything that used to require new layout templates in the theme.

**Comment by sfmskywalker** [comment]
You mean something like this? https://www.youtube.com/watch?v=DWY1n369l4Q&feature=youtu.be&t=47m46s

**Comment by bleroy** [comment]
Exactly like that. What happened to it?

**Comment by jersiovic** [comment]
A chain of questions I have: Can we do something with Zones & Widgets that we cannot do with layouts? Is it something we cannot  implement for elements? What sense has to maintain Zones & Widgets in Orchard in the future? Won't be better to remove Zones  & Widgets and left Elements with the Rule Element Sébastien mentioned in the video? At this point, why extend the backward compatibility with Widgets for ending removing them on next version or even worst making them coexist for ever making the system complex for the user?

**Comment by sfmskywalker** [comment]
@bleroy I believe the word mentioned was "confusing" and that the primary goal was the ability to use layer rules, for which we wouldn't need to use widgets and the layer rule system since we can now assign rules to individual elements on any level in the hierarchy. That, and the recommendation of going element-first (meaning new widgets should be implemented as elements, since they can serve as widgets just as fine since they can exist standalone), it was decided we wouldn't need the dynamic zone stuff.

@jersiovic I can think of two limitations with Layouts and Elements that are currently solved by Widgets:

1. Imagine a Layouts only world without the Widgets and Layers. Where would you put the Menu element for example? Typically we want to display the main menu on all pages, including pages that are not content items, such as the Login screen, which is served by a controller. The current system of widgets assigned to zones and layers works perfectly in this scenario. Layout pages on the other hand are content items, which are only rendered when requested.
2. Widgets are content items and as such are composable (you can attach parts and fields). Elements are atomic and cannot be extended with additional things (although you can extend elements programmatically by means of its Data dictionary and implementing additional drivers to handle this data and additional UI).

That being said, here are some thoughts on how we could unify the two worlds:

To solve for bullet 1, we would need some sort of UI similar to the Widgets screen where you as a user can add elements to a global zone. This UI could be based on a Layout that represents the site's layout design (currently represented by a ThemePreview.png) so that adding elements to zones is more intuitive than adding widgets to a stacked list of zones. Adding the Zone property back to the Elements (as was done in the video I linked to in my latest comment on this thread) would make this possible.

Regarding bullet 2, as mentioned, widgets are content items which have the benefit of being composable. Elements on the other hand, not so much. So what if we simply keep the concept of a Widget around and provide an element provider (called an element harvester) that enumerates elements in the toolbox based on content type definitions whose steretype is "Widget"? Now you would have composable elements.

Conceptually the Widget type would just be an extension to the Layouts engine so that users can place content items onto a layout (and those content items would not clutter the Content list screen), regardless of the layout being associated with a content item, or a "global" layout where it's just a means to associate elements to zones.

**Comment by sfmskywalker** [comment]
The following shows a way to add widgets to a layout:

![2015-08-23_11-13-01](https://cloud.githubusercontent.com/assets/938393/9427830/1cddbfb0-4988-11e5-8184-03780b15c4f6.png)

This creates widgets on the fly. A few things to handle would be:

1. What layer and zone to use? As @sebastienros mentioned, we could just use the "Disabled" layer and assign that automatically. However, the user could have removed this layer. Should the system auto-generate that layer if it went missing? Or should we tweak the `WidgetPart` such that Layer can be any content item (e.g. the layout content item itself such as Page), or even be `null` (in scenarios where a layout is not associated with a content item at all)? Regarding the `Zone` property, this could be any random string (but ideally would be the same as the `Zone` property on a container element if we would add that back).
2. If we chose to auto-assign the "Disabled" layer and an existing zone, the Widgets screen will be cluttered with widgets created as part of layouts, which would be a mess. To solve for that. I think we should allow the `Layer` property to be something else than a `LayerPart` instance. The Widgets screen would simply only list widgets whose `Layer` property reference objects of type `LayerPart` (or aren't `null`).

**Comment by sfmskywalker** [comment]
And:

3. Whenever a user deletes a widget element, the widget content item should be deleted as well.

**Comment by jersiovic** [comment]
@Sipke  Regarding bullet 1 an bullet 2 I totally agree I like both solutions. To have Template Layouts for concrete content items and a Global Layout ( or a number of those with one marked as the default) replacing the body of layout.cshtml for generic structure of the sit is something easy to understand for the user. Because both kinds of layouts are similar concepts for the user.

Related to "What layer and zone to use?" I like the idea of making the Layer of a WidgetPart can be any content item or null. Because it allows to coexist both ways of working with Orchard: Widgets Screen and Global Layouts screen. Delaying for a next version the moment of removing Widgets Screen.

**Comment by sfmskywalker** [comment]
Created a PR here: #6030
