### ISSUE TITLE
DateTime unit tests make my laptop very hot

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#5702]
For the sake of my laps, please make these tests more energy efficient ;)

**Comment by bleroy** [comment]
+1

**Comment by DanielStolt** [comment]
I can do that - they'll just take a lot longer to run. Is that OK? :)

**Comment by Piedone** [comment]
@sebastienros please discuss with your wife how you're attracted to your laptop now.

**Comment by sebastienros** [comment]
The issue is actually that it's really slow to pass, it's doing too many tests. Maybe we should make them optional. The solution is to create another test project for optional/slow unit tests that would run on the CI like the Specflow tests.

**Comment by sfmskywalker** [comment]
Or maybe these tests can be moved to a separate project so that they won’t have to be executed each time?

**Comment by MpDzik** [comment]
Maybe we can use NUnit's [CategoryAttribute](http://www.nunit.org/index.php?p=category&r=2.2) to mark long-running tests (ex. performance tests). That way the long-running tests can be easily filtered out in unit test runners in dev environments, but have them all run in CI builds.

**Comment by sfmskywalker** [comment]
That sounds like a great idea.

**Comment by DanielStolt** [comment]
@MpDzik Does the VS2015 test runner recognize that attribute and allow filtering on it?

**Comment by MpDzik** [comment]
@DanielStolt I'm not sure, as I use the test runner from ReSharper. I don't have VS 2015 installed on the machine I'm currently working on. I'll check this out as soon as I return home,

**Comment by MpDzik** [comment]
@DanielStolt Yes, VS 2015 has quite good support for NUnit categories with the [NUnit Test Adapter](http://nunit.org/index.php?p=vsTestAdapter&r=2.6.4) extension.

![screen](https://cloud.githubusercontent.com/assets/5750314/9553714/364e0b98-4dc1-11e5-9450-856dc0e25799.png)

**Comment by sebastienros** [comment]
The issue with categories is that we would need to categorize the other tests too. I'd favor a different project for now just for the DateTime localization tests..

**Comment by DanielStolt** [comment]
Even if we put them in a separate project, how do we prevent them from running when someone just clicks "run all tests"?

**Comment by MpDzik** [comment]
@sebastienros What's wrong with having the rest of the tests uncategorized? Using categories to mark special tests (performance, long running, requiring special setup, etc) seems to me like a good idea. Even if we add those tests to a new, separate project, I think that adding a category to them is a good idea.

@DanielStolt I guess there's no way to prevent any tests from running when someone runs all tests. We could use the ExplicitAttribute, but that will cause the test not to run on the build server, which seems to defeat the whole purpose of the test.

**Comment by DanielStolt** [comment]
@MpDzik OK, yes that's where I was going with that.

Since a developer will have to consciously exclude them from the test run regardless of whether they are a separate project or categorized, I think the best solution is to *categorize* long-running tests, so that you can exclude them from your test run if you want. Less intrusive than a separate project, and also allows long-running tests to exist in any test project, mixed with other test. It seems far better to keep tests in projects based on what they actually test, rather than based on whether they are long-running or not.

We could also consider checking in a `.playlist` file which Test Explorer now apparently has support for. I haven't played with those yet - have you?

**Comment by DanielStolt** [comment]
Oh and @sebastienros I don't see why we need to categorize *all* tests - just the long-running ones.

**Comment by MpDzik** [comment]
@DanielStolt I fully agree with you. Additionally, taking into account how many projects are already in the Orchard solution, I would be against adding new ones unless it's really necessary.

I haven't used the `.playlist` file yet, but I guess it should be quite easy to create one. However, I wonder how will we maintain it, because I guess that we would need to update it once new unit tests are added?

**Comment by sebastienros** [comment]
How do you run all test "but a specific category" ?

Right now, with some attempts, my bet shot is to `Skip` them with a correct explanation.

**Comment by sebastienros** [comment]
And who among you is actually running the tests ;)

**Comment by sebastienros** [comment]
I have skipped the tests for now, but I am keeping this issue open until the final solution is implemented.

**Comment by DanielStolt** [comment]
@sebastienros It's very simple. Here's how:

![image](https://cloud.githubusercontent.com/assets/3889090/9701532/381e3b46-542e-11e5-9bcb-4119c63795d8.png)

I'm reverting your change and categorizing these tests instead. Final solution implemented. And btw, the `DateTimePartsTests` methods are very small and quick, I don't understand why you skipped those. I'm not including them in the category now.
