### ISSUE TITLE
Feature key checking in CompositionStrategy.cs

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5715]
Related to the recent issue around the auto-enabling feature, I was suggesting on gitter to remove the Core dependency from jQuery and add a feature key checking in CompositionStrategy.cs...

Just seen that you removed the jQuery Core dependency but finished to solve the issue by fixing another feature name case problem (TinyMce).

Not sure, but maybe it would be good to keep the following feature key checking that I was using. This to prevent from an exception on a simple dependency name case error in a Module.txt file

In the `CompositionStrategy.ExpandDependenciesInternal()` method

    if (availableFeatures.ContainsKey(shellFeature)) { // Additional checking
        var feature = availableFeatures[shellFeature];

        foreach (var childDependency in ExpandDependenciesInternal(availableFeatures, feature.Dependencies))
            yield return childDependency;

        foreach (var dependency in feature.Dependencies)
            yield return dependency;
    }

    yield return shellFeature;

Let me know if you agree with this and if it's worth to do a PR...

Best

**Comment by sfmskywalker** [comment]
I ran into the same issue with TinyMce (listed as TinyMCE) and decided to fix the module manifest instead of doing the additional dictionary key check so that it would be easy to identify misnamed features. This does change the behavior however, since up until this change no error would be thrown when a dependency was listed that didn't actually exist. But then errors could occur later down the line when required features aren't enabled due to a spelling mistake. Maybe we should do the key checking, and if no key was found we throw a more clear exception with a message stating the problem.

**Comment by dcinzona** [comment]
I talked to @sebastienros about this exact issue.  He may have some additional input on it.

**Comment by sebastienros** [comment]
What @sfmskywalker is suggesting was also what I thought, we check for the key and just throw a nicer exeception message that makes it clear the specific module is missing. 

At the same time we can make this dictionary case insensitive, @dcinzona checked and everywhere else it's not case sensitive. So `TYnImCE` would work but `TnMce` would throw an `OrchardException` with an explicit message.

**Comment by jtkech** [comment]
So, maybe we only need in CompositionStrategy.cs line 34 to use this

    var availableFeatures = _extensionManager.AvailableFeatures().Concat(builtinFeatureDescriptors).ToDictionary(x => x.Id, StringComparer.OrdinalIgnoreCase);

If it's ok for you, I can do a PR. Just give me the explicit message you want if the key isn't found

Best
