### ISSUE TITLE
Enhance Media Library Permissions

### ISSUE THREAD

**Issue by neTp9c** [OrchardCMS/Orchard#5726]
Media Library have only one option for permissions. It's Manage Media Content that gives full access for all media items.
Be better to divide it, at least, into two permissions: manage own media and manage media for others.

**Comment by sebastienros** [comment]
I have also been thinking about a way to have a personal storage, so that you can only manage your own folder. The use case is if you have multiple contributors for a website, who have access to different parts of the site. In this case a permission per folder would also be interesting if you want shared sections. Like for a specific blog.

For instance, let's say you build a Gallery and the contributors can define screenshots for their own modules. They need to access the Media Library, but can't edit the items from others, or even add items to other folders.

One feature would then be a Personal Media Folder, where you are the only one to be able to put media items, and with a quotas.

Another feature would be to set write permissions per folder on roles, with variations on ownership. Like several users can add media to the same folder, or pick items from it, but can only edit their contributions.

**Comment by HermesSbicego-Laser** [comment]
Hi guys, someone is working on this?

**Comment by sebastienros** [comment]
Already implemented, apparently the bug has not been closed.

**Comment by dukeofdarkness23** [comment]
Is there any future plan to deliver the folder-based permissions as mentioned above, so that several users could add media to the same folder without having the manage all media permission?

Also, an option somewhere to change a users folder name to be something other than their username would be preferable (e.g. guid or custom name) - as we have a client that considers public display of usernames in folders a potential security risk and SEO issue.
