### ISSUE TITLE
Add iframe element to Layouts

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/Orchard#5740]
Adding iframe element to layouts should be usefull for embedding video, maps or anything else without using HTML element and TinyMce which surrounds anything in "p" tags.

**Comment by sebastienros** [comment]
Does the HTML element add the <p> tag too?

**Comment by bleroy** [comment]
The correct way to add video is through the media element.

**Comment by TFleury** [comment]
@sebastienros not sure I undrestand your question. HTML element uses TinyMCE as default editor, so yes, it adds `<p>` tags.

@bleroy ok for videos, but there many other usages of iframe.

**Comment by bleroy** [comment]
Those other usages should be the objects of new elements (map, etc.). An iFrame element makes as much sense to me as a "thingy" element. It has no real semantics, it's promoting an implementation detail to become a structure that should have meaning.

**Comment by sebastienros** [comment]
We should at least have a raw HTML element which doesn't try to use TinyMCE and add a p tag all the time. Best case with CodeMirror editor.

**Comment by sfmskywalker** [comment]
There's a Text element, but that encodes the provided text I think. So might be a good idea to introduce an element where you can input raw content. Currently you would have to add a Shape element and render a Template, but a more direct approach would be great. What about the following additional set of elements:

- HtmlSnippet (or RawHtml or CodeMirror - although CodeMirror is an implementation detail, so probably not a good idea to use as its name)
- RazorSnippet (or Razor, or Code - although we may want to reserve Code for an element that renders preformatted content to demonstrate code snippets on a web page)

**Comment by sebastienros** [comment]
We should definitely have a raw element, and this would solve this current issue. Razor can could be discussed, not as important in this context (Layout) as we already have shapes, projections, I don't see what Razor would add. As long as tokens are supported in some elements, dynamic data injection would be supported.

https://github.com/OrchardCMS/Orchard/issues/5773

**Comment by bleroy** [comment]
Why do we need the paragraph element?

**Comment by sfmskywalker** [comment]
@sebastienros Yep. Tokens are widely supported.
@bleroy The reason for having a Paragraph element is so that the HtmlClass, HtmlId and HtmlStyle properties are rendered on the *<p>* tag, instead of on some outer *<div>* tag. Similar reason we have the Image element, which always renders an *<img>* tag, onto which the three properties mentioned are added as attributes.

You mean an encoding option on the Text element?

**Comment by bleroy** [comment]
Yes, on the text element. The point I was trying to make is that we may have too many elements that do essentially the same thing, and that could be fixed by having settings doing the differentiation instead of separate elements. HTML, paragraph, text, all that sounds the same to me, and is probably confusing to most users.

**Comment by sfmskywalker** [comment]
I see your point. Some practical questions, concerns and suggestions I can think of:
Let's say we have a single element called *Text*.

1. It would have an **Encode** option (Encode:yes/no)
2. The tag should probably be configurable (so that it could be rendered as a *div*, *p* or *span* tag for example, so that properties such as *HtmlId*, *HtmlClass* and *HtmlStyle* would be added as attributes on that tag).
3. What editor would be used for this element? Always the editor using the *html* flavor (TinyMce by default)? Problem with this is that TinyMce always adds a *p* tag, which becomes problematic if you really want to render a *p* element with the configured HtmlId, HtmlClass and HtmlStyle properties. 
4. Related to question 3, what if the user wants to insert a piece of Markdown flavored content? Currently we have a Markdown element for that.

**Comment by bleroy** [comment]
Not sure what the solution to #3 is, but yes.

1. Encode only makes sense for some flavors of text: not rich text/html, not Markdown, so only raw text? Maybe they are distinct flavors: plain text (encoded), and raw HTML (not encoded).
2. Yes.
3. Solution should, I suppose, be consistent with what we do in the body part and text field.
4. Markdown sounds like a flavor. It is for the body part, no?

Seems like we already solved this (twice). We should be consistent.

**Comment by sfmskywalker** [comment]
Yeah, this is solved for the BodyPart which can be configured with a flavor. So for a given content type, you can configure the flavor of its BodyPart. this happens at the content type / part configuration level. However, when it comes to a Text element, one would have to configure the desired flavor for an instance of that element. And then based on this chosen flavor, the editor should change.

I agree that consistency is king, but the user experience I just described is not consistent with anything we have I think.

Unless I'm missing your point of course.

**Comment by sfmskywalker** [comment]
So similar to having multiple content types each having their own flavor, the idea I had was we would have one element per flavor. Right now hard-coded, but it could be gone more generically using an element harvester implementation that generates an element for each installed flavor.

**Comment by bleroy** [comment]
That's kind of the opposite from what I had in mind.

**Comment by sebastienros** [comment]
I am too confused by Html/Text/Paragraph, I would assume they are just because of different editors. Ideally I would use only one element for all of them, and configure which editor to use as a feature (like for Body), but because you decided to use TinyMce as a hard coded feature you have to block people from choosing and let them extend this by adding other element types.

I don't think we should have the same flavor behavior for elements as we have for BodyPart. Because it's "placed content" I need to know what I want to place. In this case I want to place a paragraph element that I edit in TinyMce or a Mardown one which only appears with the Mardown module is fine for me. I would also like a Raw HTML one so that the editor is different.

The HtmlId, HtmlClass, ... is another issue. Maybe it should be a property on the containers, and maybe we should just have another container element to handle this, where the tag would be configurable. If the element itself doesn't support it oob.

Another simple question, how is Wordpress doing? Nothing seems to complain about it, would be interesting to see.

Very hard to talk about it on the web. we need a whiteboard. Sipke, move to Redmond.

**Comment by sfmskywalker** [comment]
Ok let me see if I get it straight: you're saying we could do with just three elements: **Html**, **Raw** and **Markdown** (which is optional, provided by the *Markdown* feature).

The editor to use for the **Html** element should be configurable (could be feature-based as Sebastien suggests). Currently it is hardcoded to use the "html" flavor  easy to have that none-hardcoded.

Regarding encoding, that has been discussed and can be done as a setting on the element itself.

Regarding HtmlId, HtmlClass and HtmlStyle and containers, @DanielStolt had a nice suggestion that basically adds another property to each element: HtmlTag.

Good idea to see how Wordpress handles this sort of thing.

Being in the same room with a whiteboard would help, yes. I'm not moving to Redmond (despite the plenty amount of Super Chargers in the area :grin: ), but maybe we could carve out some time in Alicante for some serious brainstorming on this and other matters.

**Comment by bleroy** [comment]
I can live with that. The encoding setting only makes sense on Raw.

**Comment by sebastienros** [comment]
Not sure if it's the flavor which should be configurable. But what editor is used, definitely. If it's the same thing to change the BodyPart editor and this one then even better.
