### ISSUE TITLE
Orchard.Layouts - Add Bootstrap 3 support out of the box

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5788]
I've already seen tutorials from @bleroy and @sfmskywalker explaining how to override the default Orchard.Layouts grid.

The first thing every developer is going to do to integrate it into their site is to strip this grid out and then reskin the grid and elements.

It seems like it should be a built in site setting dropdown, Renderer: Use Orchard Grid, Use Bootstrap 3.

Also by default it clashes with Bootstrap (adds padding on to the rows and makes designs bloated vertically) so you have to mod it straight out of the box even if you are willing to tolerate the grid (#5728)

**Comment by sfmskywalker** [comment]
Interesting, but in my opinion adding such a setting is arbitrary and the wrong approach, because there are many other shape templates that would need tweaks here and there in order to render good in a Bootstrap based theme. Or any other theme for that matter. You are proposing some new setting called "Renderer", but we already have a setting for this; the active theme. Themes like [Cascade.Boostrap](http://gallery.orchardproject.net/List/Modules/Orchard.Theme.Cascade.Bootstrap) contain overrides for shapes like comments, pager, logon, etc. So the need to customize is absolutely apparent, and it seems arbitrary to start providing knobs and dials for *Layouts* but not for other shapes.

The convention is that Orchard modules come with default templates out of the box that work well with the default theme (TheThemeMachine). Themes have the responsibility to override shape templates where necessary.

If you find that you need to do this for every site you start with, then maybe you just need a base theme based on Bootstrap.

**Comment by rtpHarry** [comment]
I stand corrected. I typed a reply out a few ways but that's basically it. Looking back at your blog post it doesn't seem like a big task. Thanks for the feedback.
