### ISSUE TITLE
Strange Display behaviors in cshtml files

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5797]
I just noticed that

@{
Display(Model.Content);
}

and @Display(Model.Content)
have not the same result in the same cshtml file. First does nothing (the html is generated but lost), second displays the generated html.
May be normal but very disappointing.

**another one
@foreach( var item in Model.Items)
{
Display(item);
}
no more works, it was working in the past according some threads in Stakeoverflow.
The only way to have it working is now with @DisplayChildren(Model).

**Comment by sfmskywalker** [comment]
That makes perfect sense to me: @Something is more or less equivalent to @{Response.Write(Something)}.

If

**Comment by sfmskywalker** [comment]
My initial reaction is that it makes perfect sense to me that @Display workes and @{ Display } doesn't because:

`@Display(Model.Content)` is more or less equivalent to `@{ Output.Write(Display(Model.Content)); } (The @ sign used like that is just a shortcut to Output.Write or Response.Write, can't recall exactly).

That being said, the Display property is a dynamic beast that may originally very well do the Output.Write itself if it "knows" that it is not used in a way that expects a return value. So maybe a bug in Displayitself.

Do you know in what version it used to work?

**Comment by CSurieux** [comment]
It's not probing, more ambiguous than clearly error prone as this one
http://stackoverflow.com/questions/15082498/override-zone-rendering

But I don't think that this kind of behavior could help simplifying Orchard usage, clearly some trick to know...

The bad thing is that if you trace the Display inside the braces, it seems to work and generates the full html but on the end the result is garbage collected on a simple return from dozen of delayed actions.

**Comment by harmony7** [comment]
@CSurieux, as @sfmskywalker pointed out above, @{ Display(shape); } is going to render the shape and then the return value is just going to be thrown away. @Display(shape) will render the shape and then the return value will be output to the stream. This is the way Razor works, and does not have anything to do with Orchard.

The same thing would happen in this case:
@{ DateTime.Now; }    <-- output nothing
@DateTime.Now      <-- outputs current date

Think of the first as simply executing the contents of the braces as a code block. The second treats the expression after the @ as an expression and then adds that to the stream.

In the days of .aspx, we had <% %> and <%= %> to differentiate the two cases. The first is a block of code, the second is an expression that is expected to return a string.
In Razor, @{ } is the equivalent of <% %>, and @() or @ by itself precededing an expression is the equivalent of <%= %>.

<% Display(shape); %>   <-- would render shape and discard string
<%= Display(shape) %>  <-- would render shape and insert into stream

Actually it's probably closer to <%: %> because of the automatic HTML encoding, but that's beside the point of my post.

If it "used to" work, then it sounds like that was probably buggy behavior that got fixed. That means Display() had been outputting directly to the stream, rather than returning the value and letting the ViewPage render it.

**Comment by CSurieux** [comment]
Ok @harmony7 your explanation is clear but it Is not because razor has inherited some bad behaviors from the prehistoric times that orchard should follow.
From what I knows, we have defined these 2 different Display.
