### ISSUE TITLE
Orchard.Layouts - Admin CSS gobbles up br tags in layout editor

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5825]
Fresh installed 1.9.x

If you use shift-enter to add `<br>` tags they aren't displayed correctly in the admin panel.

Example screenshot below:

![layout-br-tags-display](https://cloud.githubusercontent.com/assets/1038062/9931128/dd977dac-5d30-11e5-9e89-fa9de3e3fd7f.PNG)

Markup was:

    <p>This has some br breaks here:<br>
    and here:<br>
    But a rule in the admin stylesheet gobbles it up.</p>

Offending rule:

![layout-br-tags-css](https://cloud.githubusercontent.com/assets/1038062/9931129/def7184c-5d30-11e5-9472-f5e30f589185.PNG)

This is an admin only bug, the `<br>` tags are saved correctly and displayed on the front end.

**Comment by rtpHarry** [comment]
@DanielStolt do you remember where you got [this br reset snippet](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Layouts/Assets/Less/LayoutEditor/Reset.less#L147) from because it doesn't seem to work?

**Comment by DanielStolt** [comment]
@rtpHarry Hmm... My memory is somewhat vague on this, but I think I actually constructed this reset based on some spec from W3C detailing a "default user agent stylesheet". But I have noticed that lately this reset does not seem to have the desired effect anymore, because text in the layout editor seems to use fonts from the admin UI again... been meaning to look into it but haven't gotten around to it.

**Comment by rtpHarry** [comment]
I checked it out and found w3c spec for html 4, that applied it to the `br::before` instead of `br`.

That's fixed it.

**Comment by rtpHarry** [comment]
@sebastienros I think this one should have got moved over to the Orchard 1.10.2 milestone when it the pr was accepted yesterday. Is that how it works? 1.10.x while its up for grabs and then when it gets accepted it moves over to 1.10.2 so you can track for the release notes, etc
