### ISSUE TITLE
Ensure PR/5887 is correct

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#5945]
https://github.com/OrchardCMS/Orchard/pull/5887

**Comment by jtkech** [comment]
@sebastienros, this PR isn't related to the one where many changes around the httpcontext was done and reverted, I did it after...

Because of the layout indexing, now in the context of a `BackgroundTask` new things can be done as rendering shapes. Then, the `GetContext()` method, the one with an `HttpContext` parameter, can be called in a background task. Indeed here it's an `HttpContextPlaceholder` but with the current implementation, its `Items` collection doesn't contain the `WorkContext`. So, the following to fix it.

             public WorkContext GetContext(HttpContextBase httpContext) {
    -            return httpContext.Items[_workContextKey] as WorkContext;
    +            if (!httpContext.IsBackgroundContext())
    +                return httpContext.Items[_workContextKey] as WorkContext;
    +
    +            WorkContext workContext;
    +            return EnsureThreadStaticContexts().TryGetValue(_workContextKey, out workContext) ? workContext : null;
             }

About the following that can also be called from a `BackgroundTask` after a `PublishLater`. Here, the `WorkContext.HttpContext` property uses the `HttpContextAccessor` that return null with the current implementation. In a `BackgroundTask`, currently, you have to resolve directly an `HttpContextBase`.

             public void Remove(string key) {
    -            _workContext.HttpContext.Cache.Remove(key);
    +            if (_workContext.HttpContext != null)
    +                _workContext.HttpContext.Cache.Remove(key);
             }

I've worked on an experimental PR #5966 to harmonize the `HttpContextAccessor`, the `HttpContextBase Factory`..., and to fix other issues, particularly when rendering shapes in the background... E.g, seems to fix an issue for someone that tried it, see here #5983. But, because it's a sensitive area and because I use the `CallContext Logical Data`, maybe there are some impact on performance or other side effects, I need help to eventually validate it...

I have other ideas but it depends on what could be first validated, e.g I also have some solutions for this one #4666.

Best
