### ISSUE TITLE
Performance issue when authenticating a non-orchard user account using an external user store

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5997]
The issue boils down to multiple DB calls during a single request if the following conditions are met:

1. The request is authenticated.
2. But the username stored in the cookie is not mapped to an Orchard user account.

This causes the `FormsAuthenticationService.GetAuthenticatedUser` to always go into the DB and try and get the user by the cookied user name. Which happens many times during a single request.

> The performance drain is especially felt when loading a large number of content items that have the `CommonPart` attached. The `CommonPartHandler` assigns the currently loggedin user to the content items being initialized.

A simple fix would be to set a Boolean flag in `FormsAuthenticationService` so that it won't keep calling into the DB if that already resulted into a null value.

**Comment by Piedone** [comment]
If there is a custom way in that app to authenticate users than I'd say that you need to override FormsAuthenticationService.

**Comment by CSurieux** [comment]
How could you have authenticated users not mapped to an Orchard account ?

**Comment by sfmskywalker** [comment]
@Piedone Well, adding a check against some flag instead of blindly going against the database again and again when the queried user name returns null does not cause any disadvantages. On the contrary, it improves the robustness of the class IMO. And I think this is a common enough scenario that it is a plus that we don't have to duplicate the code into our own module just for this check.

@CSurieux I queried a different user store and then set a forms authentication cookie.

**Comment by CSurieux** [comment]
Well you should not use form authentication but something as OAuth2...Not supporter by Orchard.

**Comment by sfmskywalker** [comment]
Regardless of the authentication mechanism (Orchard Users, OAuth2 provider, whatever), I still need to set a persistence cookie once credential validation is successful (using `IAuthenticationService`).

On a slightly related note, I think that `IAuthenticationService` should not event return an `IUser` (Or `IUsers` would not be an `IContent`).

**Comment by DanielStolt** [comment]
Agree with @sfmskywalker here. There's no downside to making this class more robust, and the case where some users are not content items is quite common in my experience. Also agree that `IUser` should be broken apart from any content management types, although I seem to recall others have tried this in the past and fail... @PaulDevenneyBede?

**Comment by CSurieux** [comment]
@DanielStolt  Ok but what I don't understand is that as far as someone is authenticated somewhere, Orchard should accept him without any further checking ?

**Comment by DanielStolt** [comment]
@CSurieux I don't understand what you're asking.

**Comment by CSurieux** [comment]
Ok, funny, but the question still exists

**Comment by PaulDevenney** [comment]
@DanielStolt We have (of course) observed this issue. IIRC We've always resolved it by supressing the MembershipService with our own, which deals with some per-request caching of the result (in our case an API call) to ensure that the crazy number of `GetAuthenticatedUser` calls has minimal impact. As I've previously mentioned in posts on the old forums:

* It doesn't seem necessary that `GetAuthenticatedUser` is called for every part (or whatever). It results in potentially hundreds of unnecessary calls. Per page. Any underlying implementation with non-zero latency is therefore far more complex to implement
* `IUser` is a leaky abstraction, because you are forced to recognised ContentItem in the contract. We  have `IUser` implementations with fake content items (with ID zero), but this solution still has limitations - if we need a user in the back office we *must* create a user in the Orchard tables. The correct implementation (IMO) would be a DTO style `User` object (in fact, why not just use `ClaimsPrincipal` which is easy for developers to add to)?
* The back office office of Orchard goes *direct* to the content manager, rather than using a membership service that others could override). This makes any attempt to swap out membership for orchard non-trivial, as there is not one single interface to use for Membership within Orchard

**Comment by DanielStolt** [comment]
OK, well I'm going to go ahead and make the first simple part of this change in `dev`, i.e. to make `FormsAuthenticationService` more robust in these cases.
