### ISSUE TITLE
There should be a default startup recipe without LayoutParts

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6061]
Layout parts are a great dev but I am not satisfied with it and I would prefer to be able to install Orchard without them everywhere: pages with body, etc.
The all drag and drop is not efficient for the kind of sites I build, I prefer being able to select my display type and write my shapes in my theme, to use alternates and wrappers and to use VS text editor to write my own razor/html with direct control, also because TinyMCE is still bogus with html - and it is not something easy to fix - and offers a very poor editor experience.

Moreover the source code gets overcomplicated by layoutPart and special drivers constraints.

I am not satisfied with the actual tendency/decision to put Layout Parts everywhere. Even if I know that the people behind this are solid dev and bringing huge effort to reach a stable version.
I would appreciate to have layout parts totally swtchable.

EDIT: this effort reminds me the start of asp.net webforms with all the custom controls: we were dragging them in a design view and spending lot of time to create our own custom controls (I remember the fabulous book made by this guy, Nikhil Khotari, now at Google's). I don't need all these elements as a mediation layer between html /css and me. This seems an outdated concept overcomplicating everything. I think Orchard is not taking the good direction. Using a part to drive layout is not good. My opinion. May be some others share it.

**Comment by mkinawy** [comment]
How about disabling that feature after the installation is done and then modify the corresponding content types like "Page" to have the "BodyPart"?

**Comment by sebastienros** [comment]
The Layout Part is only added to Page by default, and Page itself is really that, a routable content representing some placed content, for which Layouts is the best fit. So your issue is just that you shouldn't use Page but create some specific content type with something else than Layout Part. The default configuration fits most web dev, and __it's up to you to delete this content type, create the one you want, with the parts you want__, and even define it as the default recipe. 

A single default recipe cannot suit everyone's needs, but still there is a single default recipe. There is absolutely no magical way to suit everyone's need but what we have done, making it completely configurable so everyone can customize it and make their own defaults.

> Moreover the source code gets overcomplicated by layoutPart and special drivers constraints.

You don't have to use Layout Parts or elements if you don't want to. Nothing is forcing you, it's still a module that can be disabled and ignored.

I will ask the question at the next meeting, who wants Layout by default on Pages, or BodyPart by default on Page. Though I think we already had this discussion which led into the current configuration.

**Comment by CSurieux** [comment]
My question is more on forcing people to use this rather then letting them choose to use it.
As said in my upper text, I am not sure it is a good option because it is not totally adapted to Orchard. An exemple: how to build a layout for a Summary view ?

I am afraid by what I am hearing about widget being wrapped in elements. It seems that many components have alreday been changed in their fondmentals  to work in background with layouts (projections ?).

Again the all click-drag environment seems an outdated dream, engaging lot of dev efforts for a not obvious benefit.

**Comment by mkinawy** [comment]
There is a big difference between what we were doing in ASP.NET WebForms (developing), and the layering stuff (UX), the first one is for devs but the second one is usually for editors, authors, data entries, etc

I like Layers more than the old Body stuff, the body HTML is very limited which isn't the case for layers, and you can add HTML into layers, so I think you just need to give it 5 minutes :)
and if you still don't like it then remove it and use the old body

If we do a vote on the default recipe to go back to body or keep using the layers, layers will definitely win by way difference in votes.

**Comment by CSurieux** [comment]
I can see your point between 'Devs and Layering stuuf' but don't understandd it: is your laering stuff culture based on html5/Css3 or Orchard ?

I not specially attached to the body part, but more raising a warning on global concepts behind orchard: layouts - and not layers, it is something different in orchard - are targeting higher than the body part.

And concerning vote, what is it's reality, how many have voted recently ? in my country less than 30% of people vote but they live and appreciate their country.

Tell me if layouts are so easy:
- why when I have a large html text to insert in a layout, I end with dozen of staked windows, why did I have to wait 10 x x seconds each time I push a validate button, why sometime I get a session lost if I spend to much time on the phone with all my popups open.
- why I can't easilly change the final html code directly

and more

- how can I use alternates with layouts
- how can I take benefits from the Orchard facility in drivers to generate Detail, Summary, SummaryAdmin kind of views


If I was speaking of the old time of WebForms, it is because at that time the layering stuff was using the design view from VS with all the simulated controls from the control box...that was the ontention beyond web form. Orchard is doing quite the same. What is the futur of all this concept of elements (the new custom controls, I suggest we also re-invent the user control, we have also copied the concept of master pages) in term of standarts ?

For me text file don't look out of date if they bring better precision and faster job: may be the Orchard committee missed the point of bringing Orchard to a wider population, they take it for using only click and drag.

**Comment by bleroy** [comment]
This doesn't make any sense. As has been asked, what is preventing you from doing exactly what you want to do? Everything that was working before layouts still works. It's still trivial to build a page type without layouts.
I have no idea what that "dozen of staked windows" that your're talking about is. That doesn't resemble anything I've experienced with dynamic layouts.
You can change the html code, always. That's a central principle in Orchard. It's all in templates that you can override. Nothing's different in layouts: still using shapes, for which you can still alternate and override templates.
So yes, using alternates with layouts is trivial. I haven't checked display type, but if they aren't here (which I doubt), that would be a bug, not a design flaw.
I've worked on WebForms (I mean, I wrote some of its code), and I can tell you, this is absolutely nothing like it.
We love text files too, and you can still use them. But you don't have to.
It almost looks like you decided on your conclusion, and refuse to see any evidence to the contrary.

**Comment by CSurieux** [comment]
What is the effort to have one more startup selection for 'old fashion features' ? I don't see the problem ?

Concerning the windows staked :

- The content Edit window
- The tinyMCE Html insert window for the layout Part
- The Html source code from  tinyMCE (The very bad one)


Do I made an error ?
And each time I need to validate, it takes more time on each pop.

For WebForms, sorry but it seems very similar:
- custom cpntrols = elements: their ain usage is to wrapp some html element (because at that time MS was still expecting that html would stay as an underground langage)
- Master Pages = Master pages 

For alternates sorry but is not ... perfect: how do you build teh display for the alternate, may be I again missed some doc
Andd for display type, it seems limited: for exemple Summary view truncate thee begenning of the complicated View using grid and all the tralala you spent hours to build.

The worst element in all this is tintMCE with make all Orchard developpers cry since html5 begun more widespread: you are never sure that the html you inserted will not been changed.

So finally I am always building my html code in VS editor, just as ffor blogs, who enter its text with tinyMCE ?
And finally would be very happy with some tool able to inject a text filee as the html content in BodyPart or Any part using an html content. Just as we do for blogs. 
May be it already exists ?

**Comment by bleroy** [comment]
I see. So those "dozen of staked windows" are really three ;) And that can be avoided by using a paragraph element instead of rich text: why use the rich text editor if you're going to edit the raw HTML? Personally, I would have preferred a unique Text element with flavors and settings, but if you know your elements, that's still pretty usable.
Not to nitpick, but you seem to be ranting against encapsulation and re-use, not WebForms. Those are hardly concepts that WebForms invented. What WebForms were about was abstracting HTTP under an event abstraction. Another thing that WebForms did was to encapsulate the rendering into the components, making it hard to change. There is none of that, none, in Orchard's layouts.
What do you mean by "how do you build the display for the alternate"?
The summary template can do whatever you want, you just have to override it. You are describing the default behavior, that you have the power to change. Not sure what "grid" you are talking about.
I'm not crazy about TinyMCE myself, but there are worthy alternatives. My favorite is MArkdown, but you can also use raw HTML, or build your own editor using a different library.
So I guess you'll be very happy, as you can use raw HTML, like you can for blogs or any content type.

**Comment by sfmskywalker** [comment]
> I would be very happy with some tool able to inject a text file as the html content in BodyPart or Any part using an html content. Just as we do for blogs. 
May be it already exists ?

The BodyPart can be configured with the "textarea" flavor.

**Comment by sfmskywalker** [comment]
@bleroy 

> Personally, I would have preferred a unique Text element with flavors and settings.

You mentioned this before, and I like it. I am just wondering how this would work. There's actually an open issue that requests an "Raw HTML" element (#5773). Perhaps that would be one of the flavors.
