### ISSUE TITLE
SmtpMessageChannel file attachment feature

### ISSUE THREAD

**Issue by leventesen** [OrchardCMS/Orchard#6082]
SmtpMessageChannel in Orchard.Email module does not provide a file attachment mechanism.

**Comment by Ermesx** [comment]
You can do it because @sfmskywalker add this functionality in this commit: 81fb0d7bf57e17adedeea6c47879898ca4f0038e  
You can specify the Message parameter where you can put `MailMessage` object with attachment
```c#
// Part of SmtpMessageChannel.cs
if (parameters.ContainsKey("Message")) {
// A full message object is provided by the sender.

    var oldMessage = mailMessage;
    mailMessage = (MailMessage)parameters["Message"];

    if (String.IsNullOrWhiteSpace(mailMessage.Subject))
        

    if (String.IsNullOrWhiteSpace(mailMessage.Body)) {
        mailMessage.Body = oldMessage.Body;
        mailMessage.IsBodyHtml = oldMessage.IsBodyHtml;
    }
}
```
But I think it works strange...
You can put to parameter "Message" completly configured `MailMessage` object with recipients, attachments, body, subject, to , from etc. but also you have to put "Recipients", becuase elier in the code is check:
```c#
if (emailMessage.Recipients.Length == 0) {
    Logger.Error("Email message doesn't have any recipient");
    return;
}
```
I don't know why, but it is :)

**Comment by leventesen** [comment]
I searched but didn't find :)
Sorry for duplicate.
