### ISSUE TITLE
Adding a field to an existing ContentType during migration leads to duplicate ContentPartDefinition in the ContentItem

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6151]
I did this in Dev, which seems to be the recommanded way of adding a field directly on the ContentItem ( and not under one of its parts).

ContentDefinitionManager.AlterPartDefinition("MyNewType",
    cfg => cfg
        .Attachable()
        .WithField("Picture", f => f
            .OfType("MediaLibraryPickerField")
            .WithDisplayName("Type picture"))
);

ContentDefinitionManager.AlterTypeDefinition("MyNewType",
    cfg => cfg
        .WithPart("MyNewType")
    );
 
My fields normally appear under the ContentItem in the ContentType Editor but the tokens are not working. Using the debugger on the ContentItem I discovered that the PartDefinition for the 'hidden part' nammed as the ContentItem is duplicated.

**Comment by CSurieux** [comment]
I can no more repro, so it must have been my mistake. Closing.

**Comment by dcinzona** [comment]
I actually experienced something similar to this, where it seemed like the migration would run twice, and I would get duplicate fields. We haven't been able to figure out if there is a problem with migrations or if it was because we are running Orchard in a web farm with multiple instances.
There is an active bug with migrations in web farm scenarios.
