### ISSUE TITLE
Improvement: Include tokens into BodyPart Text (or any Text 'flavored' Part) 

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6155]
I propose to extend interface IHtmlFilter to include a ContentItem as last parameter
> string ProcessContent(string text, string flavor, ContentItem Item);

doing so we could have in the DisplayDriver of any text flavored Part some code as this

> 'protected override DriverResult Display(BodyPart part, string displayType, dynamic shapeHelper) {
            return ContentShape("Parts_Common_BodySummary",
                             () => {
                                 var bodyText = _htmlFilters.Aggregate(part.Text, (text, filter) => filter.ProcessContent(text, GetFlavor(part),part.ContentItem));
                                 return shapeHelper.Parts_Common_Body(Html: new HtmlString(bodyText));
                             });
        }
'

then we need a new filter doing

>'public string ProcessContent(string text, string flavor, ContentItem Item) {
            if (String.IsNullOrEmpty(text))
                return "";
            if (!text.Contains("#{")) {
                return text;
            }
            text = _tokenizer.Replace(text, new { Text = "Content", Content = Item }, new ReplaceOptions { Encoding = ReplaceOptions.NoEncode });
            return text;
        }'

with this modification, we could include markers as

>  '#{Content.Fields.BlogPost.Images.Url}' 

and have them displayed .

Hope it doesn't already exist ?

**Comment by Piedone** [comment]
@sebastienros you implemented tokenized body somehow, right?

**Comment by jtkech** [comment]
@CSurieux @Piedone i think @CSurieux suggestion is a good idea

First, in Orchard.Tokens there is the `TokensFilter` html filter used by the BodyPart. It inherits from `ContentHandler` so it can grab the `ContentItem` in the `BuildDisplayShape` override... So:

- There is the `Tokens Html Filter` feature, html filters are used by the body part.
- There is the `Element Tokens` used by the Html, Text and Paragraph elements.

Infortunately, when both are enabled, because the 1st `TokensFilter` inherit from `ContentHandler`, not the 2nd one (`IElementFilter`), context data are not passed in the same way and can be null. So, a first running filter can remove the token.

@sfmskywalker has done the same as @CSurieux suggests by creating an `IElementFilter` that proposes an additional `ProcessContent()` with a context parameter, see in `ElementFilterProcessor.cs` how a context can be passed if it's an element filter, but not if it's a regular filter. In another side, when a regular driver call an element filter, it can't pass a context because it uses it as an `IHtmlFilter`.

To allow such filters to cohabit, in `Tokenizer.cs`, I've found a fix by testing if the replacement value is null and then do nothing on the token. Maybe it's worth to do a PR, but, because now we have not only content parts but also elements, it seems that filters using content data should be decoupled from this.

Last thing, it seems that the `ReplaceOptions` needs to the default = `HtmlEncode` because e.g with a body part already encoded, the token needs to be encoded. But when the content can be encoded by another html filter (e.g if `textarea` flavor), the token may be encoded twice if evaluated before.

For elements the `ReplaceOptions` = `NoEncode`, maybe not right for elements already encoded, and for the others if the token filter here runs last. But it's another issue, maybe not so important with unicode pages. Is it worth to work on it?

Best

**Comment by jtkech** [comment]
Sync done

**Comment by CSurieux** [comment]
I agree
