### ISSUE TITLE
Generating TechnicalName for ContenTypes, ContentFields creates disallowed names

### ISSUE THREAD

**Issue by SzymonSel** [OrchardCMS/Orchard#6168]
When creating adding a Field to a ContentPart/ContentType with a DisplayName that already exists, a TechnicalName is generated, which contains a '-'. If we try to save, then a validation error message is display: "The technical name contains invalid characters."

So we have some disambiguity here. This might also cause problems with ContentType names.

Should "-" be allowed in TechnicalNames?

**Comment by sfmskywalker** [comment]
We can't allow - in technical names, because those names need to be usable as C# names when content items, parts and fields are accessed using the dynamic syntax. Unless of course we translate hyphens to underscores or something similar, but that wouldn't add any benefit IMO, just complicate things. The ambiguity however should be fixed.

**Comment by SzymonSel** [comment]
OK, you can assign this bug to me.
