### ISSUE TITLE
ContentHandler TokenFilter and Element TokenFilter can't cohabit

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#6193]
**Repro** on dev branch
- In an html widget, use a token that need Content data, e.g #{ Content.Id }.
- So, enable the `Tokens Html Filter` feature (will be used by the body part).
- In an Layout element (text, html...) use such a token, e.g the same as above.
- So, enable the `Element Tokens` feature used by the html, text... elements.

**Result**
- The token in the html widget is not evaluated correctly.
- Note: may depends on the token filters ordering (see below).

**Analyse**

The 1st TokensFilter inherit from ContentHandler, not the 2nd one (IElementFilter), context data are not passed in the same way and can be empty. So, a first running filter can kill the token.

Maybe the 1st filter (that is an html filter) should not be coupled to a content type by exposing a ProcessContent() method with a data context parameter... More details in my last comment here #6155.

**Fix**

To allow such filters to cohabit, in Tokenizer.cs, I've found a fix by testing if the replacement value is null and then do nothing on the token. I will do a PR.

Best

**Comment by sfmskywalker** [comment]
Ideally the Layouts module would not need its own `TokenFilter`, but the reason it was added the way it is is because it needs a way to pass along the **Content** item.

The `TokenFilter` implementation in Orchard.Tokens does this by deriving from ContentHandler and storing a reference to any content item being displayed (which I think is flawed, because multiple content items are potentially rendered on a single requests, e.g. the case of Widgets).

The **ideal solution** would be to have a single `TokenFilter`.

But we need a way to be able to provide context to `IHtmlFilter.ProcessContent` (not just `text` and `flavor`.

If we could go back in time, we could perhaps add a dictionary of context, and each `IHtmlFilter` implementation would know what values to look for.

But since my time machine isn't done yet, could we introduce another interface that filters like `TokenFilter` could implement? Obviously the caller would need to check for implementations of this interface so it can provide the context.

An example could be unimaginedly called `IHtmlFilter2`:

```C#
interface IHtmlFilter2 : IHtmlFilter {
   string ProcessContent(string text, HtmlFilterArgs args);
}

class HtmlFilterArgs {
   string Flavor;
   IDictionary<string, object> Context;
}
```

Then, callers such as the `BodyPartDriver` would invoke filters like this:

```C#
var bodyText = part.Text;
var context = new Dictionary<string, object> { { "Content", part.ContentItem } };
var filterArgs = new HtmlFilterArgs { Flavor = flavor, Context = context };
foreach (var htmlFilter in _filters) {
                var filter2 = htmlFilter as IHtmlFilter2;
                bodyText = filter2 != null
                    ? filter2.ProcessContent(text, filterArgs) // Call IHtmlFilter2 if implemented.
                     : htmlFilter.ProcessContent(text, flavor); // Otherwise call IHtmlFilter.
            }
```

This would solve the problem as mentioned in this issue as well as greatly improve the current implementation of `TokenFilter` in Orhard.Tokens.

**Comment by sfmskywalker** [comment]
I created a PR here that implements my suggestion: #6892 

The result is that we can use a single `TokensFilter` implementation that behaves as expected:

![image](https://cloud.githubusercontent.com/assets/938393/15230744/93991904-1897-11e6-8c39-47c16689a962.png)

**Comment by sfmskywalker** [comment]
And point in case, this is the result without my PR (in the 1.10.x branch):

![image](https://cloud.githubusercontent.com/assets/938393/15230935/84c2f4da-1898-11e6-9878-fada14b66cf7.png)

This is using the same database. The Html Widget using the {Content.Id} token is expected to render "12", but instead renders "11", which is the ID of the Menu Widget.

**Comment by jtkech** [comment]
Perfect :+1: , i'll close my related pr.

**Comment by jtkech** [comment]
Just for info, this one is waiting for sipke PR #6938.
