### ISSUE TITLE
IHomeAliasService GetHomePage() issue with a possible fix

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#6273]
Now, in the dev branch, `IHomeAliasService GetHomePage()` uses somewhere an alias map, based on the area name, and assumes that the home page alias is the first one. But this is not true in some use cases, e.g with some more complex route path graphs...

E.g if you define a route `.../foo1/` with a trailing slash, and another route like this `.../foo1/foo2`, then, in the alias map, these aliases will be before the home page alias. This is the case when you create a taxonomy and then create some child terms... You have the same kind of issue when modifying the home page slug or promoting another page to be the home page...

@sfmskywalker, i can fix it easily by modifying the `GetHomePage()` method as below. This to use as before the content manager directly with the `Id` retrieved from the `homePageRoute`... But maybe there is a good reason to use now an `alias map` and then the `AutoroutePartRecord` table... If so, i may have another fix that still take into account the `Id key` in the route values (not only the `area key`)... Let me know.

        public IContent GetHomePage(VersionOptions version = null) {
            var homePageRoute = GetHomeRoute();

            if (homePageRoute == null)
                return null;

            object id;
            if (homePageRoute.TryGetValue("id", out id)) {
                int homePageId;
                if (Int32.TryParse(id.ToString(), out homePageId))
                    return _contentManager.Get(homePageId, version?? VersionOptions.Published);
            }

            return null;
        }

Best

**Comment by sfmskywalker** [comment]
The reason I changed to using the alias map instead of the content manager is because the alias map is stored in memory, so it would be a faster lookup than going through the content manager. However, if it causes issues under the conditions you mentioned, then I would love to see a fix for that. If you have one that doesn't involve the content manager, then great. Otherwise I'm not opposed to going back to using the content manager like it was before.

**Comment by sebastienros** [comment]
Can you provide some step-by-step repro? I can't isolate the issue.

**Comment by sfmskywalker** [comment]
@jtkech I misread your comments and the code actually. I am using a content manager query as well, but using `Query` rather than `Get`. When you say that I am using first or default, are you referring to this line here (line 73)?

```
var alias = map.GetAliases().FirstOrDefault(x => !String.IsNullOrWhiteSpace(x.Path));
```

If so, then if you know of a better way not assuming the first or default item, then I would love to hear it.

Regarding your suggested code change however, the problem there is the assumption of the `"id"` key name. There are content handlers that provide a custom display route value dictionary that use other keys. Take for example the Blogs module which uses its own controller to display a blog, and therefore provides a custom display route value dictionary, and instead of `"id"`, uses `"blogId"`.

**Comment by jtkech** [comment]
@sebastienros 

I don't recall exactly but i've seen this when trying to use the `FrontEndCultureSelector.cshtml` razor view in `Orchard.Localization` that uses the `GetHomePage()` method. Then i've seen the problem in the scenarios described above. Note: when i was saying: "define a route .../foo1/" i meant create a page with "foo1/" slug...

But the easiest way to repro, with a fresh dev branch installation, is to create one or two new pages. Then edit one of this new page and promote it to be the home page. Then go to the `Welcome to Orchard!` page and you still see `This content is the current home page`.

@sfmskywalker 

Yes, i was referring to the line 73. One question, do you use `Query` on `AutoroutePartRecord` rather than `Get` because it' faster? Or for another reason?

Oh, i didn't think about custom route values as with `blogId`. So i need to re-visit the code, maybe i will have some questions...

Best
