### ISSUE TITLE
Days and Months names are translated all lowercase in French

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6275]
First I am surprised that the code to display Formated DateTimes is duplicated between 
Orchard.Localization\Providers\LocalizationDateTimeFormatProvider.cs 
and 
Orchard.Framework\Localization\Services\CultureDateTimeFormatProvider.cs 

???? 
then looking to the code we see that English renders a Capitalized first letter, but loading the french translation ( 1 month old), I get all the days and months as lower case.

public string[] DayNames {
            get {
                return T("Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday").Text.Split(new string[] { ", " }, StringSplitOptions.RemoveEmptyEntries);
            }
        }

public string[] MonthNames {
            get {
                return T("January, February, March, April, May, June, July, August, September, October, November, December").Text.Split(new string[] {", "}, StringSplitOptions.RemoveEmptyEntries);
            }
        }

I will hack my file...no time to go to the full translation engine.

**Comment by CSurieux** [comment]
Ok, when trying to hack the Fr-fr file I found that the Uppercase are here, so ????

Then I discovered this
[OrchardFeature("Orchard.Localization.DateTimeFormat")]
    [OrchardSuppressDependency("Orchard.Localization.Services.CultureDateTimeFormatProvider")]
related to the 2 implementations of date formating previous remark.
And it is very strange and I don't understand the reason why month and day names and should be translated differently when we enable or not the Localisation feature ?????

In my case it is not enabled because I don't need different languages as French and my site is set to use Fr-fr as default culture.
So code goes for using the .Net implementation (normally the best ?), Could the bug be inside Windows 10 ??? ... 

#Should I change my Issue title for ' Their should be only one code for translating names of days and months ????

**Comment by agriffard** [comment]
The French translations of Days and Months names are not in lower case in Orchard.Localization\Providers\LocalizationDateTimeFormatProvider.cs : 
https://crowdin.com/translate/orchard-cms/325/enus-fr#q=LocalizationDateTimeFormatProvider

The translations from CultureDateTimeFormatProvider are missing because it comes from variables that are in System.Globalization.DateTimeFormatInfo (ex : DateTimeFormat.MonthNames) and the tool can not detect it has to be translated (cc @BenedekFarkas )

And in the end, it seems to be a little more complex because some shapes that display Datetimes seem to use IDateLocalizationServices and IDateFormatter implemented by @DanielStolt in which Date formats are deducted and I don't know how they can be translated.

**Comment by CSurieux** [comment]
Antoine,

It is no so complicated. It has been complicated.

Thanks but the problem is : why 2 translations systems for Months and Days names.
It should not change when enabling or not the localization features: if when not enabled orchard  translates something, it should provide the same result when enabled ? It seems evident, isn't it ?

**Comment by CSurieux** [comment]
Another point, isn't this another bug, why is it not publisheddateTimeUtc which ise rendered ??? What is the usage of this date if never used ???

        [Shape]
        public IHtmlString PublishedState(dynamic Display, DateTime createdDateTimeUtc, DateTime? publisheddateTimeUtc) {
            if (!publisheddateTimeUtc.HasValue) {
                return T("Draft");
            }

            return Display.DateTime(DateTimeUtc: createdDateTimeUtc);
        }

**Comment by DanielStolt** [comment]
The feature `Orchard.Localization.DateTimeFormat` should normally not be enabled at all. The only purpose of this feature is when you want to do translation (PO) based localization of the date/time formats, instead of relying on `System.Globalization`. But I think in most cases this is not necessary, so you should leave the feature disabled, which will instead use the normal `CultureDateTimeFormatProvider` implementation.

**Comment by CSurieux** [comment]
This should be documented and It should return the same results as the 'normal CultureDateTimeFormatProvider ' when enabled.

**Comment by DanielStolt** [comment]
Many things in Orchard should be documented. :) Feel free to document it and submit a PR.

Since it's a different implementation for a different purpose it should not always return the same results (otherwise what would be the point?). You should only need the feature when you actually *want* it to return something different. It is up to the translation files what will be returned.

If the current translation file for French is wrong, then I agree that we should fix it. I'm actually not sure where they are stored though..?

**Comment by CSurieux** [comment]
Orchard committe should engage a long term action on doc.
Concerning my pb, I think that Microsoft is providing a bad solution. In french and spanish and certainly other languages they decided that these languages don't use upper case first letter for day and month name. Since the origin of the company. Si the English version display Monday and the French lundi. They only return lowercase strings. They have only one call which bring back the 'Microsoft decided official version'. It Is vert limited considering languages as french and spanish.
We more often use dates with upper char in first place for days and months in french.
It would have been easier to adopt the same rules as in English because converting a whole formatted string to lowercase is easier.

Orchard should fox this pb either using your solution either providing 2 kind of api for names and adapted core shapes.


Envoyé à partir de mon sanyo phc 25
________________________________
De : Daniel Stolt<mailto:notifications@github.com>
Envoyé : ‎12/‎01/‎2016 19:29
À : OrchardCMS/Orchard<mailto:Orchard@noreply.github.com>
Cc : CSurieux<mailto:christian.surieux@hotmail.fr>
Objet : Re: [Orchard] Days and Months names are translated all lowercase in French (#6275)

Many things in Orchard should be documented. :) Feel free to document it and submit a PR.

Since it's a different implementation for a different purpose it should not always return the same results (otherwise what would be the point?). You should only need the feature when you actually *want* it to return something different. It is up to the translation files what will be returned.

If the current translation file for French is wrong, then I agree that we should fix it. I'm actually not sure where they are stored though..?

---

**Comment by bleroy** [comment]
The rule in French is lowercase for days of the week and month names. Look it up.

**Comment by DanielStolt** [comment]
I don't believe the .NET Framework implementation is wrong at all, I am pretty sure lowercase names is the official standard for French, but then again I am not French so I have less authority I suppose.

Regardless of that - Orchard's deliberate goal in the area is:

- Use the .NET Framework localizations of date/time formats and names by default.
- If anybody wants different translations, they can enable the Orchard.Localization.DateTimeFormat feature and provide their own PO file.
- Or they can substitute their own implementation and return whatever formats and names they want.

I don't believe Orchard should be changed in this regard. I think this is the absolute best strategy to use, and covers the absolute majority of cases.

In your case, you are free to use either of the two mechanisms to override the default behavior.

**Comment by agriffard** [comment]
Example on my website where the format is wrong while the culture is fr-FR : 
http://antoinegriffard.com
"jeudi, octobre 8, 2015" should be "jeudi 8 octobre 2015"

Because the long date pattern in French is :  "dddd d MMMM yyyy" not "dddd, MMMM dd, yyyy"
see https://msdn.microsoft.com/en-us/library/system.globalization.datetimeformatinfo.longdatepattern(v=vs.110).aspx

**Comment by DanielStolt** [comment]
@agriffard do you have the `Orchard.Localization.DateTimeFormat` enabled?

**Comment by CSurieux** [comment]
@Bertrand: Which french grammar rule are you invoking, from which century. French owns hundred rules and is in permanent change since 1990. If Microsoft was aware of all this the Word Spellchecker would not be so catastrophic.
And we are not interested here in bringing perfect grammar rules, but fact is that someone would prefer to have french dates displayed with capitalized first letter of Months and days whatever the order of all the formatted date string.

**Comment by bleroy** [comment]
I'm aware of the evolution of the language, thank you very much, but I haven't found a single source claiming that the rule is to capitalize. It doesn't matter anyways as Daniel has given you ways to implement your deviation from the rule.

**Comment by agriffard** [comment]
@DanielStolt The "Date/Time Format Translation" feature was enabled but even if I disable it, the format is still incorrect. Same with "Localization" feature

**Comment by CSurieux** [comment]
@Bertrand : Deviation of the rule, you 're funny :)

**Comment by DanielStolt** [comment]
@agriffard In that case the format string provided by `System.Globalization.DateTimeFormatInfo" is not what you want. There's not much we can (or should) do about that in Orchard core?

**Comment by DanielStolt** [comment]
@agriffard I checked and there must be something wrong. The `LongDatePattern` returned by `System.Globalization.DateTimeFormatInfo` for "fr-FR" is `dddd d MMMM yyyy`, so if you disable the feature `Orchard.Localization.DateTimeFormat` this is the format you should be seeing.

Can you see anywhere in the code path where something might be overriding this?

**Comment by DanielStolt** [comment]
@agriffard Here is what I see on fresh site if I change to "fr-FR" culture:

![image](https://cloud.githubusercontent.com/assets/3889090/12278022/f5ef500a-b97e-11e5-89e8-7ce0d36dacc8.png)

So the only things I can think of are either you did not really disable the feature, or you have some other custom code in your site somewhere that overrides the formatting, or you are running on a really old version of Orchard.
