### ISSUE TITLE
Change: Vary by *

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6304]
I would like to change how orchard 1.9.1 sets the Vary request header form Vary * to Accept-Encoding.
Tried: in web.config and got response headers of both * and Accept-Encoding.
I serve gziped static files from AWS cloud front and to cache these files for users I need a Accept-Encoding Header
using
This somewhat works to give the header Accept-Encoding: gzip,deflate; 
```<add name="Accept-Encoding" value="gzip,deflate" />```
Still it does not cache these resources on users machines without the proper Vary header.
But when add
```<remove name="Vary" />```
```<add name="Vary" value="Accept-Encoding" />```
With
```<add name="Accept-Encoding" value="gzip,deflate" />```
Then I get a static file error on my sites and a Vary response header of
Vary: *,Accept-Encoding,Accept-Encoding

NO settings in Orchard cache to change Vary to anything it will stay Vary:* no matter what, and you cannot change it or fix it in the web config.

**Comment by jtkech** [comment]
@sebastienros, @DanielStolt 

I don't remember all details, so not sure it's exactly the same issue as @donaldboulton. But in `OutputCacheFilter.cs` i'm used not to comments this line:

    response.Cache.SetOmitVaryStar(true);

Because, not in all cases, but **the use of the vary:* header can disable all client caching**.

Just re-tried with a recent dev branch + vs2015 + issexpress + chrome, and maxAge > 0 in cache setting to allow client caching. Then, if the above line is commented, a page is cached only on **server side**, it loads in **10ms**, and in the response headers i can see:

    Vary: *

If the above line is not commented, then a page can be cached on **client side**, it loads in **1ms**, and in the response headers i can see:

    Vary: HOST,Accept-Encoding


Best

**Comment by jtkech** [comment]
as a side note, adding the following to the web.config seems to have the same effect.

    <system.web>
    ...
    ...
      <caching>
        <outputCache omitVaryStar="true"></outputCache>
      </caching>
    </system.web>

But maybe better to re-introduce `response.Cache.SetOmitVaryStar(true);`.

Best.

**Comment by donaldboulton** [comment]
Here is my caching profile now after change I get response headers of.
Status: HTTP/1.1 200 OK
Cache-Control:	public, max-age=259200	
Content-Type:	text/html; charset=utf-8	
Expires:	Mon, 25 Dec 2017 21:31:12 GMT	
ETag:	36025454	
**Vary:	*	**
Server:	Microsoft-IIS/8.5	
X-Generator:	Orchard	
X-AspNetMvc-Version:	5.2	
X-AspNet-Version:	4.0.30319	
allowKeepAlive:	true	
Access-Control-Allow-Origin:	http://donboulton.com	
Accept-Encoding:	gzip,deflate	
Date:	Tue, 02 Feb 2016 09:24:05 GMT	
Connection:	close	
Content-Length:	70902


My Web.Config cache settings do not change Vary* to anything.

Also added to OutputCacheFilter.cs

response.Cache.SetOmitVaryStar(true);

Web Config
`<caching> 
            <outputCacheSettings>
                <outputCacheProfiles>
                    <outputCache omitVaryStar="true" />
                    <add name="Cache1Month" duration="259200" varyByParam="Accept-Encoding" />
                    <add extension=".js" policy="CacheUntilChange" kernelCachePolicy="CacheUntilChange" location="Any" varyByHeaders="Accept-Encoding" />
                    <add extension=".css" policy="CacheUntilChange" kernelCachePolicy="CacheUntilChange" location="Any" varyByHeaders="Accept-Encoding" />
                    <add extension=".jpeg" policy="CacheForTimePeriod" kernelCachePolicy="CacheForTimePeriod" duration="7.00:00:00" varyByHeaders="Accept-Encoding" />                
                    <add extension=".jpg" policy="CacheForTimePeriod" kernelCachePolicy="CacheForTimePeriod" duration="7.00:00:00" varyByHeaders="Accept-Encoding" />                            
                    <add extension=".png" policy="CacheForTimePeriod" kernelCachePolicy="CacheForTimePeriod" duration="7.00:00:00" varyByHeaders="Accept-Encoding" />                
                    <add extension=".gif" policy="CacheForTimePeriod" kernelCachePolicy="CacheForTimePeriod" duration="7.00:00:00" varyByHeaders="Accept-Encoding" />   
                </outputCacheProfiles>
            </outputCacheSettings>           
        </caching>
    </system.web>`

from: http://www.asp.net/mvc/overview/older-versions-1/controllers-and-routing/improving-performance-with-output-caching-cs

but where can we add

The controller in Listing 7 illustrates how you can apply the Cache1Hour / Month profile to a controller action with the [OutputCache] attribute.

Listing 7 – Controllers\ProfileController.cs
`using System;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class ProfileController : Controller
    {
        `[OutputCache(CacheProfile="Cache1Month")]`
        public string Index()
        {
            return DateTime.Now.ToString("T");
        }
    }`

And what about this in Orchard web.config

<remove name="OutputCache" />

should it stay or go??

**Comment by DanielStolt** [comment]
Just so I can understand this, are we discussing static files or Orchard output cache here? 

For client-side caching purposes I think these two are very different.

For static files I see no problem using client-side caching. Orchard is not even involved in serving these files, they are served by IIS directly. Caching them can be configured in the `<system.webServer>` section in `Web.config` in folders where these files are served from. If changes need to be made to the `Web.config` files we have in the code base for Scripts and Styles folders to enable client-side caching, I'm all for it.

For Orchard output cache however I think it's less cut and dry.

1. There is a mechanism by which a content item gets evicted from the cache when it is edited from the admin UI. This would not propagate to the client.

2. Orchard output cache has mechanisms to vary the cache key by arbitrary circumstances which the client cannot evaluate. Third-party module can also extend this by adding anything they wish to the cache keys. This means that for a lot of cases, pages which will be rendered differently and cached differently on the server, will be mixed up if cached on the client.

I think for these reasons client-side caching is not enabled with `Orchard.OutputCache`.

But if you know what you're doing, and you have a website scenario in which you know that the cache only varies by URL for example, then perhaps there should be a way to enable client-side caching that does not involve a code change like the one @jtkech showed. I'm just concerned that a lot of people won't consider the possible ramifications, and just enable it because they think client-side caching sounds good.

**Comment by jtkech** [comment]
@DanielStolt 

Not sure with other content items with Orchard output cache. I totally understand what you mean, but, if i remember correctly, even you re-introduce in the code `response.Cache.SetOmitVaryStar(true);`, anyway you can avoid client caching (and other public caching) by setting `maxAge = 0` in the dashboard cache settings. Just re-tried it, seems to work.

For static files you're right, thanks. Didn't see that @donaldboulton was talking about static files. So, maybe the, in the folder related to these static files, the web.config (not the root one) is not up to date. @donaldboulton, check if it contains something like this: (you can copy paste with other web.config, e.g in some scripts / styles folders)

    <system.webServer>
      <staticContent>
        <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="7.00:00:00" />
      </staticContent>

      <handlers accessPolicy="Script,Read">
        
        <add name="StaticFile" path="*" verb="*" modules="StaticFileModule" preCondition="integratedMode" resourceType="File" requireAccess="Read" />
      </handlers>
    </system.webServer>

Best.

**Comment by donaldboulton** [comment]
Most all of my gzipped static files are or will be served from Cloud Front through AWS.
No matter what AWS cloud front's response headers say these files are served through my site so for the client doing round trips through my site as from home page to any other page, my gzipped files should be cached on there machine; by serving the compressed versions.
Vary* stops that.
For this to work I need a response header of Vary: accept-encoding, accept-language.
Vary* kills it.
As:
 http://tools.ietf.org/html/rfc7231#section-7.1.4 
clearly states
7.1.4.  Vary
   The "Vary" header field in a response describes what parts of a
   request message, aside from the method, Host header field, and
   request target, might influence the origin server's process for
   selecting and representing this response.  The value consists of
   either a single asterisk ("*") or a list of header field names
   (case-insensitive).

     Vary = "*" / 1#field-name

   A Vary field value of "*" signals that anything about the request
   might play a role in selecting the response representation, possibly
   including elements outside the message syntax (e.g., the client's
   network address).  A recipient will not be able to determine whether
   this response is appropriate for a later request without forwarding
   the request to the origin server.  A proxy MUST NOT generate a Vary
   field with a "*" value.

   A Vary field value consisting of a comma-separated list of names
   indicates that the named request header fields, known as the
   selecting header fields, might have a role in selecting the
   representation.  The potential selecting header fields are not
   limited to those defined by this specification.

   For example, a response that contains

     Vary: accept-encoding, accept-language

Check this out
https://www.fastly.com/blog/best-practices-for-using-the-vary-header

**Comment by jtkech** [comment]
@donaldboulton 

Oh, just seen you use Amazon Web Services, i first thought that AWS meant Azure Web Sites. Sorry to misunderstood your use case. I had a look on Amazon CloudFront doc, how they serve files through urls where you can use your own domain...

For the `<remove name="OutputCache" />` line, if i remember correctly, it's not to use the OutputCache httpmodule because of the orchard OutputCache where some outputCacheAttributes are still checked...

That said, i've seen your site and indeed you still have `Vary: *`. But in my tests i can remove this by adding in the web.config the lines i've proposed. But just seen that you have put `<outputCache omitVaryStar="true" />` under `<outputCacheProfiles>` under `<outputCacheSettings>`...

Please, try again, first by only adding the lines i've proposed where `<outputCache omitVaryStar="true" />` is just under `<caching>`, this in the `<system.web>` section.

Best

**Comment by jtkech** [comment]
@DanielStolt

Without disturbing you. Sorry, i don't remember all details around this, so it's as i understand right now.

I understand what you mean about cache invalidation mechanisms, but when we enable public cache with `maxAge > 0`, isn't it the same problem with other public proxy caches? (maybe also kernel cache). And as i remember not all browsers disable caching with `Vary: *`.

So, i thought we are allowing some "mixed up" for some duration (specified with maxAge) by using public caching (client cache included). Anyway, by setting `maxAge = 0` we still have the option to disable all public caching (client cache included).

So, as i understand, I think it could be usefull to re-introduce `response.Cache.SetOmitVaryStar(true);`

But maybe i miss something here.

Best.

**Comment by DanielStolt** [comment]
@jtkech You are not missing anything, and I think you make good points.

Yes, the same problem exists with public caches, reverse proxies, kernel cache etc.

It is true that having `MaxAge `as a separate setting allows users to set a lower cache duration for client-side and intermediary caching, which can, at least in part, be used to compensate for the lack of invalidation and key variation. One problem is that we can set the server-side duration per route, while there is only one global `MaxAge `setting - but perhaps that problem can be accepted.

So, a couple of suggestions:

- The default value of `MaxAge` for a new site should always be 0 (I'm not sure if that's already the case)
- Reintroduce `response.Cache.SetOmitVaryStar(true);` but conditionally, only if `MaxAge > 0`
- Add some explanatory text in the hint for `MaxAge` to explain the limitations of client-side and intermediary caching compared to server-side caching (lack of invalidation and limited key variation)

What do you think?

**Comment by jtkech** [comment]
@DanielStolt 

Looks good for me.

- Default value of `MaxAge` = default(int) = 0.
- You're right, it's the right place to use `SetOmitVaryStar(true)`.

It's as you want, but if i have to do a PR for this, in which branch, and please give me the text i have to use to replace the current explanatory text for `MaxAge`.

Best.

**Comment by DanielStolt** [comment]
@jtkech I think this one should go in `1.9.x`. It's a safe non-breaking change, but too late to get it into the 1.9.3 and 1.10 releases now.

For the hint text I would suggest:

> Specifies the duration (in seconds) content is allowed to be cached on the client, and on intermediaries such as proxy servers, CDNs or IIS kernel cache. When set to a non-zero value, a cache-control header with a max-age property will be added to responses.
NOTE: Responses cached on intermediaries or clients will not be invalidated when content is edited, and cannot participate in the full cache key variation supported in Orchard. Only activate this if you really know what you're doing, and consider setting it to a considerably lower value than the default cache duration.

In a subsequent PR targeting `dev` perhaps you could add separate configuration of the `s-maxage` header. :)

**Comment by donaldboulton** [comment]
Noticed one issue that database migrations did not occur for Orchard.OutputCache/DatabaseOutputCacheMigrations.cs
Never could get database caching to work and this is not in all my sites local or production.
Manually created the table and index so everything is working now by adding the table its index with the changes to wed config as below:
``<outputCache omitVaryStar=" true" />``
But when add
`<remove name="Vary" />`
`<add name="Vary" value="Accept-Encoding" />`
With
`<add name="Accept-Encoding" value="gzip,deflate" />`
 I get the proper response headers == finally.

Thanks for the help
