### ISSUE TITLE
After I created or saved some content type. The information do not show up, but after I click F5 to refresh the page, the message shows.

### ISSUE THREAD

**Issue by david0718** [OrchardCMS/Orchard#6326]
HI nice guys

I deployed Orchard 1.9.2 to a load balance environment.
After I created or saved some content type. The information do not show up, but after I click F5 to refresh the page, the message shows.

Messages like below:
Your "ContentType" has been created.
Your "ContentType" has been saved.

Do you have idea on this?

Thanks and best regards

David

**Comment by sfmskywalker** [comment]
Hi David, this is because content types are cached locally, so if your load balancer selects another node,to handle,the request after having created a content type, that node's cache will not know about the new or updated content type. You can enable Redis Signals to have the cache invalidated across nodes. I recommend doing a search on CodePlex for more information about this. Should you not find an existing thread, then please feel free to create one. I'm closing this issue here as there is nothing to do, codewise.

**Comment by david0718** [comment]
agree~ thanks
