### ISSUE TITLE
Having Problem after clone and lots of error for cshtml files when they are opened

### ISSUE THREAD

**Issue by mohammadyou** [OrchardCMS/Orchard#6351]
Hi, I'm a newbie. I forked the CMS and Cloned it in my root folder when I opened the solution and rebuilt it (VS2015) some system.web.helpers references didn't recognized so I deleted those that were indicated with yellow triangle and added them from _C:\Orchard\src\packages\Microsoft.AspNet.WebPages.3.2.3\lib\net45\System.Web.Helpers.dll _ patch
it worked(Compile Successfully without any error) but when I opened a .CSHtml file lots of errors showed up that says system.object is not defined and lots of other Errors. I deleted all bin folder and .user file but nothing changed. I checked Nuget and up to date the packages but no luck. I used resharper cleanup code but extra error come up after rebuilding the project. what am I missing here, how can I correctly clone the Orchard and access the cshtml without any error? 
Thanks

**Comment by rtpHarry** [comment]
I had this problem recently when I cloned the dev branch. If you're just looking to get started the master branch should be stable?

**Comment by mohammadyou** [comment]
Thanks rtpHarry for your response. I deleted dev branch and added the master, after cleaning the solution and rebuilding, it compiled successfully without needing to correct the references. but when I open some cshtml file (ie: Branding.cshtml under the TheThemeMachine), lots of errors show up that says  "The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)", Apparently something is wrong with  System.Runtime

**Comment by Xceno** [comment]
I have the same issue right now regardless of the branch. I'm pretty sure this is a VS bug as I see a lot of complaints right now about the stability of Intellisense in Razor-Views.
And I also have it with other non-Orchard projects.

**Comment by rtpHarry** [comment]
With the razor files I have seen problems on projects but I haven't figured out the exact cause. 

I'm using VS 2015 Community with a fresh branch of 1.9.2 and I don't get the problems with the views that come with Orchard but when I load in a 3rd party module it gets confused and most of the code has red squigglies under it.

I think the problem is that the references are out of date or something in the 3rd party modules.

Actually when I first load up the theme branding.cshtml as you say it all had squigglies for a while and then compiled in the background and they have all gone away now and I can get intellisense on `@WorkContext...` for example.

Orchard uses razor templates but it's not just plain old mvc, it uses its own View Engine in  `Orchard.MVC.ViewEngines.Razor`.

**Comment by sebastienros** [comment]
Works fine for me on 1.9.3, please reopen if you can repro.
