### ISSUE TITLE
Remove TitlePart from Template content type and make ShapePart.Name a persisted unique property

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/Orchard#6360]
Currently the TitlePart.Title is the name of the Template (Shape) but it is not unique. You can create two Templates with the same Title. In this case an exception is thrown on every pageload. 

Exception is thrown in Orchard.Template module in TemplateShapeBindingResolver class. The BuildShapeProcessors method tries to create a dictionary from the content item list where the ShapePart.Name is the key.

With this solution the part should implement ITitleAspect and Name would be the Title.

**Comment by Piedone** [comment]
This guy knows something. Trust him.

**Comment by sfmskywalker** [comment]
I've actually contemplated doing this when implementing this type, but decided to wait and see. I agree with Mark's proposal.

**Comment by sebastienros** [comment]
If the issue is to fix the unicity (because the word exists) check then we can still do that with the Title, we just need to add a driver for this check. We do that for other parts. I don't disagree with the change but it would be a breaking one (at least it would incur migrations/update) but if we can prevent it, let's just fix the issue.

**Comment by sfmskywalker** [comment]
That's true, the driver or handler could just add a model validation error.

**Comment by Piedone** [comment]
Since we won't have an 1.9.4 most possibly re-targeting this to 1.9.3.

**Comment by sebastienros** [comment]
We'll merge 1.10 into master. And rebase 1.9.x on top of master and rename it 1.10.x. Also merge it into dev.

**Comment by Piedone** [comment]
OK
