### ISSUE TITLE
add media item recent show nothing

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6396]
add media item recent show nothing after i just upload a image

**Comment by BenedekFarkas** [comment]
I can repro this on the 1.9.3 branch. When `/Admin/Orchard.MediaLibrary` loads, the recent media items are not shown, because no folder is selected/displayed by default in the Media Library navigation. If you click on "Recent", then the recent items will be displayed. I agree that the default behaviour should be to display recent items, when display the MediaLibrary (without a `folderPath` specified).

**Comment by BenedekFarkas** [comment]
Removing `viewModel.selectRecent();` (line 613 and 614 altogether) from `media-library.js` fixes both issues. I assume it's because displaying the selected/recent folder is already initialized (starting with line 437) and re-initializing it messes with it.

This will cause the `/Admin/Orchard.MediaLibrary` route (which is in the Admin menu) to automatically redirect to `/Admin/Orchard.MediaLibrary?folderPath=` that will display the recent media items. You can also go to `/Admin/Orchard.MediaLibrary?folderPath=test\test2` that will navigate to the `test2` folder and display its content.

@sebastienros do you approve the fix?

**Comment by BenedekFarkas** [comment]
TODO: check if this fix doesn't cause regression (see the fix for #6248).

**Comment by BenedekFarkas** [comment]
I tested the change taking #6248 into consideration and it works OK. The change only affects the client-side (so it fixes that the media items are not rendered, because the item grid is re-initialized), but doesn't affect the server-side logic that prevents users from renaming a folder they don't have permission for: If a user has `ManageOwnMedia` permission (but not `ManageMediaContent`), then they are restricted to only access the `Users\<username>` folder structure. If they attempt to edit (rename) a folder and edit the query string to reference a folder they don't have permission for then they'll still get a 403 same as before the suggested change.

**Comment by BenedekFarkas** [comment]
While testing this, I discovered another issue -> #6466.

**Comment by dcinzona** [comment]
Shouldn't the first call go to `RecentMediaItems` instead of `MediaItems`?  This is the API endpoint when clicking on the Recent folder after loading the media items view, however, the first API endpoint that is called is the `MediaItems` endpoint, causing the recent items to not appear.

**Comment by dcinzona** [comment]
This is actually caused because FolderPath is set to true (since it's being passed in as an empty string in the view).  This line here: https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Admin/Index.cshtml#L99 should use string.isNullOrWhiteSpace (because on initial load, it's "" by default, not null).  In fact, it will never be null.
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/AdminController.cs#L44
It defaults to "".

I've tested on my local and confirmed that changing the line
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Admin/Index.cshtml#L99
to `hasFolderPath: @(!string.IsNullOrWhiteSpace(viewModel.FolderPath) ? "true" : "false"),` resolves the issue for me on 1.10

**Comment by BenedekFarkas** [comment]
I agree (with a slight change):
`hasFolderPath: @(!string.IsNullOrEmpty(viewModel.FolderPath) ? "true" : "false")`
is the most straightforward fix.
