### ISSUE TITLE
1.10 Various modules reference Nuget packages from Orchard.Azure Solution

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#6403]
I'm not sure this is correct.  Should the Themes project be referencing a completely different solution's packages directory?  

Themes
https://github.com/OrchardCMS/Orchard/blob/1.10/src/Orchard.Web/Themes/Themes.csproj#L62-L85

Looks like this is also happening in a few other projects:

PublishLater
https://github.com/OrchardCMS/Orchard/blob/1.10/src/Orchard.Web/Modules/Orchard.PublishLater/Orchard.PublishLater.csproj#L54

TinyMce
https://github.com/OrchardCMS/Orchard/blob/1.10/src/Orchard.Web/Modules/TinyMce/TinyMce.csproj#L64-L82

Orchard.Resources
https://github.com/OrchardCMS/Orchard/blob/1.10/src/Orchard.Web/Modules/Orchard.Resources/Orchard.Resources.csproj#L52

**Comment by DanielStolt** [comment]
Yes, this is an issue I think. Not sure how this can be solved. As soon as you open the Azure solution, it will restore packages to a different solution folder and references might be re-hinted to that folder from projects in certain situations. The only solution I can think of is to re-arrange so that the Azure solution and the normal solution are in the same folder.

**Comment by dcinzona** [comment]
The azure solution references the same projects as the orchard.web solution, correct?  If that's the case, I agree that it should be resolved by moving the Orchard.Azure solution to the same directory as the orchard solution.  Is there any opposition to removing the Orchard.Azure solution altogether? i.e. Orchard as a cloud service is no longer officially supported and the recommended solution is to use Orchard as an Azure Web App?  Just a thought, not sure if it helps anything.

**Comment by DanielStolt** [comment]
I used to be in opposition of removing cloud service support, but I am no longer. :) Would not be too sad to see it go. @Piedone might have opinions on the matter though?

**Comment by Piedone** [comment]
Not really, we don't use the Azure solution either.

**Comment by dcinzona** [comment]
So should it be put to a vote or just removed? cc/ @sebastienros

**Comment by BenedekFarkas** [comment]
I don't know of any reason why one would run Orchard in a Cloud Service instead of a Web App, so if there's no one on the side of keeping it, it should be removed from 1.9.3 and 1.10 too.

**Comment by Piedone** [comment]
While I'd be glad to see any traces of Azure Cloud Services wiped out of Orchard I guess there are people using it, since it has been available for forever. If we remove it, what I'd wholeheartedly support, then we shouldn't do it on such short notice, but rather in one-two major releases later after hearing counter-arguments (and if hearing powerful ones, then not removing at all). This can be a total deal-breaker for some.

**Comment by BenedekFarkas** [comment]
tru dat
We could also provide a step-by-step migration guide, if necessary, although running Orchard in a Web App is not a big deal.

**Comment by dcinzona** [comment]
I think the issue has only come up in 1.10 because of the Nuget packages.  From my understanding (and in practice trying to migrate our current implementation to 1.10), 1.10 is a big change for Orchard. That could be where it starts, but it remains in 1.9.3.  Or maybe even doing it in 1.10.1 or 1.11
But then we need to resolve the issue of 1.10 building without the Azure solution requirement.

**Comment by DanielStolt** [comment]
The 1.10 and 1.9.3 releases are waaay to far along for such a drastic change. For 1.10 let's just fix the references by repointing them back to the regular solution folder (non-Azure).

We can start removing cloud service support from dev pretty much starting now I think. This would then be a 1.11 change, for which everyone has ample time to prepare.

**Comment by dcinzona** [comment]
True, good point.
