### ISSUE TITLE
Server Error 404 on Dynamic Form Submit with GET

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/Orchard#6417]
If the option GET is used, the form submits to /Orchard.DynamicForms/Form/Submit? which not exists and results in a 404 Not found.

**Comment by donaldboulton** [comment]
Which version of orchard is doing this?

**Comment by Flarescape** [comment]
1.9.2

**Comment by donaldboulton** [comment]
I never could get dynamic forms to work with 1.9.2 on production site and on localhost it installed but I got tired of several issues it had, so I used custom forms in 1.9.2.
Its a known issue of it not installing properly in 1.9.1 and 1.9.2, this issue is addressed at  
[https://github.com/OrchardCMS/Orchard/issues/6085](url)
It was fixed for 1.9.3 but 1.9.3 had to many other issues. So to 1.10 it installs fine and works have not used it much yet so ???

**Comment by Flarescape** [comment]
Everything else works fine for me with dynamic forms in 1.9.2

Let's wait till 1.10. ;)

**Comment by sebastienros** [comment]
By design, unless you have a specific reason to? Please share if so.
