### ISSUE TITLE
media item-- Recent --show nothing

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6490]
this time click left menu "Media", it is ok.
but 
1--click admin folder
 2--i choose pic from my computer and upload, 
3--then click "close".
Recent is highlight, but show nothing

**Comment by infofromca** [comment]
i should click Recent, then it is ok

**Comment by BenedekFarkas** [comment]
@sebastienros we should assign this to 1.9.3.

I can repro this (and this is different from the previous issue with loading Recent items).

Again, I would suggest to remove `viewModel.selectRecent();` at the end of `media-library.js`. This line was added in the commit to fix #6248, but it has nothing to do with that change, but it causes two issues by forcing the selection of Recent items:
- When you try to load a specific folder path, e.g. `Admin/Orchard.MediaLibrary?folderPath=test\test2.
- When you upload items, click on the `Close` button and the folder should be display to which the items were uploaded.

In both cases what happens is:
- Media Library page is loaded.
- We are in the correct folder and Media Items are retrieved through the API for the folder we are looking at.
- The items' placeholders are displayed for a short duration, but the script execution reaches the last line that forces the Recent items to be displayed.
- The method that runs looks at the viewModel and decides that there is no need to retrieve new items from the API (for the Recent items), because items are loaded in the previous API call.
- Result: Recent is selected, no items displayed.

Removing that line solves it for both cases and it doesn't cause any issues for other scenarios.

**Comment by sebastienros** [comment]
I think it is related to that change, I did it on purpose, and tried the bug that is was supposed to help fix. Maybe some new changes make it useless.
If you know the ultimate solution feel free to create the PR.

**Comment by BenedekFarkas** [comment]
Fixed the issue on the `1.9.3` branch.
