### ISSUE TITLE
SSL module is showing admin notification to all users on all pages

### ISSUE THREAD

**Issue by Xeevis** [OrchardCMS/Orchard#6494]
When Socure Sockets Layer module is enabled and not configured it will notify with message "You need to configure the SSL settings." ... This is clearly intended for administrators but is displayed to all users (including anonymous) on frontend.

```
public void OnActionExecuted(ActionExecutedContext filterContext) {
    var settings = _sslService.GetSettings();

    if (!settings.Enabled) {
        _orchardServices.Notifier.Warning(T("You need to configure the SSL settings."));
    }
}
```
I don't think this message is THAT important to have it displayed on all pages even for administrators, should probably appear only on administration for admins similarly to how "The SMTP settings need to be configured." message from **Orchard.Email** works.

**Comment by sebastienros** [comment]
It should always appear on the admin, and only on the admin side, there is an extension method for that (look at the SMTP settings) to check.

**Comment by MatteoPiovanelli-Laser** [comment]
Are there news on this issue? I see it's not solved on the Master branch.

**Comment by rtpHarry** [comment]
I've just taken a look, it seems like the two modules take a different approach but it should be a simple fix.

The SSL module just does the notice itself which is why its leaking out, but the email module uses an `INotificationProvider` which are automatically filtered to the admin panel.

I will submit a PR shortly.
