### ISSUE TITLE
Parts\Media.Actions.cshtml alternates in dedicated theme don't work

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6537]
Or I don't understand where to put it ?

in \Views nok
in \Views\Parts Nok
in \Views\Orchard.Medialibrary nok
and the bizarre ones
in \Views\Orchard.Medialibrary\Views nok
in in \Views\MyModule\ nok
in in \Views\MyModule\Mycontroller nok

what else ?

**Comment by bleroy** [comment]
That's an admin view, right? Admin themes require some additional work because of the way the admin theme is selected: https://github.com/OrchardCMS/Orchard/blob/df4f4234bd62c47c32eebdc87a57cd2ff06133a1/src/Orchard/UI/Admin/AdminThemeSelector.cs

If you want your theme to be an admin theme, you need it to include its own theme selector that selects it with a higher priority than 100.

**Comment by CSurieux** [comment]
No it is not an admin view, it is called by the display driver for Detail and Summary.

**Comment by bleroy** [comment]
That's irrelevant. It's only included in admin views by the default placement file of the module. If you are placing that shape into front-end views, you should have specified that in your bug report, as that would have eliminated the guesswork. What is the scenario for displaying administration buttons for media on the front-end? Won't the actions they point to fail anyway?

**Comment by CSurieux** [comment]
Administration buttons work on front-end as soon as you have the rights and it is tested upper in the pipeline. Authenticated and correct role.
The download button is Ok when user has ManageOwnMedia. The update button also.
My situation is a custom  document (manuscrit) which is displayed in Summary front-end in a list of documents for the actual user.
The normal display driver is called and generate the useful but a little 'faulty' Media.Action shape.

**Comment by bleroy** [comment]
It would probably be easier to add some action links to the main media shape rather than try to shoehorn a view that was designed for the admin into the front-end. Another solution is to add your own driver for the part, that adds a custom shape.
To get back to your original question however, can you confirm that the default template does get rendered?

**Comment by CSurieux** [comment]
I did nothing but trying to use an alternate to bootstrapize it but I discovered that my alternate, as already said is not called in my theme. But if I put it in the module where I have defined the custom document, it is called. Not ideal but it's an alternate.
I can confirm the default template get rendered in every call, I have not tried but a projection....

**Comment by bleroy** [comment]
Just to make sure: we aren't really talking about an alternate, but rather about a template override, right? If not, what is the alternate name?
I've verified on themes I own that both Themes/MyTheme/Views/Parts.ThePartName.cshtml and Themes/MyTheme/Views/Parts/ThePartName.cshtml are patterns that work. It also works with alternates.
Before I try that specific shape, can you share what version of Orchard you're on, and also the placement file for your theme?

**Comment by donaldboulton** [comment]
Name it.
Parts.Media.Actions.cshtml in you theme root Views folder
No Parts folder needed if using Orchard version 1.8.1+
Then register it in your theme project file... Theme.csproj

**Comment by CSurieux** [comment]
It is the first thing  I tried. No success. 
 Using dev, very similar to 1.10.

**Comment by bleroy** [comment]
Can we see your theme's placement file?

**Comment by sebastienros** [comment]
Please reopen with some repro steps.
