### ISSUE TITLE
Required fields should not have client side required attribute if a default value is set

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#6550]
If a default value is provided, and the field is left empty, we can't submit the page as it will be prevented by the browser. We should rely on server side validation in this case instead.

**Comment by jtkech** [comment]
Just seen this issue, i agree.

That's why here #6535 i said `Anyway, when Required the field can't be left empy because there is client validation...`. And i didn't implement default value when `Required`.

So here we also have to update some razor views and revisit some field handlers. I could do a PR for this but not immediately because of other works, but if it can wait.

Best.

**Comment by jtkech** [comment]
@sebastienros 

Just seen the recent merge plan. Maybe these series of PRs need to be re-targeted. If so, let me know in which branch.

I've done them separately because there are many use cases to test. And each field has its own singularities. So, maybe better to validate them step by step and independently.

Best
