### ISSUE TITLE
Merge plan

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#6583]
Here is the plan for branch merges once the release is out:
- __1.9.3__ merged into __1.10__
- __1.10__ merged into __master__
- __master__ merged into __dev__
- __1.10.x__ created out of __master__
- __1.9.x__ merged into __1.10.x__

- __1.9.3__ and __1.10__ tags are created 
- __1.9.x__, __1.9.3__, __1.10__ are then deleted

Note that __1.9.3__ is already merged in __1.10__ as of today.

Closed bugs assigned  to __dev__ will be reassigned to __1.10__
Closed bugs assigned  to __1.9.x__ will be reassigned to __1.9.3__
Open bugs assigned to __1.9.x__ will be reassigned to __1.10.x__

**Comment by DanielStolt** [comment]
One last step is missing: delete **1.9.x**.

I was going to question 1.9.3 -> 1.10 because it could introduce issues after all the testing of 1.10 we have done, but I realized as you point out, we have been merging 1.9.3 -> 1.10 regularly during the lock-down and we have been testing continuously, so this should not be an issue.

Looks solid!

**Comment by BenedekFarkas** [comment]
:+1:
