### ISSUE TITLE
[dev] Taxonomy Term picker in admin

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#6659]
I'm getting "can't acces the admin" with the Taxonomy Term picker in the admin.
it throws an error in TagsController.cs
`	        if (!_authorizer.Authorize(StandardPermissions.AccessAdminPanel)) {
		        throw new UnauthorizedAccessException("Can't access the admin");
	        }`

**Comment by jtkech** [comment]
Here, where i'm around this. In `admin-taxonomy-tags.js` there is an ajax call that target `TagsController` that is an `ApiController`. Then, for the permission checking, in `FormsAuthenticationService.GetAuthenticatedUser()`, `Request.IsAuthenticated` is false, the `User.Identity` is expected as a `FormsIdentity` but is a `GenericIdentity`...

I think it's because of the use of the http `ApiController` where authentication can't be done in the same way as with a mvc controller. Here, we would need to use, for example, some credential data in the request headers / cookies... Indeed, if i comment the permission checking, it works.

Maybe not worth, for this use case, to implement permissions through web api. Here, a simple fix would be to use a regular mvc controller, not an `ApiController`.

Best.

**Comment by jtkech** [comment]
It was simpler, `admin-taxonomy-tags.js` uses a relative url (because it depends on a base url) with an absolute virtual path `/api/taxonomies/tags`. It doesn't work if you use a virtual directory as `OrchardLocal` or, i think, if you use a tenant prefix.

If in the script i use the full url `http://localhost:30321/OrchardLoca/api/taxonomies/tags`, it works.

So, i could fix it by initializing a `baseUrl` variable in the razor view, and using it as an html data attribute. Then, using this data attribute in the script to construct the full url.

To initialize the baseUrl i use this:

    var baseUrl = Url.Content("~/") + WorkContext.Resolve<ShellSettings>().RequestUrlPrefix;

Note that i could resolve and use the full url by using this:

    var taxoTagsApiUrl = Url.HttpRouteUrl("", new { area = "Orchard.Taxonomies", controller = "Tags" });

but, here, there is the piority issue between an httproute descriptor (for the ApiController) and another route descriptor in the same module. Here, i need this PR #5823. If i aplly this PR, it works.

But, right now, we can use the solution with the baseUrl. I'll do a PR.

Best.
