### ISSUE TITLE
Manage Aliases, Home page Managed and Unmanaged.

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6667]
Orchard 1.10 latest web.zip shows home page as unmanaged and managed as `/ 	Contents/Item/Display/90` when adding my home page and deleting Welcome to Orchard stock home page.

**Comment by Skrypt** [comment]
On a fresh install I get : 

Unmanaged Alias : "/" that points to "Contents/Item/Display/9"
Managed Alias : "welcome-to-orchard" that points to "Content/Item/Display/9"

Not sure why the "/" alias has been kept unmanaged. If we change that alias it will break the homepage.

**Comment by edikaufmann** [comment]
Because#6669 is closed ... my comment here:
Mid of the night I realized that I probably made a boboo when migrating! I.e I only copied the Orchard.sdf and NOT the complete App_Data folder! 
I will go through the migration again and let you know.
Thanks but sorry for your time spent, ed

**Comment by Skrypt** [comment]
It's finebut we still need to make light on the reason why the "/" alias is unmanaged. If there is a reason; we need at least to document it.

**Comment by sfmskywalker** [comment]
The reason I left it as unmanaged is so that you can potentially assign the '/' alias to routes other than the content controller, such as a custom controller action you might want to become the homepage.

We could turn the '/' alias into a managed one if we provide some other means to a user to specify a custom controller to be the homepage.

On the other hand, we could consider this to be an edge case scenario, where one would have to provide a custom module to re-target the home page alias.

**Comment by Skrypt** [comment]
Maybe we could let people override managed Alias. Add a button in managed Alias to override any Alias.

**Comment by edikaufmann** [comment]
as said I did another 'migration' from scratch and found something interesting!

A) my 192 shows for the HomePage (HP) see -- > HP1.png
B) when transferring the 192 App_Data folder onto 110 I see --> HP2.png  I.e a ' /' and HP NOT ticked. 
C) because I want that as the HP I ticked  it and I see --> HP3.png I.e. NO / and  HP stays ticked!
PS: on my WebMatrix it still finds the HP HOWEVER when deployed the HP is NOT found see #6669.

My Conclusion: as soon as I tick HP and save, I loose the HP because the Permalink '/' is gone!
hope this does NOT confuse you more
but thanks to ALL for all your effort, ed 

![hp1](https://cloud.githubusercontent.com/assets/6625322/14100733/e94414ce-f58f-11e5-88e1-97585d009347.PNG)
![hp2](https://cloud.githubusercontent.com/assets/6625322/14100734/e945ca6c-f58f-11e5-9cd2-8f2a57d64611.PNG)
![hp3](https://cloud.githubusercontent.com/assets/6625322/14100735/e9464456-f58f-11e5-92cf-cf290d3bfbe3.PNG)

**Comment by donaldboulton** [comment]
1.10.1 will not let me change Un-Managed home page alias /Contents/Item/Display/9
Error
Cannot save alias home. It conflicts with existing one pointing to /Contents/Item/Display/9. Please change or delete the existing alias first. 

Tried to do what the message said and then no home page.

**Comment by sfmskywalker** [comment]
So you deleted the home page alias. What happens if you add it back? Even though the homepage is gone, you should still be able to access the admin via /admin.

**Comment by donaldboulton** [comment]
Will not accept / that's when I got the above error, had to use /home

The line The virtual path '/' maps to another application is because I ftp uploaded localhost and then changed the name of the site, done it many times the same way with a new database so how could I get the error, my server caching maybe because nothing was in the App_Data folder, but the home page alias is strange. 
On localhost I have to delete the alias and associated page as welcome to orchard, and then recreate it, cannot just change the name to home or whatever.
