### ISSUE TITLE
Scripts and styles referenced by layout snippets are emitted in the admin UI

### ISSUE THREAD

**Issue by DanielStolt** [OrchardCMS/Orchard#6672]
If a layout snippet file references one or more scripts or stylesheets (either via `Require()` or `Include()` those will end up being rendered in the snippet element editor in the admin UI.

Here is an example of when this happens - this particular snippet references stylesheets that are part of the theme and meant for the front-end, which change the styling of fieldsets and their labels:

![image](https://cloud.githubusercontent.com/assets/3889090/14096794/b0720b66-f56b-11e5-80c0-9ed6e7f669f0.png)

This is what it looks like in the rendered markup:

![image](https://cloud.githubusercontent.com/assets/3889090/14096800/bc3790b0-f56b-11e5-9129-db6722e3dda8.png)

**Comment by sebastienros** [comment]
Yet another reason not to render front-end shapes in the admin. I assume a simple solution is to render a placeholder instead of the snippet.

**Comment by sfmskywalker** [comment]
In this case it's not about rendering the snippet as it is on the fronted. In fact, a placeholder is being rendered already. But in order to discover the configurable snippet fields, the Razor view is executed, which causes the snippet field HTML helpers to execute, which invocations are being spied on.

One solution could be to execute the snippets in a child work context and replace the Resource Manager with a fake one so that no resources will be registered.

A completely separate approach would be to simply parse the Razor contents instead of executing it, but it's not as clever. I like clever ;)

**Comment by sebastienros** [comment]
How easy is it to use a child context?
What about having two razor files, one for configuration and one for rendering ? (not this topic)

**Comment by sfmskywalker** [comment]
If it works as I think it would, then should be straightforward, but I'll experiment.

Two Razor files would work, but I think the beauty of the parameterized snippets is that you don't have to separately configure the fields - it's all in one place and inline. But if it turns out it's technically not feasible, I guess we'd have to resort to other means like you suggest. But we'll see.

**Comment by DanielStolt** [comment]
I think the most elegant and "correct" solution is what you are suggesting, i.e. to do the rendering in an isolated child work context with a fake resource manager.

**Comment by sebastienros** [comment]
Go ;)

**Comment by sfmskywalker** [comment]
Unfortunately the child work context won't work, because the Razor base views access a WorkContext object that is initialized earlier to resolve the Resource Manager. This is due to the `ShapeTemplateBindingStrategy` singleton that injects the `IWorkContextAccessor` which is always resolved from a parent lifetime scope.

So at this point I'm thinking to resort to plain string-based parsing of the Razor view file (as is already done to determine if it has any SnippetFields in the first place so that the LayoutEditor knows if it needs to launch the element editor dialog). This approach would move us towards an approach where the fields are externally declared (although technically speaking they are stil declared inline).

Another, rather unorthodox approach, would be to change the ResourceManager to be "disabled". But then we're really hacking our way to a solution, so I probably shouldn't even have suggested it. ;)

It's sad to see the snippet fields' magic dissipate.

**Comment by sebastienros** [comment]
What about applying what I suggested today, as the only way to do snippets, but on a 1.11 as it would be a breaking change.
We could add the behavior in 1.10.x at any point as it would not be breaking and prepare for people to see the old way (current state) deprecated.

**Comment by sfmskywalker** [comment]
So a new harvester but one that reads the field descriptions from another file, or from the same Razor view but from a particular section? Can you please summarize what you proposed during today's meeting? I forgot the details :)

In any case, this new harvester could be added to 1.10.1 like you say, it would simply be a better version of the current one.

**Comment by sebastienros** [comment]
A snippet is two files, .Display.cshtml and .Editor.cshtml. With two different sets of helpers.

**Comment by sfmskywalker** [comment]
Ah right, yes that would work nicely.

**Comment by sfmskywalker** [comment]
Created a PR to fix this here: #6700
