### ISSUE TITLE
Nice Application, Bad Website CMS

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6703]
Show me a Orchard CMS since 1.9 that a .rss feed validates. Show me a Orchard Site that fully works as a CMS with search that is on point to content, feeds that validate,
 A sitemap that works; even the new one in 1.10 does nothing, just through the new Orchard.Sitemap in for bad measure??????
Blog Archives that have a accurate count. 
Caching destroys any .rss and .xml it has for over a years; Advanced sitemap stated that, "when  3 years ago".
Some of the standards of any CMS do not work in Orchard, I am beginning to think this is intentional.
Severely lacking proper perspective and focus or what this should be and you are working on.

**Comment by Skrypt** [comment]
I like the fact that you are opiniated. I'm sure that those problems you are facing can be fixed. You could easily ignore caching by setting the url's you don't want to be cached in the Cache settings. And you can also use feed tokens to alterate your rss feeds. For the sitemap, I think it's a contributed module wich is not part of the Core modules.

**Comment by donaldboulton** [comment]
The caching issue for .xml or .rss has been going on for years. I have set the url's to not be cache in cache settings = does not work, tried it every way, should be simple, but it does not work. have to set it in the web.config, then it works.
`<add extension=".xml" policy="DontCache" kernelCachePolicy="DontCache" />
                    <add extension=".rss" policy="DontCache" kernelCachePolicy="DontCache" />`
Sitemap is not part of the core; and why not.
Check out [iDeliverable](http://www.ideliverable.com/), why do they not have a fully functional CMS = good luck; they cannot even get it right = no search no .rss, no functioning count on Archives.
They don't even notice that Orchard Blog Archives .css and .js do nothing, two calls to the server for what = nothing.
Test it yourself on production site. And show me a Orchard CMS that works as a normal CMS should.
I will be wanting, as I have for years!

**Comment by Skrypt** [comment]
Github is mainly about to report issues and to propose enhancements for Orchard. And, like any other CMS out there, there is always room for improvements. If we can get to have constructive statements from this, I'll be happy to help. 

I believe that iDeliverable must also have clients to serve before pushing time on their own websites. And they contribute a lot to this community, so that makes less time to fix those 2 requests calls that must not cost them really much more with their Azure hosting. I've worked with Drupal, Wordpress and several other CMS's and this is always the same results in the end ... there is always customizations that needs to be done. And in this case, better having Orchard than nothing at all. Let's continue this chat on the forum or on Gitter ...

**Comment by bleroy** [comment]
If you are sincerely trying to help, don't insult the maintainers, and post separate issues for specific problems. One thing at a time and without counter-productive drama.

**Comment by donaldboulton** [comment]
My frustration is from the lack of response on these issues.
I have posted on the above issues several times on blog archive counts since codeplex and 1.9, with no response. Caching responses I received were not on point.
I fix these things myself by hand coding Sitemaps, Robots and feeds then adding to Orchard root and entries to web.config, but why should I have to.
The caching issues of .rss .xml and .txt has been going on for years and continues.
See http://orchardgalleryfe.cloudapp.net/List/Modules/Orchard.Module.WebAdvanced.Sitemap from 2013, stating to use the sitemap without it breaking from Orchard Caching you should turn off Caching, nothing has changed for the better since.
When I started using orchard about 1.6 all the above I mentioned worked correctly.
Truth through is foundation is usually insulting; with any truth there should be drama, its human nature, that is usually how we define life

**Comment by Skrypt** [comment]
> 
My frustration is from the lack of response on these issues. 
> 

Usually, when there is no answer, that's because it's a minor issue that has a low priority. And that means that it can be fixed by you or someone else. Here, you are putting your personal interests in front of your thoughts.

>
Truth through is foundation is usually insulting; with any truth there should be drama, its human nature, that is usually how we define life
>

There is always a way to tell the truth without insulting people. This is called having respect for other people and to have some social manners. Again, here, drama is avoidable, if there is drama that's because you are trying to push it. 

As for the caching module, there's been ongoing work on it and a lot of changes has been made. I don't know all the details. But since the Advanced Sitemap module is not part of Orchard Core the support on this module should be done by those who made it. Then, if you absolutely want to have this feature in Orchard you can vote here https://orchard.uservoice.com/forums/50435-general/suggestions/635685-sitemap. As you can see it has only 160 votes and other features have been requested more. That's the reason why it's not been taken care of as much as other things...

**Comment by donaldboulton** [comment]
Like I said, "Show ME", one Orchard site that functions like a normal CMS. A Sitemap, validated .rss and correct counts on Archives and maybe even counts on tags.
Went through most Show Orchard sites and no sitemaps or sitemap.xml no rss , no robots.txt.
A lot of pretty sites all the nice pictures with little or no internet or search positioning possibility's.
I am talking a website that has all the normal functions that Search engines can position and easy user navigation through Archives, Tags and descriptions of the site with Robots, Sitemaps.
Since these do not work in any Orchard site I can find; I must be mistaken that they matter.

**Comment by Skrypt** [comment]
https://www.halowaypoint.com/en-ca
I'm pretty sure they have this there.

**Comment by donaldboulton** [comment]
Yes nice, Generated by Orchard = not; but done by hand hard coding like my .xml or .rss. To do this is alot of work, which usually I do not mind. Try to do that with hundreds of posts, like halowaypoint did.
This is proof that a site index or map is needed and https://www.halowaypoint.com/sitemap.xml sitemap is a site index pointing to other sitemaps = nice learned something from your links.
Cool nice to know for correct positioning with google search = a index then maps.

**Comment by DanielStolt** [comment]
@donaldboulton I actually do agree with you on the actual point, i.e. that the **quality** of Orchard is dissatisfying. It's architecture and functionality are really good I think, but things like stability, code quality, documentation really are not. As volunteer developers we have a tendency to focus on what we think is fun - unfortunately, testing, getting the details right and documenting what we do don't fall into that category for most.

I'm sorry to hear you are feeling like the maintainers are unresponsive when you raise these issues. But if I may be so bold, I think this might be due to the way you express them - your posts IMO are often kind of garbled, filled with a mix of a variety of different points, poorly written and thus difficult to read and decipher, while still managing to somehow convey a sort of bitter contempt for the product and its developers. I think this might in some cases discourage people from picking up the valid points and issues buried within.

If you made more of an effort to write more clearly and contextually and to the point, went a little lighter on the sarcasm and non-constructive criticism, and perhaps spent a few seconds on punctuation and complete sentences, I think you will see more engagement.

**Comment by donaldboulton** [comment]
Lets talk about specificity, which post; and where is it garbled and not on point? This thread maybe! Who is being vague?
In the last several months I have pointed out many things that got attention and were fixed. I did not do a pull request and others always get the credit. Its easy for me to see the fun you are having paying attention to Orchard Gitter chat, children please.
Since 1.9 lots of features that worked before do not work now. I guess its not fun to test what you build, which is very evident, "mostly with 1.10".
In the past I just used orchard and it worked, nothing to say. Now lots of things need to be fixed to make it work. Is that simple enough.

**Comment by Skrypt** [comment]
And this is why we suggest with PR's that we should implement specflow tests. If contributors are not doing it. We can't force them. Maybe we should work on a curated list of unit and functional tests.
