### ISSUE TITLE
YAMLDotNet spans in every published module since this thing added

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6778]
Is it normal, why adding it ? Confused on the process to add external extensions in Orchard.

**Comment by sfmskywalker** [comment]
What do you mean by "spans in every published module"?

This NuGet package was recently added to implement a feature and fix an issue.

**Comment by CSurieux** [comment]
It was copied in the been folder of every published module.
But I now think it was a border effect of vs update 2 recent installation and some Google API update with portable library code.
I close this. 
But why using this YAMLDotNet extension, it is another burden to support. I am not uptodate on which benefit it brings. Isn't Json ok ?

**Comment by sfmskywalker** [comment]
Ah ok.

The YAML parser was added to fix the following issue: #6672
To summarize, in order to fix that issue we need an additional "manifest" file to describe a snippet. This manifest file is optional, and only needed if you want to be able to provide user-configurable fields to the CMS user. In Orchard 2, we would have gone with the JSON format like you suggested, but in Orchard 1, YAML is more consistent for this type of file. Module and theme manifests also use the YAML syntax.

**Comment by CSurieux** [comment]
Ok, thanks. Personnaly I use only json now.

**Comment by sebastienros** [comment]
To be consistent we are still using YAML, in ORchard2 everything YAML will become json.

**Comment by bleroy** [comment]
Well, JSON has issues if you start using it for human-written documents. There are things like human json, but it's less standard and less widely supported. Would be fine for stuff that won't move from the server, such as config files, but wouldn't work for anything that needs to cross app or machine boundaries.

**Comment by sebastienros** [comment]
The fact we can't write comments is killing me. Creating fake property to old it is so ugly.
