### ISSUE TITLE
Localization Module don't provide a proper culture selector for front-end

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#6793]
Current Localization module provides a culture selector shape (FrontEndCultureSelector) for front-end that allows user to change to a different culture but it always redirects user to the home page instead of redirecting you to the culture version of the current page.
There is an alternative for pages with LocalizationPart that allows you to show links for the different cultures for which that page is available.
Problem is I have dynamic forms without LocalizationPart using a visibility rule based on the user language to decide which fields to show. 
Another problem of current FrontEndCultureSelector is unexpectedly it forces you to use LocalizationPart in your home page. Furthermore, any content you get through Ajax won't be localized because by default cookie by default it is not used, you need to customize it.
In a site with some pages with LocalizationPart and other without it but with different appearance depending on the language problems arise for usability. The point is FrontEndCultureSelector and LocalizationPart shape doesn't provide a consistent way for changing culture. One redirects the user to the home page, and the other is only available sometimes.

**Comment by jersiovic** [comment]
Old Orchard Content picker provided an homogeneous way of navigating between culture  https://orchardcontentpicker.codeplex.com/
I have rescued a part of its code with modifications to provide a new shape in Orchard Localization Module that provides an homogeneous way of navigating between cultures. The new shape is UserCultureSelector.cshtml and it is based in a controller that works with routes and stores culture in  a cookie using CookieCultureSelector like this module does for admin pages.
I send a PR to hear your comments

**Comment by sebastienros** [comment]
@Jetski5822 to comment

**Comment by Skrypt** [comment]
The FrontEndCultureSelector currently uses the LocalizationPart and does'nt rely on the cookie because on the front end we need to be able to set a page favorite in a browser and be able to get back that page in the right culture. Someone could delete it's cookies and then would get that page in french if the default website culture would be french. Thus, I made the Culture Route Patterns to be able to have prefixes on url's per content types. Wich is also better for SEO concerns. Remember also that a crawler robot will never login into Orchard.

I presume that this dynamic form would have a url for any culture. e.g : /my-dynamic-form. So on server side this page would be considered like having the default website culture.

I need to think more about it.

**Comment by Skrypt** [comment]
For the Layout module we could use this technique. JSON Web Tokens.
https://jwt.io/
We could encode the user and everything related to it this way. This would be encoded and secure.

**Comment by neTp9c** [comment]
I think it is typically to use different domain for different culture instead of URL prefix. 
At least i do like that very often.

example 1:

  * domain.ru and domain.ru/login - for Russian locale
  * domain.com and domain.com/login - for English locale

example 2

  * domain.net - for main localization
  * en.domain.net - for another localization

In that case the different locale pages have the same relative URLs (at least, end users will thinks so). But on the server side they stay distinguishable. And that approach will be OK for crawler robots.

It will be good if this will be available out of the box.

**Comment by MatteoPiovanelli** [comment]
found this while opening another issue. We have a culturePicker module in our open source stuff:
https://github.com/LaserSrl/Laser.Orchard.Platform
We have been using it for a while, and tinkering with it. I think it was originally from the gallery, but that is from before my time.

**Comment by MatteoPiovanelli** [comment]
Our culturepicker module is opensource (has been for a while, but I only just remembered about this issue)

https://github.com/LaserSrl/Laser.Orchard.Platform/tree/master/src/Modules/Laser.Orchard.CulturePicker

**Comment by aipetryakov** [comment]
May be helpful, you can reach

- cross-domain localization
- page to page localization redirect 

by three modules:

- https://github.com/MainBit/MainBit.Utility
- https://github.com/MainBit/MainBit.Alias
- https://github.com/MainBit/MainBit.Localization

this modules are used on http://mainbit.com

**Comment by BenedekFarkas** [comment]
@MatteoPiovanelli-Laser I tested the current dev branch to make sure I understand where we're starting from (mostly because this issue and the associated PR is old) and you can render the FrontEndCultureSelector with a Shape Element in a Layout Widget. If the currently displayed content item has translations, you can switch to those, so that's great.

Is there a way in the current Orchard dev code (without third-party extensions) to select a culture that is "sticky", so content is always displayed with that selected culture (even if I open a URL that points to a content item with a different culture) with a fallback to the site culture?

**Comment by sebastienros** [comment]
Even in OC we don't do "sticky" cultures. We redirect to the corresponding item, but then if you click on another language then it load this language. Otherwise it would mean to change the content item controller, or intercept it in a middleware ... too complex.

**Comment by BenedekFarkas** [comment]
We did this kind of redirect with ContentHandlers for a few clients before, not a big deal, really.

**Comment by BenedekFarkas** [comment]
Closed by #8784.
