### ISSUE TITLE
Layout styling conflict

### ISSUE THREAD

**Issue by ActivePHOENiX** [OrchardCMS/Orchard#6804]
There are conflicts between layout css styling and the front end theme styles, specially if the front them is composed with the help of Bootstrap styling framework.
As I debugged a bit around the issue, its because the layout output has its own container element which pushes its styling over theme style.

has anybody else came around this issue?

**Comment by sfmskywalker** [comment]
Yes, this is by design so that it works out of box with the default theme. If you use a custom theme with Bootstrap, you're supposed to override certain element shapes depending on your particular requirements. Some more information can be found here: http://www.ideliverable.com/blog/orchard-layouts However it is slightly inaccurate: you no longer need to override Parts.Layout.cshtml because TheThemeMachine now includes the custom-grid.css.
