### ISSUE TITLE
Error in import media

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#6894]
When i import media i get this error!

![untitled](https://cloud.githubusercontent.com/assets/13555275/15239592/1935e7de-18f9-11e6-8406-00dd24c0851a.jpg)

**Comment by sfmskywalker** [comment]
Maybe a browser cache issue / try and clear the browser cache?

**Comment by asemandeveloper** [comment]
Yes, i clear the browser cache. In Chrome and Firefox i get this error!

**Comment by infofromca** [comment]
![after-close](https://cloud.githubusercontent.com/assets/297675/15375306/55cd5890-1d1c-11e6-8af4-16d2152c76c5.png)

 after i clike the item , it can go thru, but strange for the gray and progress bar.

**Comment by sebastienros** [comment]
Crap, @BenedekFarkas you know what it is, I do too.

@infofromca you should be able to change the settings on your browser to not show javascript errors. It must a development setting you have enabled. But there is definitely an issue in the javascript.

**Comment by infofromca** [comment]
only for canary, ff is ok

**Comment by rtpHarry** [comment]
I reported this a few weeks back in more detail but it seems I wasn't paying attention and I added it to an existing issue instead of starting a new one!

https://github.com/OrchardCMS/Orchard/issues/6756#issuecomment-213580336

Anyway it has some more details in that link. For me the problem only happens when the file has just been uploaded. Leaving the page and returning to it makes everything work fine.
