### ISSUE TITLE
Investigate default FcnMode

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#6942]
We need to look at the impact of applying `<httpRuntime fcnMode="Single" />` by default

c.f. http://shazwazza.com/post/all-about-aspnet-file-change-notification-fcn/

**Comment by sebastienros** [comment]
At least on production.

**Comment by rasseru08** [comment]
I have repeated the test with an empty 1.10.1 demo site.   Just hitting the opening page the creates about 400 files monitors.   If you click around the admin section the number quickly jumps to almost 800.   After adding the "fcnMode=Single"  to the web.config the count always stayed a 5.     

Another article about about this problem can be seen on a DNN site  [http://www.dnnsoftware.com/community-blog/cid/154980/aspnet-file-change-notifications-and-dnn](http://www.dnnsoftware.com/community-blog/cid/154980/aspnet-file-change-notifications-and-dnn)

**Comment by carlwoodhouse** [comment]
It seem's to me that certainly in environments like aw with a shared file system between instances enabling this would be hugely beneficial.

Can you for-see any implications at all @sebastienros ? as we are going to look into setting this to single or disabled.

**Comment by sebastienros** [comment]
Ping!

Just to resurrect this discussion. I will try it on one of my apps to see if there is any impact.

**Comment by carlwoodhouse** [comment]
I will double check but I have a feeling we've been running this in production for 7months lol

**Comment by carlwoodhouse** [comment]
ah we've actually been running with it disabled for 7 months rather then single

**Comment by sebastienros** [comment]
I'd suggest to have <httpRuntime fcnMode="Single" /> by default then, even on debug/development.
And document the other recommended option `Disabled` for performance reasons and also for a website not to restart when a configuration file is changed.

**Comment by Piedone** [comment]
I'm taking on this issue. On a vanilla Orchard site from the dev branch set up with the Default recipe it's actually more than 3300 file watchers; if there are more custom modules and themes then this goes up dramatically (just opening the lombiq.com homepage, which is not particularly complex, makes this go over 5600).

Any other long-term experiences @carlwoodhouse ? Is there any reason you'd advise against switching to Default?

I think for local development we should just keep the default, but change this config for the Release build target. I'm not sure on Single vs Disabled though: Single could be possibly overloaded on extremely large applications or with a lot of tenants (since for every tenant we have at least one additional directory and a couple of files).

There are certain files that need to be watched in a production scenario apart from Web.config (which is watched even in Disabled mode) still:

- App_Data\hrestart.txt
- refresh.html
- bin\HostRestart

We can possibly use the [location element](https://support.microsoft.com/en-us/help/815174/how-to-make-application-and-directory-specific-configuration-settings) to restrict the file watchers to just these, however, I didn't find a way to do that: you can only use this for paths in the URL. Otherwise we could have the config as Disabled in the root Web.config but override it in the App_Data folder.

**Comment by carlwoodhouse** [comment]
Default should be fine I imagine ... tho I’ve checked and we still run it as disabled on patient; and have since the discussion when this issue was opened (we don’t have dynamic extension loading etc tho)

**Comment by Piedone** [comment]
I see, thanks. I'm testing this now with one of our production apps ([DotNest](https://dotnest.com), but in a test environment yet) and to be honest I don't see a noticeable performance difference (we've just run with default in the last five or something years without issues). Will come back with more results.

**Comment by carlwoodhouse** [comment]
I mean it depends on a lot of other factors to how much gain you’ll see; if any .. 

How media is configured, how cache is configured, number of modules, etc etc

We mostly did it as we where running on app services which share the file system across instances and occasionally fcn’s Where occurring for no good reason and restarting all the instances (network latency to the drives having a weird effect on fcn)

(Similar to this https://www.rahulpnath.com/blog/azure-web-restarting-automatically-due-to-overwhelming-change-notification/)

As far as I can remember anyway :) I’ve not really worked on any of o1 projects for about a year heh

**Comment by Piedone** [comment]
Media for us is in Blob Storage, so that can be a pretty big factor, as no local Media folder (we're using App Services too). I'll see what I'll find. Foremost I'm interested whether there is any negative impact of having a Single or Disabled default, or the most issue you can get is that there's no measurable advantage.

**Comment by Piedone** [comment]
I did some measurements with the DotNest app having around 5000 tenants running on an Azure App Service. The deployed app is a precompiled build and uses Azure Blob Storage instead of a local Media folder. It also stores several of the tenants' App_Data files not locally (but rather in the DB and again in Blob Storage), most notable Lucene index and settings files; similarly, Settings.txt files are not present. All in all the app's folder only contains the compiled binaries and static source files, and temporary cache files.

With this app I couldn't consistently measure a difference in memory usage and thread count. Aggregated CPU usage seems to be slightly lower with default settings actually.

So this doesn't help too much with this particular app. The amount of file system watchers is indeed much lower with more app files but I don't have an actual production site with a local Media folder where this could have a significant impact.

I'd suggest just documenting this and having the Single and Default configs as suggestions for certain hosting scenarios. It's certainly not beneficial for local development (where you want dynamic C# and Razor compilation), but it can be for production deployments. While during my brief and not at all exhaustive tests I couldn't find any issues even with Disabled I'm not sure if indeed there aren't any issues. Carl has more experience here, if we're feeling adventurous we could just add Single as the Release mode default, but I'm not sure about that without some exhaustive testing (with Disabled I don't see how we wouldn't eventually bump into issues due to the above-mentioned files not being watched).

**Comment by Piedone** [comment]
What we discussed on the meeting: Go with Single as the default value in Release mode, document the others.
