### ISSUE TITLE
Re-enabling dynamic forms after deleting Content Type Form doesn't recreate the Form content type

### ISSUE THREAD

**Issue by petermorlion** [OrchardCMS/Orchard#6956]
I had an issue with a Form and thought I might start from scratch. So I disabled the Dynamic Forms module. I saw the Form content type was still there, so I deleted that too. Then I enabled Dynamic Forms again, but the Form content type wasn't recreated...

So I'd like to file this as a bug, but also ask if there's a way I can recreated the Form content type (short of doing it manually).

**Comment by sfmskywalker** [comment]
This is not so much a bug with Dynamic Forms, or with Orchard for that matter, since content types are created by migrations that execute only once, and modules don't remove their settings and data automatically (this is a [deliberate decision](https://github.com/OrchardCMS/Orchard/issues/3823)).

That being said, maybe it's not such a bad idea to have each module that provides content types to the system come with a recipe that can re-create those types on demand.

For now I recommend creating the Form content type manually, or exporting and importing its definition from another Orchard installation. I attached a recipe for your convenience that you can simply import (make sure you enabled the Import/Export feature)
[export.zip](https://github.com/OrchardCMS/Orchard/files/300631/export.zip)

.

**Comment by petermorlion** [comment]
Awesome, thanks. The decision makes sense now that I read more about it. But indeed, a recipe to recreate would be interesting.
