### ISSUE TITLE
Cloud Service Support 1.10.x

### ISSUE THREAD

**Issue by grapto** [OrchardCMS/Orchard#6972]
What happened to Orchard.Azure Solution and how are we going to deploy to an Azure Cloud Service?

**Comment by carlwoodhouse** [comment]
It's getting removed i believe in 1.11, mostly because now there isn't any real reason to not use app services instead.

https://github.com/OrchardCMS/Orchard/issues/6403 - has more details.

Personally we are just going through the work of migrating our site to app services, as like you we've always used cloud services.

**Comment by grapto** [comment]
Do you know if I can find a guide of how to deploy orchard to an App Service? All I can find is information of how to deploy up to 1.9.3
Also, now that cloud services are not supported any more (Didn't see any roadmap on that) how are we going to define start up tasks? Not to mention that we gonna miss the ability to remote access our servers.

**Comment by carlwoodhouse** [comment]
Deploying as an app service is basically MsDeploy, or you can deploy straight from github which is built into azure and the orchard solution supports it through the .deployment file i the source route.

Here is some info on it - http://docs.orchardproject.net/en/latest/Documentation/Deploying-Orchard-to-Windows-Azure/#deploying-orchard-to-a-windows-azure-web-site

Startup tasks i have no idea, depends what they are i guess? the only ones we had were to apply security fixes that already exist on app services. 

Remote access i understand, and i used to be apprehensive too ... but really, app services supports all the data you would want through the azure portal (event log streaming, etc etc)

I wasn't totally sold on the cloudservices retirement either for a while, but having used it iin our test and qa enviornments for a few months now, you really dont miss anything from cloud services! (might not be true for you ....)

All that been said, just because Orchard is supposed to be officially dropping the support - no reason you couldn't maintain your own Azure sln ;)

**Comment by grapto** [comment]
Thanks a lot for the information, I will test a new deployment as an app service. It looks very promising although I believe that cloud services are way more flexible for Web Applications.
As a final note, I tried to maintain an Azure solution for version 1.10.x but I could not find a way to make the dependencies work together.

**Comment by sebastienros** [comment]
Closing as it seems to be answered.
