### ISSUE TITLE
One question and  a sincere concern, Does it matter to you?

### ISSUE THREAD

**Issue by ActivePHOENiX** [OrchardCMS/Orchard#6985]
Sorry Nothing.

**Comment by agriffard** [comment]
You are free to share your concerns. It matters to me if you are worried about the project. 

I know it can be sometimes frustrating when you have some expectations that are not fulfilled or don't understand some choices that are made.

**Comment by Skrypt** [comment]
The new admin theme was first introduced as an override of the actual admin theme. It's been refused in that form since it was more like a hack. I'm actually working on client websites "wich I can't neglect" that's mainly why the project has not moved forward much lately. The rewrite of the modules has been discussed with the core members and we all agreed about it. There is 2 different things to considerate here. If we want to have an admin theme based on Bootstrap and to make it easier for people out there to be able to make mods easily we need to use the Bootstrap class names. There is also the fact that those Bootstrap components have their own HTML markup, wich means, that if we want to have something that is extensible enough to be modified with a Bootswatch file we need to also have better HTML semantics. So, in the end a rewrite of the entire views is needed. Also, the reason why it takes so much time to deliver is mainly because I don't want to push something that is not finished yet. We still need to make the new admin theme to be RTL, we need to test if the older modules views will still display adequately. And on top of that, I think most of the current admin views needs to be fine tuned to work better with mobile devices. Wich means that adding Bootstrap is only 50% of the work.

It is true that right now the focus of the core dev's are on Orchard 2. I think it is right where they should be. And from what I've heard, because I'm reading what @sebastienros does daily, they are taking all the major pain points and are going to make it better for 02. Though, there's nothing preventing contributors to still work on 01 like we all used to. Like I used to say on the old forum.

For the Gallery, I need to discuss about some ideas that he probably already knows with @sebastienros. But again, I think we miss time and hands if you want this here and now.

And yes, we are developpers, so, let's find solutions then.

**Comment by Skrypt** [comment]
And thanks to @agriffard who's giving me a hand on this :+1:

**Comment by ActivePHOENiX** [comment]
Thank you for the response you gave, I thought my wordings and concern may not give a good vibe or may not be effective or positive so I decided to remove it and just wait, just like I have done for past few years and see.

**Comment by Jetski5822** [comment]
Hey there all!! - So my two cents (I read the original article in my email box :))

So the first thing to remember is that Orchard is massively community driven, people like @Piedone @sfmskywalker @DanielStolt all use this in their day to day jobs, even I do sometimes, but what that means is that they will normally maintain the version that they are working on, which I think is 1.x at the moment, the momentum may have slowed down slightly on commits, but hey, that's not a bad thing - also bare in mind, these guys push to banches so its work taking a look at the project forks. I know Lombiq are mainly creating modules these days (correct me if I am wrong boys), and Daniel and Sipke are working hard on internal projects, hense why we see crazy bug fixes from these chaps.

The focus of myself, @sebastienros and a few others is Orchard 2.0, mainly because I am interested in it, and don't use Orchard day to day at the moment.

Which video from Scott Hansellman were you referring to btw?

So, the migration from O1 to O2... Yes we started from scratch, however... that's only 'kinda' true. We have taken a lot of the concepts and stuff you are used to and just ported it across, You still have IDependency! eek. We are changing interfaces and contracts, introduction to Async and Await is also important, remember that wasent around during O1 early days and to put that in the O1 now would be hard work. Also making sure it works on Windows, OSX, and Linux.... requires some thought. I know half the guys working on O2 develop solely in Linux or on a Mac. Exciting stuff!!! And we have also talked about migration from one system to another, that story hasent been penned fully, but conversations have started, maybe  I should open a github issue for it so we can track it in the wild. We have a roadmap of the initial release, so all good there too.

The admin thats being done for O1 should be able to go straight over to O2, with some tweaks for tag helper.

O2 Performance will knock your socks off.... (If it doesnt, its probably because you werent wearing socks, so please put socks on first, and they prepare for them to be knocked off)

RE Docs: Yes, this is a problem when a project is driven by the community, but @agriffard took on the new docs site, and thats now live I believe! (might be wrong)

RE Orchard Project Site: Steve Taylor has started to look at this, not sure how far he has got and I know a bunch of people have tried, but Steve looks like hes started all the way from the requirements stage which looks interesting, if you need links let me know.

Overall - I know it seems that we have ramped down because code commits dont look as often, but with any project, the focus isent always code!

Nick!
