### ISSUE TITLE
Problem with getting SiteSettings from the OwinMiddlewares

### ISSUE THREAD

**Issue by konstrui** [OrchardCMS/Orchard#6991]
We've created an issue on codeplex, but since it seems to be a 'bug' after 1.9.2, I'm posting this here on Github with a link to the original post.

Anyone who has some ideas about this issue?
http://orchard.codeplex.com/discussions/655411#post1476792

**Comment by konstrui** [comment]
Anyone? Seems to be related to Autofac I guess...

**Comment by Piedone** [comment]
Long story short: you can't use directly injected dependencies in the middleware's delegate but you need to access the ambient `WorkContext`.

This is not a bug, though something that's not trivial to pinpoint: Owin middlewares are self-contained delegates that will run on a request. The `IOwinMiddlewareProvider` they are created in is only their factory.

This means that the middlewares should run independently of their provider, i.e. they also need to use a work context scope independent of that of their provider's.

For an example see: https://orcharddojo.net/blog/writing-an-orchard-owin-middleware

**Comment by konstrui** [comment]
We're able to do it like this right now:

```
using (var scope = _workContextAccessor.CreateWorkContextScope()) {
   var settings = scope.Resolve<ISiteService>().GetSiteSettings();
}
```

So, indeed using a scope.

And I could get my specific settings like this:

```
var workContext = _workContextAccessor.GetContext();
if (workContext != null) return;

// If null, create a new WorkContextScope
var workContextScope = _workContextAccessor.CreateWorkContextScope();
workContext = workContextScope.WorkContext;

var wsFederationSettings = workContext.CurrentSite.As<WsFederationSettingsPart>();
```

Any problem with these solutions you think?

**Comment by Piedone** [comment]
You don't need to create a new WC as there should be one at that point already (i.e. you can always use `_workContextAccessor.GetContext();` or inject `Work<T>` types), but otherwise good. If I'm mistaken and you do see the WC being null for some reason then I'd think it's a bug and please come back here to elaborate.

**Comment by konstrui** [comment]
Yeah, this line:

`_workContextAccessor.GetContext()`

is giving me NULL.

The same counts for every interface I'm injecting through the constructor, e.g.:

```
IAuthenticationService 
IContentManager 
```

They are throwing an exception during initializing of the component.

**Comment by Piedone** [comment]
Where exactly are you calling `GetContext()`? Because it should happen inside the `app` delegate, not outside of it anywhere in the provider.

**Comment by konstrui** [comment]
Yes, that is what I do:

```
public IEnumerable<OwinMiddlewareRegistration> GetOwinMiddlewares()
        {
            return new[]
            {
                new OwinMiddlewareRegistration
                {
                    Priority = "9",
                    Configure = app => {

                        var workContext = _workContextAccessor.GetContext();
                        if (workContext != null) return;


                        using (var scope = _workContextAccessor.CreateWorkContextScope()) {
                            var siteSettings = scope.Resolve<ISiteService>().GetSiteSettings();
                        }
```

And it returns null. (version 1.10.1)

**Comment by Piedone** [comment]
Hmm, that's strange, I don't know why this happens as it shouldn't....

**Comment by sfmskywalker** [comment]
I can confirm that it indeed returns null. The reason is that the OWIN middleware components are invoked outside the scope of a `WorkContectScope`. If at this time there was actually an ambient HttpContext.Current available, it would be fine. However, no such HTTP context is available this early in the pipeline (or perhaps because the code runs on a different thread).

So it seems that either each individual OWIN middleware provider needs to create a work context scope themselves as Daniel is doing, or we need to update the `Activate` method on the `DefaultOrchardShell` to wrap the middle ware invocations with an actual work context scope, as is also done a few lines below in that method:

![image](https://cloud.githubusercontent.com/assets/938393/18914706/8bc455fe-858e-11e6-9344-ad5059a67c58.png)

**Comment by sfmskywalker** [comment]
I just created PR #7161 that implements what I propose above. Using this, `IHttpContextAccessor.GetContext()` will return a non-null `IWorkContextScope` (being an instance of `CallContextScopeImplementation` since there is no real HttpContext when this executes.)

**Comment by konstrui** [comment]
Thanks for the follow up, Sipke!
