### ISSUE TITLE
It is awkward to add a sub menu item to an existing menu item in the admin menu

### ISSUE THREAD

**Issue by Hazzamanic** [OrchardCMS/Orchard#7049]
When the admin menu is rendered it uses this if statement to check whether it should render any sub menu items: 

`if (secondLevelMenuItems.Count(menuItem => !menuItem.LocalNav) > 1 || !firstLevelMenuItem.LinkToFirstChild) {`

I don't know if there is a reason for there to just be > 1 and not >= 1, but it means you need to need to specify menu items like this:

```
builder.AddImageSet("media-library")
                .Add(T("Media"), "6",
                    menu => menu.Add(T("Media"), "0", item => item.Action("Index", "Admin", new { area = "Orchard.MediaLibrary" })
                        .Permission(Permissions.ManageOwnMedia)));
```
If a menu item hasn't been added in this double structure, adding your own sub menu item is confusing and not particularly intuitive. Say you want to add a sub menu to the Users menu, you will need to provide that extra menu item (so that it passes the > 1 check), like so:

```
builder.Add(T("Users"), item => item
                .LinkToFirstChild(false)
                .Add(T("Users"), "0", t => t.Action("Index", "Admin", new { area = "Orchard.Users" }))
                .Add(T("Download Users"), "0.1", i => i.Action("DownloadUsers", "Admin", new { area = "Mod.Statistics" }).Permission(Orchard.Users.Permissions.ManageUsers)
            ));
```
I don't if this is how it is supposed to work, but it's definitely harder than it should be. (I also tried setting LinkToFirstChild to false so it would pass the other check in the if statement but this value only seems to be affected when originally adding the admin menu item, not when trying to append more onto an existing item.

**Comment by sebastienros** [comment]
I don't think we should change anything at that point, first because this would mean all the modules could be broken, also because it's not really a bug, and finally because there might have been some reason that I can't recall for this design. I remember there were long hours of thinking behind that, from people more clever than me. 

However I'd like you to suggest what you'd like to see in Orchard2, there is already a port of this API that I simplified, and it's still time to not make the same mistakes if you think there is one.
