### ISSUE TITLE
Layout feature's css styles interfere with bootstrap styles

### ISSUE THREAD

**Issue by kumards** [OrchardCMS/Orchard#7096]
I see css class `row `interfearing with bootstrap's css class `row`. Can we use different names for layouts?
May be `layout-row`?

**Comment by kumards** [comment]
The bootstrap section from the article http://www.ideliverable.com/blog/orchard-layouts helped me to overcome the issue for now. I still think some unique naming convention would avoid this issue.

**Comment by bleroy** [comment]
Well, if you're using Bootstrap, your theme should properly override the templates, which is what the linked article does. The idea here being that layouts should generate markup and classes that leverages Bootstrap instead of just standing next to it. In that way, I disagree that the feature should avoid conflict with Bootstrap. Am I missing something?

**Comment by kumards** [comment]
Well said! I cannot agree more.
I didn't realize it can be overridden at grid and column level to leverage by the theme.
