### ISSUE TITLE
Admin Theme - Empty manage page content typo

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7183]
Create should be create

![image](https://cloud.githubusercontent.com/assets/1038062/19007034/a453f28c-875a-11e6-83b9-b21b2e0ad0a5.png)

**Comment by agriffard** [comment]
As a localizer, I don't like these "Why don't create one?" used as empty placeholder because they are harder to translate (for example in French, there is a space before the '?') and there is the begining of a sentence in a resource and the rest in another and also the link button one.

It would be easier to have 2 separate texts : "There are no content items created yet." and "Create one" for the link.

**Comment by rtpHarry** [comment]
I agree the language should be consistent. A lot of the modules use different styles of wording. While we are doing breaking changes we should get in there and tidy as much up as possible.

Kind regards
Matthew

Sent from my iPhone

On 1 Oct 2016, at 10:52 pm, Antoine Griffard <notifications@github.com<mailto:notifications@github.com>> wrote:


As a localizer, I don't like these "Why don't create one?" used as empty placeholder because they are harder to translate (for example in French, there is a space before the '?') and there is the begining of a sentence in a resource and the rest in another and also the link button one.

It would be easier to have 2 separate texts : "There are no content items created yet." and "Create one" for the link.

-

**Comment by sfmskywalker** [comment]
Agreed
