### ISSUE TITLE
Incorrect log message in Indexing module.

### ISSUE THREAD

**Issue by hakan648** [OrchardCMS/Orchard#7225]
It's not that important, but I just want to note that a log message is not correct. :)

Take a look at [Orchard.Web/Modules/Orchard.Indexing/Services/IndexingTaskExecutor.cs#L298](https://github.com/OrchardCMS/Orchard/blob/a6f46d17cdfb46cd5573a3e4e9aebfd6a5d042a9/src/Orchard.Web/Modules/Orchard.Indexing/Services/IndexingTaskExecutor.cs#L298).

```c#
_indexProvider.Delete(indexName, deleteFromIndex);
Logger.Information("Added content items to index: {0}", addToIndex.Count);
```

**Comment by rtpHarry** [comment]
Well spotted, yes that message should be for deleted items. A lot of code in Orchard ends up being copy pasted and it looks like this is one of those cases where the original author has forgotten to tweak the pasted code.

It looks like you're new to GitHub, are you looking to get involved? If you want to do this as your first fix then you can make your change and I believe you should target it to the 1.10.x branch with your update.

If you're just letting us know then no worries I will make the fix for you.

**Comment by viniciusdfx** [comment]
Hey. I'm looking for projects to help with something and i'm a beginnner.

Can I help with this task?

**Comment by sfmskywalker** [comment]
Absolutely, this is a perfect issue when getting started. Please fork the repository, apply the fix, and create a pull request (PR).
