### ISSUE TITLE
Robots.txt module get lost

### ISSUE THREAD

**Issue by JingyuShao** [OrchardCMS/Orchard#7368]
I have slot A and slot B, both have Robots.txt module installed. But when I periodically import slot B's database into A, the Robots.txt module got lost. I can't see the module from orchard dashboard. 
I checked orchard log and DB log, nothing helpful.

**Comment by Skrypt** [comment]
Modules (NHibernate) creates their own database tables. Maybe the problem is with how you export that data. You should use the import/export module for that matter. If you want to just switch from one database to another you need to be sure you have that module locally and remotely. That way, you are sure at least to have the same database structure on both ends.

**Comment by sebastienros** [comment]
@JingyuShao "Got lost" can mean many things. You should look into the log to see why it didn't get loaded. Also what do you do to get it back up?

**Comment by sebastienros** [comment]
Talked offline with @JingyuShao The module was not part of the git repository, and was hence lost after each deployment.
