### ISSUE TITLE
Users' own Media folder PathValidation

### ISSUE THREAD

**Issue by LorenzoFrediani-Laser** [OrchardCMS/Orchard#7404]
A user with ManageOwnMedia permission can upload files to a folder that can't be accessed by other users which is Media/{Tenant name}/Users/{User.Name}.
User.Name can accept any char es:"*?", when user with these chars on username try adding media file to ContentItem  an error of ValidationPath occour  and folder can't be created.

Other problem, i think that to expose username can create Security Risk.

Other problem, changing username -> folder can't be accessed by user

I suggest a solution for the 3 problems 
change Media/{Tenant name}/Users/{User.Name}  to Media/{Tenant name}/CustomMedia/{User.Id}

**Comment by sebastienros** [comment]
- Normalizing the username would introduce a security issue as there would be collisions
- Using the id is a breaking change

The solution is not to normalize but to encode the username so that forbidden chars are replaced by supported ones.

Example: 
username: lorenzo*?
would become: lorenzo_2A_3F

It's using ASCII encoding, for any char that is not alphanumeric.

Also, if we want to be able to hide the username from urls, we need to create an extensibility extension. Let's create an `IMediaUsernameProvider` that would convert a username to the folder name. The default implementation is the one described above. Any other module can provide alternative implementations.

**Comment by sebastienros** [comment]
One example could be to attache an IdentityPart to the User type, and use it as the folder name.
