### ISSUE TITLE
Dynamic Forms and Email Workflow: newlines in textarea lost

### ISSUE THREAD

**Issue by petermorlion** [OrchardCMS/Orchard#7512]
I wonder if this is a "bug" or if it's me doing something wrong. I've set up a Dynamic Form as a contact form. I have a textarea for the visitor's message. I've also set up a Workflow so a mail is sent to the site admin. However in that email, the message is put on one line, i.e. any newlines/linebreaks have been removed.

**Comment by sebastienros** [comment]
I assume the issue is that you get the message correctly with new lines, but when the email is sent, you are sending an HTML email, so all new lines will then be rendered as spaces by the HTML client. You need to convert the new lines into <br/> tags.

You should use the `HtmlEncode` token for security reasons (so that I can't send you malicious content to your email box) and then chain it with a `LineEncode` token to replace all new lines with  `<br/>`
