### ISSUE TITLE
methods in AccountController of in openid module should consider returnUrl

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#7530]
methods in AccountController of in openid module should consider returnUrl like orchard.Users

**Comment by Devqon** [comment]
It does..: https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Users/Controllers/AccountController.cs#L74

**Comment by ThaerAlAjlouni** [comment]
@sebastienros Yes I think it does, it will be nice to have this, but the way **OpenId** works by default will prevent that because it relies on redirecting back to a specific action (_LogOnCallback_ in our case).

I think this is doable by saving the requested URL (in memory or session or another mechanism) before redirecting to the Id provider and then handling it again on successful login.

What do you think?

**Comment by sebastienros** [comment]
Using Session directly is not recommended. Try to use TempData whic is used for return url too.
