### ISSUE TITLE
Login causes error

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#7561]
I apologize if this has already been reported. When a user is logging in, they can enter their user name and hit enter. This will post the login attempt and return an error that they need to provide a password. If the user fills out the password field and hits enter, the post will begin, BUT if the user goes and clicks the submit button it can cause an error. What I think happens is that if the system is slower (not local) the first post from hitting the enter key causes the second post from hitting the submit button to have an invalid token. This seems like a simple javascript blocking the login button when the form is posting would solve this. Clearly this is a user error, but I have been getting reports of this quite a bit.

**Comment by sebastienros** [comment]
The issue is that you can't double clock a button on a form in ASP.NET MVC. The second click will trigger an Antiforgery validation issue. The solution is to prevent double click on specific buttons. We do that in the admin: https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Themes/TheAdmin/Scripts/admin.js#L84

This is a per theme issue, you should change your theme by using the same solution.
