### ISSUE TITLE
Please Help! Cannot fully customize layout.cshtml to match existing website

### ISSUE THREAD

**Issue by bobi33** [OrchardCMS/Orchard#7569]
Hi, 

I am trying to customize the layout.cshtml file with a few css files (including bootstrap). To test this out, I copied the existing assets folder, which contains all relevant styles and js components from the existing website, into the orchard.web folder, and I have included such folder in the Visual Studio solution. However, when I erase everything in the ThemeMachine layout.cshtml file and include the basic html code from my index.html file from the existing website, the style does not carry-over for some reason. Am I missing something? It's as if none of the assets (css files and js components) are not being picked up by layout.cshtml.

**Comment by siyamandayubi** [comment]
If you include more detail about the Layout.cshtml file in your theme and folder structure of your theme, then we can help you more.

Generally, you can reference css files by the adding the following line to your theme
Style.Include("site.css");

It will add a link to the following css file.
/Themes/[YOUR THEME]/Styles/site.css

Also, I think it is better to create a fresh theme and customize that  instead of manipulating TheThemMachine

**Comment by bobi33** [comment]
="http://slclaw.caThanks. I tried that but it still did not pull the correct css and js files from the assets subdirectory in the main root. So in stead of pointing to 
<link rel="stylesheet" href="assets/css/headers/header-default.css">

I uploaded the assets folder to the main root on my server (hosting provider) and pointed to 

<link rel="stylesheet" href="http://xyz.com/assets/css/headers/header-default.css">

That seems to get the desired result...

**Comment by sebastienros** [comment]
Next time, feel free to use the Gitter forum for questions, thanks
