### ISSUE TITLE
Reference issue when using OrchardCMS

### ISSUE THREAD

**Issue by bobi33** [OrchardCMS/Orchard#7574]
Hi there,

I am new to orchard and am having an issue with reference links. Specifically, I am using OrchardCMS in addition to an already existing html5 bootstrap website (I am using Orchard for the blog menu item in the existing site). I am trying to determine how to link to Orchard in the existing website's menu (I'm assuming a simple href pointing to the directors that Orchard is in). 

However, I am not sure why a Not Found message is being provided to me after I try to move back to the index.html page from the blog page running the Orchard engine? For example, I go from index.html to (http://localhost:xxxxx/index.html) to the blog page (http://localhost:xxxxx/OrchardLocal), but when I try to click on the home page to bring me back to index.html I am presented with a Page Not Found message and the link is http://localhost:xxxxx/OrchardLocal/index.html. 

I want to go back to http://localhost:xxxxx/index.html not http://localhost:xxxxx/OrchardLocal/index.html.

Any help would be greatly appreciated. Essentially I am using Orchard in addition to an existing website for the purpose of running a blog...I do not want to make Orchard the main root because it is quite a bit of work to convert the styling to cshtml, etc...

**Comment by DanielStolt** [comment]
This happens because Orchard by default is configured to run under the `/OrchardLocal` virtual directory. You have two options:

1. Put your custom `index.html` inside of `Orchard.Web` so that it resides within Orchard.
2. Change your link to a custom link that includes a leading slash `/index.html` which will make it relative to the root of the server.
