### ISSUE TITLE
Admin theme : Audit trail settings

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#7583]
I'm getting a blank page.

![image](https://cloud.githubusercontent.com/assets/3228637/23273665/e7700340-f9cd-11e6-8d70-f17ef5c521b0.png)

**Comment by sfmskywalker** [comment]
This appears to be admin-unrelated, but I'll check on the 1.10.x branch to see if there's anything to fix there.

**Comment by sfmskywalker** [comment]
Issue appears on 1.10.x as well. The issue is an inconsistent use of the "Audit Trail" GroupInfo use. "AuditTrail" is used for the settings menu item URL, which makes it a GroupInfo route value, but since "Audit Trail" is used as the GroupInfo name in code, the AuditTrail settings driver isn't invoked.

I also noticed a runtime error with the background trimming task that I'll push a fix for.

**Comment by sfmskywalker** [comment]
Actually, the trimming issue appears to have been fixed already in the 1.10.x branch, so nothing to do there.

**Comment by sfmskywalker** [comment]
Fixed in 9f98d3151b3f81eb00983f428f53b5080cd1a35d

**Comment by Skrypt** [comment]
👍

Get Outlook for iOS




On Tue, Feb 28, 2017 at 8:39 AM -0500, "Sipke Schoorstra" <notifications@github.com> wrote:












Fixed in 9f98d31
