### ISSUE TITLE
dev: #6652 should we delete AzureOutputCacheStorageProvider.cs

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#7584]
after #6652, Orchard.Azure\Services\Caching\Output\AzureOutputCacheStorageProvider.cs was removed.
Orchard.Azure.OutputCache: still in the module.txt.
---------------------------
more, according to document , Cache Service for Orchard.Azure.OutputCache can be Enabling for Windows Azure Web Sites or the site of the other hoster,  so this  is not related with Cloud Services, why also deleted it?

**Comment by sebastienros** [comment]
I think this class was only related to Cloud Service cache (Role Cache). And Azure Websites don't provide any cache service. The only support cache service in Azure is the Redis Cache which is handled by the Resis module/features.

However if Orchard.Azure.OutputCache is still present in the manifest, this might be a problem.

I am opening this issue just in order to remove the feature from the manifest, and also the constant `OutputCacheFeatureName` that references it.

**Comment by infofromca** [comment]
#6652 only affect dev branch
