### ISSUE TITLE
modules/alias  features in orchard

### ISSUE THREAD

**Issue by KumarVikey** [OrchardCMS/Orchard#7585]
i had a running solution of my project .but i changed the setting by disabling alias in module now i am getting Autofac.Core.DependencyResolutionException.
      is there any way to solve this issue or enable the alias.

**Comment by sebastienros** [comment]
The solution might be to change the enabled features list directly in the database, like all the dependency graph of features that depend on Alias. Or you can copy the value from a clean setup.

You might also try with the command line tool to enable all the missing features.
Also remove the cache.dat file which is in app_data/sites so that the features list is not cached, after each operation, or the database changes won't be applied.
