### ISSUE TITLE
How to use Angular 4?

### ISSUE THREAD

**Issue by mehranrezaei** [OrchardCMS/Orchard#7701]
I am using Orchard branch 1.10.x. I need to use Angular 4 for a new project. The new version of Angular has not a simple JavaScript file. I should install, test, build and bundle it using npm, webpack, ... and a modular system. Also it uses TypeScript. But Orchard uses Assets.json file with Gulp.
How should i setup my module or theme to use the new version of Angular?

**Comment by sebastienros** [comment]
Use whatever tool you want instead of Assets.json and Gulp. In the end your javascript files should just go in a folder of the module so that you can reference them from the views.

**Comment by Xceno** [comment]
I use Aurelia in some projects and typically have an "Aurelia" - folder in my project, which is completely self-contained. Then I write a `ResourceManifest.cs` that points to the exported bundle.
Small tip: Since angular 4 uses TypeScript I highly recommend to check out the [TypeWriter Extension](https://marketplace.visualstudio.com/items?itemName=frhagn.Typewriter) for VisualStudio, so you can easily share ViewModels and Interfaces with your angular app.

**Comment by mehranrezaei** [comment]
A special thanks to all you guys.
@sebastienros Do you confirm that creating a package.json or node_modules folder under a module or theme folder cannot cause a problem?

Is there any recommended way specially about Angular 4 and Orchard?
Also as you know Orchard.Layouts and some other modules uses Angular 1.x. Is there any plan to upgrade them for using new version of Angular in the future? (Because loading two different versions of Angular will be a problem.)

**Comment by Xceno** [comment]
I'll jump in here again real quickly, I hope you don't mind ;)
We have *jspm* and *node* folders in many different modules and never had any real problems whatsoever.

**Comment by mehranrezaei** [comment]
@Xceno Thank you for your help.
