### ISSUE TITLE
in new version 1.10.2 , culture does not work in front end! 

### ISSUE THREAD

**Issue by Reza-Piri** [OrchardCMS/Orchard#7726]
hi

after installing new version , culture (for example Persian culture fa-IR) does not work in front end.
and date time format is not correct!

**Comment by BenedekFarkas** [comment]
Hi,

I assume you added `fa-IR` on the Dashboard under `/Admin/Settings/Culture`. This means that when you create content translations (which is allowed by having `LocalizationPart` on the given content type) you can select `fa-IR` as the culture. UI and date localization are set up separately:

- To install a UI localization package, check out [the "Localization" page on the website](http://orchardproject.net/localization).
- Dates will be localized if the current culture is set - by default the UI is displayed according to the default site culture that you can set under `/Admin/Settings`. You can override by enabling the `Culture Picker` feature, which will add a culture selector dropdown to the top of the page.

Does it answer/help with your question?

**Comment by Reza-Piri** [comment]
hi,
i know these solutions. And i have done these before. these solutions worked fine in previous version.
but now, it doesn't work!

## i did setups :
![002](https://cloud.githubusercontent.com/assets/13100338/26777147/5da18a02-49f1-11e7-8c6e-5efa5a70bd7f.png)

## and i selected correct culture for content :
![001](https://cloud.githubusercontent.com/assets/13100338/26777197/8ad6ec4c-49f1-11e7-800c-74e0a4408ca9.png)

## and even date picker works fine in admin area and shows correct date format : 
![004](https://cloud.githubusercontent.com/assets/13100338/26777218/a0bd3c1e-49f1-11e7-9933-67758756b913.png)

## but  dates are not showed in correct format in front end (year and day part is correct, but month and weekday is wrong) :
i think something is wrong with jquery resources.. 
![003](https://cloud.githubusercontent.com/assets/13100338/26777348/19e96388-49f2-11e7-9d46-4b47a0228df8.png)

**Comment by sebastienros** [comment]
@omidnasri do you agree with the issue or do you think it's fixed in 1.10.x ?

**Comment by BenedekFarkas** [comment]
Is this the expected result?

![image](https://user-images.githubusercontent.com/2797449/46221837-d4366480-c34e-11e8-86f6-dfd91584f93f.png)

This is on 1.10.x, with the latest commit.

This includes the fix for #7738 (3644d868ec72643030ea16cc99c2ddb89c0b3bdf), but the current fa-IR translation throws the same error, if we don't split the translated day/month names by the space character as well.

We can do that easily, but that is a potential problem for cultures that have space in a day or month name. According to the .NET Frameworks CultureInfo instances, there are:

- There are 117 cultures with the least one month name with a space in it.
- There are 77 cultures with the least one day name with a space in it.

So translations for these cultures would be broken, but looking at the list, I don't really expect this to be a problem anytime soon.

Just for the sake of completeness, there are 2 cultures (`Yangben (yav)` and `Yangben (Cameroon) (yav-CM)`) with at least one day or month name with a comma in it. With the fix linked above, those translations (if they existed) are broken anyway.

**Comment by BenedekFarkas** [comment]
@sebastienros so should we split by space characters as well, then? That will make this problem go away, but can break a lot of translations (mostly African and South American languages that we don't have translations for and I'd be surprised if someone would like to add those).

Edit: Done, see the commit below.
