### ISSUE TITLE
Taxonomies->Terms List Issue,case by TermsComparer's Compare method

### ISSUE THREAD

**Issue by wthinkit** [OrchardCMS/Orchard#7832]
When I create a child [cA ]term under A and [cA] show under B node as B's child in the terms list view. 
I find this is case by the 'Compare' method in the 'TermPart' class. attached:
![compare](https://user-images.githubusercontent.com/16713368/29671297-bc416f1e-891b-11e7-99bd-2a006f338ca0.png)

Say we have term with fullpath: /24 and other one's fullPath is /241/247, so u know it, bang!
Then I add a new property 'FullPathEnd' in TermPart Class to fix this, also attached:
![new bitmap image](https://user-images.githubusercontent.com/16713368/29671618-95b49cd0-891c-11e7-8c9f-ebe117f53397.png)

Well, there could be more effective solution,its do the trick.

**Comment by sebastienros** [comment]
@jersiovic what do you think?

**Comment by jersiovic** [comment]
It looks the compare method is using FullPath instead of FullWeight the new property @jardg added.
We didn't change this method because it is not used anywhere so we marked it as obsolete.
Is it posible the terms view you mention is a custom one in your theme?
We can fix Compare to work properly and remove the obsolete annottation.

**Comment by jersiovic** [comment]
Well it is not so easy because current Compare method is used by the Orchard.Upgrade module when it calls TermPart.Sort() for the migration of terms from previous versions, and for that it is needed as it is. 

I imagine at some point you are using TermPart.Sort() method in your view instead of simply get terms ordered per FullWeight using TaxonomyService.GetTerms(). My advice is replace one per the other.

What we can do in Orchard for avoiding confusions like that is to mark also TermPart.Sort() as obsolete, but maybe it is not enough. Maybe we should rename obsolete method and comparer to TermPart.ObsoleteSort() and ObsoleteTermsComparer() to allow an early detection of obsolete calls in custom code at compilation time.

**Comment by jardg** [comment]
@wthinkit  Looks like you could be using Sort method on the retrieved terms when generating a custom Terms View?. Sort actually should be Obsolete as @jersiovic says. Also could you specify the repro steps?. Did you have an existing taxonomy in which you added the new terms or you tested it creating a new taxonomy?. In case you had an existing taxonomy, did you apply the migration for terms using the Upgrade module? so you dont have to use Sort because the terms can be retrieved from db and ordered by FullWeight.

**Comment by wthinkit** [comment]
Wow, the new way to order terms,after I pull the newest code and checkout dev branch, good job!

**Comment by BenedekFarkas** [comment]
`TermPart.Sort` now yields a build warning as it's still using `TermsComparer`, which marked as Obsolete (but there's no recommendation what to use instead, btw). Can we change it like this?

```
public static IEnumerable<TermPart> Sort(IEnumerable<TermPart> terms) =>
    terms.OrderBy(term => term.FullWeight);
```

Btw we should add some documentation to `TermPart`, as `int Weight` vs. `string FullWeight` looks confusing to me.

**Comment by jardg** [comment]
I will work on it and submit a pr with this change and documentation about the Weight

**Comment by jardg** [comment]
Where should I provide the documentation? I didn't find any written documentation about terms or taxonomies other than a simple mention to the Orchard.Taxonomies module.

**Comment by BenedekFarkas** [comment]
I think some in-line documentation (for both properties) is enough. What do you think about the Sort method?

**Comment by jardg** [comment]
Yes. Should be changed to the way you say.I didn't change it at first because I didn't want to force the users to upgrade but this way it's better than just order manually everywhere you want to sort the items.

I added a static SortObsolete method with the old code because TaxonomyController needs in Upgrade module to migrate terms created in an old version.
