### ISSUE TITLE
Possibility of setting user roles in IUserRoles by code

### ISSUE THREAD

**Issue by jardg** [OrchardCMS/Orchard#7851]
I have an scenario where I have a user which has associated(logically) other type(clients) but separately on his own type not as parts of the same content item. Those clients each have their own roles instead of the user having the roles. The user authenticates, then chooses the client he wants to work with and signs in. 

The problem is that I want to grant access to the clients according to the permissions linked to the client roles using Services.Authorizer.Authorize(Permission permission, LocalizedString message) but this one looks for the roles related to the user that has signed in.For doing this the Authorizer gets the user roles from user.As<IUserRoles>().Roles which value is provided on UserRolesPartHandler. 

My question is if there is any way I can change those roles and assign the roles I want to check using a handler or participating in the roles assignation in any way. What I have done locally is creating my own handler making a implementation of OnInitialized<UserRolesPart> and assigning there IUserRoles.Roles. But for doing this I need to change the access modifier of _roles in UserRolesPart from internal to public. Can I make a pull for this or is possible to do some other workaround?

**Comment by sebastienros** [comment]
I think you can, the security handlers can actually alter the list of permissions to check when a permission is checked, then mark it as "altered" so that the permission checked is run again using the new set of permissions. This is how roles are converted to permissions, and also how dynamic permissions are done for dynamic content types.

Check the classes that implement `https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Security/IAuthorizationServiceEventHandler.cs` to see how it can be used.

**Comment by jardg** [comment]
Solved. Thanks for the help!. I close the issue
