### ISSUE TITLE
Content could not be get the correct value into DecimalFieldIndexRecord table in User editor page at the first creation

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/Orchard#7950]
I add a NumericField to User type and name it as Login.
When I fill in this field in User editor page or create a new user using ContentManager, the content could not insert into DecimalFieldIndexRecord. 
Then I search this field using Query in Projection, as the field is 0 in database table, I can't get what i want from the Query. 

But when I import user content in Import module, those data can be inserted into the table successfully, so I can query those imported content but could not query the content I create in admin page or create using ContentManage in code

Any suggestion?

Thanks

**Comment by HengzheLi** [comment]
new finding. the field can be inserted into table but its value is 0 in creation. then when the content is edited and save again,  the table can save the correct value

**Comment by HengzheLi** [comment]
I think my issue is the same as #4927 which is raised according this SO question https://stackoverflow.com/questions/27145865/orchard-cms-adding-default-data-to-fields-and-then-querying-them

And seems that #4927 is still open.

**Comment by sebastienros** [comment]
Can you provide some repro steps and what you would expect, I am confused by this "the content could not insert into DecimalFieldIndexRecord", I don't understand what you mean.

**Comment by HengzheLi** [comment]
Sorry for my pool written words.

I query content using Projection with ContentField filter. The filter will query table DecimalFieldIndexRecord in my case and the content field is 0 while I was querying it. But before I query it, I have create content item and fill that custom field

**Comment by BenedekFarkas** [comment]
FieldIndexing has gone through some changes recently, so that might be the cause that I can't repro this problem (tested with a custom type and also the User type, just to be sure - Field Indexing and Projection Queries working as expected). 

But I've found an other issue: `EditorShapes` in `Orchard.Forms.Shapes` doesn't define a shape for an input field that has `type="number"` and the one for TextBox can't be overridden with dynamic parameters to use that type. This means that `NumericFilterForm` has normal textboxes, so the decimal separator won't be validated. ~~When you are editing content, the input for NumericField has this attribute, so the decimal separator will be validated against the one defined by the site culture (but that can be overridden by e.g. the Admin Culture Selector).~~
The NumericField editor doesn't use `type="number"` either.
