### ISSUE TITLE
Orchard Gallery can't install any modules, locally or on live site

### ISSUE THREAD

**Issue by edwardm** [OrchardCMS/Orchard#8062]
I'm bringing this issue over from the Orchard Gallery project:
https://github.com/OrchardCMS/Orchard.Gallery/issues/38

![edward margallo ux ui design development install package failed](https://user-images.githubusercontent.com/444720/40517698-7827d09e-5f6b-11e8-83a6-5c4783f21b57.png)

Anyone have any ideas?

**Comment by sfmskywalker** [comment]
I was wondering if I was the only one seeing this issue. I can't seem to install anything from the gallery, or from the local machine for that matter. Not even packages from the gallery that used to work before. So far it's been a mystery to me.

**Comment by rezarouf** [comment]
Do a clean build, delete  files inside the bin and run again.

**Comment by BootprojectStore** [comment]
I did a clean new fresh installation, still the same problem. Also the thumbs only on Orchard Cms modules is shown.

**Comment by jayharris** [comment]
This appears to be an issue with the feed, not with the Orchard installation. Though the feed is at `gallery.orchardproject.com`, the Gallery's feed service is reporting the download link for each package as `orchardgallery.azurewebsites.net`. Anything request to `orchardgallery.azurewebsites.net` is returning an HTTP403.

The package won't download because of the 403, causing the installation failure.

In the Gallery tab, copying the URL for the package's download link, changing the domain from `orchardgallery.azurewebsites.net` to `gallery.orchardproject.com` will at least get you a successful download in the mean time.

**Comment by jayharris** [comment]
The Base URL within the Gallery Settings might be set to `orchardgallery.azurewebsites.net` instead of `gallery.orchardproject.com`.

**Comment by sebastienros** [comment]
Thanks @jayharris that fixed it

**Comment by edwardm** [comment]
Works now, thanks guys!
