### ISSUE TITLE
AuthenticationService GetAuthenticatedUser and OrchardServices WorkContext CurrentUser()  failing intermittently

### ISSUE THREAD

**Issue by Ifetayo** [OrchardCMS/Orchard#8064]
Hi,
I am having some issues with the above methods. For some reason the authenticationservice **GetAuthenticatedUser** and orchard services workcontext **CurrentUser** methods fail to get the authenticated user.

I have a pretty simple set up I just want to get the authenticated user. This behaviour happens say once in about a hundred times. 

I think it is worth noting that I am logged in with the same user on different computers connected to the same database. I don't think this should be the cause because it happens on my development box where I am the only user logged in. Below is the code I use to get the authenticated user.

`var currentUser = _orchardServices.WorkContext.CurrentUser;` or
`var currentUser = _authenticationService.GetAuthenticatedUser();`

Also I have a model that extends the UserPartRecord, and this is how I get my model

`                var myExtendedUserModel = _myExtendedUserModelService.Get(x => x.UserPartRecord == new Orchard.Users.Models.UserPartRecord { Id = currentUser.Id });
`

I have no idea why this fails sometimes. Am I doing something wrong?

**Comment by MatteoPiovanelli** [comment]
Hello,

`WorkContext.CurrentUser` is not a method as far as I know, so I'll assume that is a typo in the issue here.

What exactly is failing? Is `currentUser` null?

I would try, as a comparison in your method, something different, because I am not sure comparing an existing record to a new one, even where you set the Id, is correct. Something like this:

```
var myExtendedUserModel = _myExtendedUserModelService.Get(x => 
    x.UserPartRecord.Id == currentUser.Id);
```

**Comment by Ifetayo** [comment]
thank you @MatteoPiovanelli-Laser for your response. Yes indeed that was a typo and I have corrected it.

The crux of the issue is that  `WorkContext.CurrentUser` returns null intermittently. 
Even if the way I was comparing existing records isn't how it should be done, fact is that the `currentUser` returns null thereby causing a null ref when I use this `currentUser.Id`.
Just as I pointed out even `_authenticationService.GetAuthenticatedUser();` returns null too. This behaviour happens intermittently. 
I am lost for ideas right now. 

Edit: To put into perspective I have several tenants, active and inactive. Also I tend to use the same logged in user on different browsers on different computers.

**Comment by MatteoPiovanelli** [comment]
You may be seeing the issue I was seeing related to this:

https://github.com/OrchardCMS/Orchard/blob/1.10.x/src/Orchard.Web/Modules/Orchard.Users/Services/MembershipValidationService.cs

Basically, if you login from a different browser, you get logged out from every other client.

You may configure that differently from sites.config

**Comment by Ifetayo** [comment]
Thank you @MatteoPiovanelli-Laser I seriously doubt that is the case. When `WorkContext.CurrentUser` returns null, I do a simple page refresh and I get back the current user object. 

Just like I said this happens intermittently.

**Comment by MatteoPiovanelli** [comment]
Are you running 1.10.x? or a build from the dev branch?

**Comment by Ifetayo** [comment]
@MatteoPiovanelli-Laser Orchard 1.10.2, thank you.

**Comment by MatteoPiovanelli** [comment]
Since a refresh "fixes" this, I would like to make sure it's an issue on Orchard's side:
Could you check whether, when it failed, the browser had sent the correct cookies? The one we are interested in is the .ASPXAUTH cookie, that contains the information Orchard uses to identify the authenticated user. 
I am not sure what would be the best way to test that.
If you can make this happen somewhat reliably, I would add either breakpoints or calls to `Logger.Error` in `GetAuthenticatedUser()` to understand where it's going wrong.
If I remember correctly, `WorkContext.CurrentUser` is calling `GetAuthenticatedUser()` behind the scenes, so it should be enough to check there.

**Comment by Ifetayo** [comment]
Thank you @MatteoPiovanelli-Laser for your response.

Replication of the issue is rather vague, it happens with intermittently and indeterminately. 

I suspected that the case was the browser not sending the correct cookie value, I am logging all cookies sent for every request. I hope to replicate the said issue soon. I will keep you posted on the outcome. Thank you very much @MatteoPiovanelli-Laser , I really appreciate your work and efforts.

**Comment by stephanlotter** [comment]
I had this problem on my development machine too. Turned out to be that my Orchard was configured to work on localhost (e.g.: http://localhost), but I was accessing the site using the IP address (e.g.: http://192.168.0.1).

The problem was resolved by using http://localhost.
