### ISSUE TITLE
Can't download from Gallery

### ISSUE THREAD

**Issue by a1Sandor** [OrchardCMS/Orchard#8075]
Hi,
I have this feed URL: "https://gallery.orchardproject.net/api/FeedService"

As far as Im concerned, this is the latest URL?
However I am still getting an error when trying to install modules. I have given access to all of the folders required.

**Comment by sfmskywalker** [comment]
It's the correct URL. The problem appears to be within Orchard itself somewhere when reading the actual NuGet package. You can try it for yourself by downloading the package to your computer and then try and install it (using the Browse button somewhere in the Modules view on one of the tabs). For me, it always fails, no matter which module I try (even the ones that I know worked before).

**Comment by a1Sandor** [comment]
Thanks for the reply.
Thats how I've been installing the modules. The only reason I want to get this to work is because of the "Designer tools" module. I really need to get URL alternates. When I install it from my computer, it gives me an error about "claySharp" and it wont work.

**Comment by sfmskywalker** [comment]
Interesting, so you are actually able to install NuGet packages 🤔 
So it sound like your issue is not installing modules, but that you're getting a compilation error. Are you working with the full source solution, or the web package (precompiled) one?

**Comment by a1Sandor** [comment]
I'm not sure. I don't usually work with asp.net and c#. I downloaded from this link http://docs.orchardproject.net/en/latest/Documentation/Installing-Orchard/ on the third bullet point as the zip file. and I am using IIS as the server. Im guessing its the precompiled one.

**Comment by sfmskywalker** [comment]
So you downloaded Orchard.Web.1.10.2.zip?

**Comment by sfmskywalker** [comment]
If so, that's a precompiled one.

**Comment by a1Sandor** [comment]
So could that be the problem?

**Comment by sfmskywalker** [comment]
The problem seems to be the module you installed can't be compiled for some reason. Come to think of it, you should not have to install the Designer Tools module yourself, since it's already included as part of the core distribution. My guess is that the module you installed is vastly outdated (Claysharp was removed a long time ago).

Try deleting the module from your Modules folder. If it overwrote files from the existing *Orchard.DesignerTools* folder, then just delete it wholly and copy it back from the Orchard.Web.1.10.2.zip file. 

Then from within the Orchard admin area, go to Modules -> Features and locate the Designer tool features and just enable them.

**Comment by a1Sandor** [comment]
And... You fixed it for me.

It has overwritten the pre installed designer tools when I tried to install them so i just copied it back from the Orchard.web.zip and enabled it.

Thank you so much.

**Comment by sfmskywalker** [comment]
Good!
