### ISSUE TITLE
how to set the workflow to remove the notification if content item is removed.

### ISSUE THREAD

**Issue by rezarouf** [OrchardCMS/Orchard#8120]
Hi i use workflow to trigger notification , for example in my website if i publish a news, the workflow broadcast across all the users through notification.

![image](https://user-images.githubusercontent.com/39696836/46059860-a5699400-c17e-11e8-82bd-a34242ff0892.png)

Now if i delete the news , the notification still stays .. how do i set the workflow such that the notification disappears once the item is deleted 

this is my message for broadcast : **_(("notification":(("title":"News Published","details":"{Content.NewsTitle}","id":"{Content.Id}","url":"{Site.BaseUrl}/News/Details/Article/{Content.Id}"))))_**

@Piedone @sebastienros

**Comment by Piedone** [comment]
The Broadcast activity is something you've written, right? Because then you can check there is the item still exists. Otherwise I'm afraid there is no feature in Workflows for this directly, but depending on how the Broadcast activity works you may be able to utilize the Decision activity to write some C# for your decision logic.

**Comment by BenedekFarkas** [comment]
@rezarouf please reopen or follow-up on [Gitter](https://gitter.im/OrchardCMS/Orchard) if this question is still relevant.
