### ISSUE TITLE
In exception stacktraces, how to show line numbers for non-core modules?

### ISSUE THREAD

**Issue by 0liver** [OrchardCMS/Orchard#8133]
Orchard has always intrigued me with showing line numbers in exception stacktraces even for Release builds. As it turns out, [there is no magic behind this](https://stackoverflow.com/a/628590/177710).

Now, I would like to see line numbers for code from our own modules - but I can't get it to work. I've tried putting my modules .PDB files in a number of places, but they are not picked up/used when an exception stacktrace is generated:

- the root \bin folder
- the App_Data\Dependencies folder
- they are already in the module's \bin folder

Please let me know how I can achieve this.

**Comment by 0liver** [comment]
@sebastienros @bleroy @Piedone @pszmyd @BenedekFarkas 

I really hope you know the answer - please share your knowledge with me and the world ;-)

**Comment by Piedone** [comment]
Hmm, I can't actually remember that I've seen line numbers in logs ever. I just checked and they're certainly not there for me, not even when running locally in debug mode (yet alone in production). So I'm afraid I can't be of too much help here; however you shouldn't need to manually move the PDF files. If your csprojs don't have any different config than built-in Orchard modules' (I'm talking about the ones in the Modules folder, since technically they're the same as your own modules) then they should work the same too.

**Comment by 0liver** [comment]
Thanks, Zoltán, for answering.

Well, I haven't seen line numbers from **regular** modules, either.  The core modules generate them, but they are naturally loaded from the \bin folder, so that's a different pair of shoes.

Maybe the solution is not that obvious - but we would be very glad to have those line numbers to tackle some of our bugs more easily.

**Comment by bleroy** [comment]
One thing that generally helps a lot is to check out the Modules window in Visual Studio during a debug session. It shows you where each dll was bound from, and should give you some clues about where it'll look for symbols and other debug info.

**Comment by Piedone** [comment]
Hmm, if it's core modules (i.e. the ones in Orchard.Core) then yes, possibly the issue is that those assemblies are not statically referenced from Orchard.Web (but dynamically loaded, so that might mess things up). Try adding a reference to your modules from Orchard.Web.

And I just noticed I've written "PDF" files :D. That's when you do more bizdev than development.

**Comment by 0liver** [comment]
Thanks, everyone, for your input.

@bleroy You put me on the right track - the PDB files must be placed side-by-side with the modules' DLL files in the `App_Data/Dependencies` folder. I had tried that once by hand, but the PDB must have not exactly matched the DLL, so it wasn't used.

Here's how I achieved my goal for **precompiled extensions**.

I added the following method to `IAssemblyProbingFolder`:

```
/// <summary>
/// Store an assembly's PDB file corresponding to "moduleName" from the given fileName
/// </summary>
void StorePdbFile(string moduleName, string fileName);
```

And the following implementation to `DefaultAssemblyProbingFolder`:

```
public void StorePdbFile(string moduleName, string fileName) {
    try {
        var path = PrecompiledAssemblyPath(moduleName).Replace(".dll", ".pdb");

        Logger.Information("Storing pdb file \"{0}\" for module \"{1}\"", fileName, moduleName);
        _appDataFolder.StoreFile(fileName, path);
    }
    catch (Exception) {
        Logger.Information("Could not find/copy pdb file \"{0}\" for module \"{1}\"", fileName, moduleName);
    }
}
```

And then I call that method in the `PrecompiledExtensionLoader`:

```
if (copyAssembly) {
    ctx.CopyActions.Add(() => _assemblyProbingFolder
        .StoreAssembly(extension.Id, sourceFileName));
    // added the following line:
    ctx.CopyActions.Add(() => _assemblyProbingFolder
        .StorePdbFile(extension.Id, sourceFileName.Replace(".dll", ".pdb")));
    // ...
}
```

And now I can see line numbers for our own code in those exception stacktraces. Hurray!

**Comment by BenedekFarkas** [comment]
I think this could be a nice addition to the source - enabled by default and disabled in the Release transform of HostComponens.config for example?
