### ISSUE TITLE
Orchard CMS Facets using field [type] not working

### ISSUE THREAD

**Issue by kcastro18** [OrchardCMS/Orchard#8158]
I am working on a custom search module and I am stuck in trying to implement facets that was discussed in this video https://www.youtube.com/watch?v=7v5qSR4g7E0&t=2960s.

So, I have a content type named [Docket] and I am trying to count how may Dockets are there in my search results. I tried the code below but the docketsCount is always 0.

`var resultFacets = searchBuilder.GetBits();

var docketFacets = _indexProvider.CreateSearchBuilder(index).WithField("type", "Docket").Mandatory().ExactMatch().GetBits();

int docketsCount = 0;
if(docketFacets != null) {
    docketsCount = (int)resultFacets.And(docketFacets).Count();
}`

I tried using other fields, like [author] and that one works fine. I don't know why the [type] field is not working or does it have different values other than content type names?

Please tell me what I'm doing wrong. Any help is greatly appreciated.

Thanks, Karen

**Comment by Skrypt** [comment]
I see that you posted a lot of requests in different places. If someone can provide informations about indexing features in 01 please do. I can't really answer from the top of my head on this since I've never used Orchard for indexing extensively. Though with Orchard Core you can use ElasticSearch queries now. Depending on how much advanced you are on your project I'd suggest you take a look at Orchard Core and see if it would fit your needs.

I'd say by looking at your code that maybe the .Count() method doesn't work. Try looking at wich type 'resultFacets.And(dockerFacets) returns you. If you have actualy records returned you could try to add the results in an Array or a List which allows having a .Count() or .Length() method.

**Comment by kcastro18** [comment]
Thank your response. Do you know a good source/material I can read on about ElasticSearch? And I don't know where to start looking into Orchard Core. Could you give me an idea? 

About the code .Count(), I know for a fact that it works because like I said I used [author] field and that counted the items just fine. I also have another facet for Rule content types that counts how many items in the search result has a [true] value in their [rule-iscurrentversion] field and that works fine as well. 

Which is why I am baffled as to why [type] field won't work even as a filter.

Again, thank you and any help is greatly appreciated.

**Comment by Skrypt** [comment]
Here is the documentation of ElasticSearch for Queries.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html
Are you sure that this Field is stored in your Lucene index? You could try to inspect your index with a tool like Luke : https://github.com/DmitryKey/luke

**Comment by sebastienros** [comment]
The `type` field is not analyzed when it's been indexed, which mean when you query it you should not analyze it either, or it won't match the "exact" value. In this case you need to call `WithField("type", type).NotAnalyzed()`.

**Comment by kcastro18** [comment]
.NotAnalyzed() worked perfectly! Thank you so much!
