### ISSUE TITLE
enabling module requires app restart

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#8191]
This is a really annoying issue that causes frustration for developers and fear in non technical end users who see that sometimes when you enable an application you have to restart the app. This is happening specifically on azure web services.

**Comment by sebastienros** [comment]
By design on .NET Framework, not much we can do about it. In Orchard Core we only reload the tenant so it's much faster, and doesn't impact other tenants.

**Comment by roballred** [comment]
@sebastienros Can you explain what is happening and any practices that we can use to minimize the impact on sites? Moving to Orchard core is not the answer for many sites right now.

**Comment by sebastienros** [comment]
This is how it was implemented, and it won't change because there are too many things that would change too. Because enabling a mode is not something that is done often, and shod probably not be done in prod, it is easier to generate the DI services from scratch by restarting the site. Also as the module might require dynamic compilation it would also force a restart.

I closed the issue not because I disagree with the intent, but just because this will never be fixed in O1. My recommendation is to prepare for new modules to be on prod, and expect the downtime. And to handle it gracefully you can also use slots I assume. By enabling it on another instance, then switching instances.

**Comment by roballred** [comment]
@sebastienros That is solid advice, thank you.
