### ISSUE TITLE
.NET Core 3.0 (.NET 5)

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#8203]
Since they announced that .NET Core will become .NET 5 and will unite all the frameworks are you guys planing to try to make Orchard 1 work with it? @BenedekFarkas

**Comment by BenedekFarkas** [comment]
We've joked about it that now we have Orchard CMS for .NET Framework, Orchard Core for .NET Core, so the next step is just "Orchard" for .NET. :D
The problem is that we (at least I) don't really have a good grasp on what .NET 5 is (compared to .NET Framework 4.x), but yes, Orchard 1.x should evolve further.
