### ISSUE TITLE
Terms are saved as draft when changing weight and LocalizationExtensions is enabled

### ISSUE THREAD

**Issue by MarcoViglione-Laser** [OrchardCMS/Orchard#8273]
Issue found on dev branch.

Reproduction steps:
- Enable the feature "Orchard.Taxonomies.LocalizationExtensions"
- Create new taxonomy term
- Change its weight
- Save

The term will appear in the list as a draft. Saving it a second time will actually publish it.
I already have a fix, I'll add it soon as a pull request.

**Comment by BenedekFarkas** [comment]
@MarcoViglione-Laser this is not directly related to this issue, but maybe you can help: I noticed that when TaxonomiesLocalizationExtensions is disabled, when I publish a Term (doesn't have to be a Draftable type), there's always two new versions created (and the second of those two will be the Published version). I assume that's because ContentManager.Get is called with DraftRequired, but I guess that's there for a reason...
