### ISSUE TITLE
Indexing log error

### ISSUE THREAD

**Issue by ElenaRepository** [OrchardCMS/Orchard#8331]
In our logs, we have this error message every time the batch operation that updates the indexes is invoked

Orchard.Exceptions.DefaultExceptionPolicy - (null) - An unexpected exception was caught [(null)]
NHibernate.ObjectNotFoundException: No row with the given identifier exists[Orchard.ContentManagement.Records.ContentItemRecord#5840]
   in NHibernate.Impl.SessionFactoryImpl.DefaultEntityNotFoundDelegate.HandleEntityNotFound(String entityName, Object id)
   in NHibernate.Proxy.AbstractLazyInitializer.CheckTargetState()
   in NHibernate.Proxy.DefaultLazyInitializer.Intercept(InvocationInfo info)
   in ContentItemRecordProxy.get_ContentType()
   in Orchard.Indexing.Services.IndexingTaskExecutor.<>c.<BatchIndex>b__20_6(IndexingTaskRecord x)

In my opinion our problem is similar to this issue :  #7987

**Comment by sebastienros** [comment]
Can you log the state of the indexed content item, and if it's in the db when you get this exception? At least locally to understand how this issue is triggered.

**Comment by HermesSbicego-Laser** [comment]
We did some invastigation... The ContentItemRecord is missing in the DB: we have to investigate more deeply to find why is missing, but **it's not the first time we see this problem** (perhaps related to this old issue about concurrency #8082?) .
we see 2 ways to fix it:
1. using not-found="ignore" as proposed here https://stackoverflow.com/questions/695931/nhibernate-no-row-with-the-given-identifier-exists, (but I don't know if it is possible - and I was not able to find an example - to decorate the `ContentItemRecord` property of class `Orchard.Indexing.Models.IndexingTaskRecord` properly)
2. Enforce the check in the where clause (that throws the exception ) testing the type of `ContentItemRecord`: When the `ContentItemRecord` is missing the `x.ContentiTemRecord` is `not null` but it is of type `ContentItemRecordProxy`. In this case the code can be modified in `.Where(x => x.ContentItemRecord != null && x.ContentItemRecord.GetType()==typeof(ContentItemRecord) && x.ContentItemRecord.ContentType != null)`. By our tests it solves the problem.

**Comment by MatteoPiovanelli** [comment]
Hello, pitching in. We did a few more tests on this issue.
In order to reproduce it, you just have to invoke the hard-delete method on an indexed ContentItem (`_contentManager.Destroy(item)`).
At that point, https://github.com/OrchardCMS/Orchard/blob/27e6401965e6be58567642b6beb0cd1223e3f2d4/src/Orchard.Web/Modules/Orchard.Indexing/Services/IndexingTaskExecutor.cs#L228 will throw an exception, because nHibernate is creating a ContentItemRecordProxy whose get_ContentType fails (because the property doesn't really exist).
@HermesSbicego-Laser and I prepared a fix to this, that can be applied to both 1.10.x and dev. A PR is coming soon.
